In [1]:
#a code block that deals with concentration and drug names
#we do not use this block for now.

import pandas as pd
f1 = pd.read_csv('B.csv')
f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('A_ks2.csv')
file = [f1,f2,f3,f5]
train = pd.concat(file,axis=1)
train.to_csv("train.csv", index=0, sep=',')


In [2]:
#do some further processing with "A" because there are some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('A_ks2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('modified_A.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                


-0.294442


In [3]:
#test file A
import pandas as pd
df_A=pd.read_csv("A_ks2.csv")
df_A.shape
#df_A2=pd.read_csv("A_modified.csv")
#df_A2.shape


(767, 239)

In [4]:
#a block that is used to concate the drug names(drug combinations and related concentration)

import csv
res_list=[]
with open('train.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        data=[]
        data.append(row[0]+'+'+row[1]+"+"+row[2])
        res_list.append(data)

        
        
with open('concatenated.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerows(res_list)

In [5]:
#a block that is used to concate concentration and ks numbers.
import pandas as pd
f1 = pd.read_csv('concatenated.csv')
#f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('modified_A.csv')
file = [f1,f5]
train = pd.concat(file,axis=1)
train.to_csv("train3.csv", index=0, sep=',')

In [6]:
#a block that sets the fields for the drug data
import csv
fields=['drug_name','default']
for i in range(1,239):
    fields.append('ks'+str(i))
rows=[]
with open('train3.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        rows.append(row)

        
        
with open('drug_withfields2.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerow(fields)
    writer.writerows(rows)

In [7]:
#do some further processing with "drug_withfields" because there are still some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('drug_withfields2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('drug_with_fields.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                

-0.294442


In [8]:
df=pd.read_csv('drug_with_fields.csv')
#one type first type. dna
df11=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+2') ]
df13=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+3') ]
df14=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+4') ]
df15=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+5') ]
df16=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+6') ]
df21=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+1') ]
df22=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+2') ]
df23=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+3') ]
df24=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+4') ]
df25=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+5') ]
df26=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+6') ]
df31=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df32=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]
df33=df.loc[(df['drug_name'] =='Etoposide+Etoposide+3') ]
df34=df.loc[(df['drug_name'] =='Etoposide+Etoposide+4') ]
df35=df.loc[(df['drug_name'] =='Etoposide+Etoposide+5') ]
df36=df.loc[(df['drug_name'] =='Etoposide+Etoposide+6') ]
df41=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+1') ]
df42=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+2') ]
df43=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+3') ]
df44=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+4') ]
df45=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+5') ]
df46=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+6') ]
frames = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
dna = pd.concat(frames)
dna


drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.184870 -0.099087 -0.128100   
14    Etoposide+Gemcitabine+2        0 -0.160830 -0.130290 -0.207700   
16    Etoposide+Gemcitabine+3        0 -0.251310 -0.090650 -0.233650   
18    Etoposide+Gemcitabine+4        0 -0.182100 -0.064928 -0.196120   
20    Etoposide+Gemcitabine+5        0 -0.125830  0.055525 -0.072723   
22    Etoposide+Gemcitabine+6        0 -0.083361 -0.033312 -0.036934   
72    Gemcitabine+Etoposide+1        0 -0.282500 -0.071655 -0.093233   
74    Gemcitabine+Etoposide+2        0 -0.278330 -0.148370 -0.231830   
76    Gemcitabine+Etoposide+3        0 -0.127020 -0.111580 -0.229470   
78    Gemcitabine+Etoposide+4        0  0.040190 -0.113630 -0.225430   
80    Gemcitabine+Etoposide+5        0  0.112420 -0.125760 -0.167860   
82    Gemcitabine+Etoposide+6        0  0.033567 -0.101750 -0.107470   
0       Etoposide+Etoposide+1        0 -0.275910 -0.090945 -0.219180   
2       Etoposide+Etoposide+2        0 -0.293500 -0.120860 -0.257060   
4       Etoposide+Etoposide+3        0 -0.240420 -0.083899 -0.210410   
6       Etoposide+Etoposide+4        0 -0.047500 -0.083910 -0.118560   
8       Etoposide+Etoposide+5        0  0.033567 -0.055637 -0.082210   
10      Etoposide+Etoposide+6        0 -0.048333 -0.069917 -0.075126   
84  Gemcitabine+Gemcitabine+1        0 -0.147500 -0.110340 -0.136360   
86  Gemcitabine+Gemcitabine+2        0 -0.137500 -0.116870 -0.203430   
88  Gemcitabine+Gemcitabine+3        0 -0.232880 -0.075379 -0.154700   
90  Gemcitabine+Gemcitabine+4        0 -0.120730 -0.122040 -0.264540   
92  Gemcitabine+Gemcitabine+5        0 -0.078761 -0.056834 -0.146080   
94  Gemcitabine+Gemcitabine+6        0  0.075999 -0.072383 -0.093049   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.090660 -0.179700 -0.136530 -0.126740 -0.120790  ...  0.057665  0.114990   
14 -0.101180 -0.231780 -0.226070 -0.216740 -0.206720  ...  0.071715  0.117700   
16 -0.083527 -0.137960 -0.229940 -0.246240 -0.240170  ...  0.112950  0.140700   
18 -0.065672 -0.115260 -0.191780 -0.191640 -0.195310  ...  0.084220  0.127640   
20  0.082487  0.053150 -0.065715 -0.081916 -0.086398  ...  0.097900  0.050722   
22 -0.053729 -0.029681 -0.047214 -0.040963 -0.042845  ... -0.028586  0.065742   
72  0.137140 -0.222910 -0.129930 -0.069211  0.072609  ...  0.098426  0.067214   
74  0.152670 -0.297130 -0.250930 -0.206700 -0.205970  ...  0.120800  0.084633   
76  0.210130 -0.313550 -0.268160 -0.199610 -0.179470  ... -0.065570  0.054781   
78  0.213640 -0.190440 -0.229400 -0.204370 -0.199090  ... -0.058121 -0.046544   
80  0.130490 -0.198560 -0.188520 -0.157870 -0.144860  ... -0.097427 -0.047620   
82  0.093043 -0.162880 -0.106970 -0.094408 -0.092742  ... -0.045023  0.018609   
0   0.151500 -0.261880 -0.247700 -0.203930 -0.191430  ...  0.121660  0.101620   
2  -0.128320 -0.265030 -0.258180 -0.241930 -0.233880  ...  0.117910  0.096803   
4   0.089637 -0.172030 -0.217160 -0.210520 -0.204970  ...  0.105970  0.093028   
6  -0.051050 -0.111450 -0.121400 -0.110790 -0.105290  ...  0.030848 -0.051124   
8   0.047443 -0.061823 -0.086123 -0.073333 -0.072355  ... -0.044610  0.031479   
10  0.068748 -0.065750 -0.071556 -0.067314 -0.065130  ... -0.047176  0.050841   
84  0.150780 -0.266940 -0.183890 -0.094675 -0.079493  ... -0.076809  0.119250   
86  0.159140 -0.272920 -0.219580 -0.193030 -0.184520  ... -0.057089  0.097788   
88  0.102650 -0.176820 -0.165830 -0.149320 -0.141060  ...  0.088712  0.116290   
90  0.139890 -0.233570 -0.269580 -0.256340 -0.255100  ... -0.054707  0.082898   
92  0.152750 -0.076998 -0.142650 -0.144530 -0.148220  ...  0.033027  0.080362   
94  0.159150 -0.141890 -0.101310 -0.079069 -0.076247  ... -0.076269 -0.039469   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.270030  0.151400  0.107700  0.114990 -0.138540 -0.247210 -0.088777   
14 -0.295330  0.153960  0.114980  0.11770

In [9]:

#one type first type. mt
df11=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+1') ]
df12=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+2') ]
df13=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+3') ]
df14=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+4') ]
df15=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+5') ]
df16=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+6') ]
df21=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+2') ]
df23=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+3') ]
df24=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+4') ]
df25=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+5') ]
df26=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+6') ]
df31=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df32=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]
df33=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+3') ]
df34=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+4') ]
df35=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+5') ]
df36=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+6') ]
df41=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+1') ]
df42=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+2') ]
df43=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+3') ]
df44=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+4') ]
df45=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+5') ]
df46=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+6') ]
frames2 = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
mt= pd.concat(frames)
mt



drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.184870 -0.099087 -0.128100   
14    Etoposide+Gemcitabine+2        0 -0.160830 -0.130290 -0.207700   
16    Etoposide+Gemcitabine+3        0 -0.251310 -0.090650 -0.233650   
18    Etoposide+Gemcitabine+4        0 -0.182100 -0.064928 -0.196120   
20    Etoposide+Gemcitabine+5        0 -0.125830  0.055525 -0.072723   
22    Etoposide+Gemcitabine+6        0 -0.083361 -0.033312 -0.036934   
72    Gemcitabine+Etoposide+1        0 -0.282500 -0.071655 -0.093233   
74    Gemcitabine+Etoposide+2        0 -0.278330 -0.148370 -0.231830   
76    Gemcitabine+Etoposide+3        0 -0.127020 -0.111580 -0.229470   
78    Gemcitabine+Etoposide+4        0  0.040190 -0.113630 -0.225430   
80    Gemcitabine+Etoposide+5        0  0.112420 -0.125760 -0.167860   
82    Gemcitabine+Etoposide+6        0  0.033567 -0.101750 -0.107470   
0       Etoposide+Etoposide+1        0 -0.275910 -0.090945 -0.219180   
2       Etoposide+Etoposide+2        0 -0.293500 -0.120860 -0.257060   
4       Etoposide+Etoposide+3        0 -0.240420 -0.083899 -0.210410   
6       Etoposide+Etoposide+4        0 -0.047500 -0.083910 -0.118560   
8       Etoposide+Etoposide+5        0  0.033567 -0.055637 -0.082210   
10      Etoposide+Etoposide+6        0 -0.048333 -0.069917 -0.075126   
84  Gemcitabine+Gemcitabine+1        0 -0.147500 -0.110340 -0.136360   
86  Gemcitabine+Gemcitabine+2        0 -0.137500 -0.116870 -0.203430   
88  Gemcitabine+Gemcitabine+3        0 -0.232880 -0.075379 -0.154700   
90  Gemcitabine+Gemcitabine+4        0 -0.120730 -0.122040 -0.264540   
92  Gemcitabine+Gemcitabine+5        0 -0.078761 -0.056834 -0.146080   
94  Gemcitabine+Gemcitabine+6        0  0.075999 -0.072383 -0.093049   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.090660 -0.179700 -0.136530 -0.126740 -0.120790  ...  0.057665  0.114990   
14 -0.101180 -0.231780 -0.226070 -0.216740 -0.206720  ...  0.071715  0.117700   
16 -0.083527 -0.137960 -0.229940 -0.246240 -0.240170  ...  0.112950  0.140700   
18 -0.065672 -0.115260 -0.191780 -0.191640 -0.195310  ...  0.084220  0.127640   
20  0.082487  0.053150 -0.065715 -0.081916 -0.086398  ...  0.097900  0.050722   
22 -0.053729 -0.029681 -0.047214 -0.040963 -0.042845  ... -0.028586  0.065742   
72  0.137140 -0.222910 -0.129930 -0.069211  0.072609  ...  0.098426  0.067214   
74  0.152670 -0.297130 -0.250930 -0.206700 -0.205970  ...  0.120800  0.084633   
76  0.210130 -0.313550 -0.268160 -0.199610 -0.179470  ... -0.065570  0.054781   
78  0.213640 -0.190440 -0.229400 -0.204370 -0.199090  ... -0.058121 -0.046544   
80  0.130490 -0.198560 -0.188520 -0.157870 -0.144860  ... -0.097427 -0.047620   
82  0.093043 -0.162880 -0.106970 -0.094408 -0.092742  ... -0.045023  0.018609   
0   0.151500 -0.261880 -0.247700 -0.203930 -0.191430  ...  0.121660  0.101620   
2  -0.128320 -0.265030 -0.258180 -0.241930 -0.233880  ...  0.117910  0.096803   
4   0.089637 -0.172030 -0.217160 -0.210520 -0.204970  ...  0.105970  0.093028   
6  -0.051050 -0.111450 -0.121400 -0.110790 -0.105290  ...  0.030848 -0.051124   
8   0.047443 -0.061823 -0.086123 -0.073333 -0.072355  ... -0.044610  0.031479   
10  0.068748 -0.065750 -0.071556 -0.067314 -0.065130  ... -0.047176  0.050841   
84  0.150780 -0.266940 -0.183890 -0.094675 -0.079493  ... -0.076809  0.119250   
86  0.159140 -0.272920 -0.219580 -0.193030 -0.184520  ... -0.057089  0.097788   
88  0.102650 -0.176820 -0.165830 -0.149320 -0.141060  ...  0.088712  0.116290   
90  0.139890 -0.233570 -0.269580 -0.256340 -0.255100  ... -0.054707  0.082898   
92  0.152750 -0.076998 -0.142650 -0.144530 -0.148220  ...  0.033027  0.080362   
94  0.159150 -0.141890 -0.101310 -0.079069 -0.076247  ... -0.076269 -0.039469   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.270030  0.151400  0.107700  0.114990 -0.138540 -0.247210 -0.088777   
14 -0.295330  0.153960  0.114980  0.11770

In [10]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames3=[]
for i in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+AUY922+'+str(i)) ])
for j in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+17AAG+'+str(j)) ])
for k in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+AUY922+'+str(k)) ])
for m in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+17AAG+'+str(m)) ])
HSP= pd.concat(frames3)
HSP


drug_name  default       ks1       ks2       ks3       ks4  \
397   17AAG+AUY922+1        0 -0.293330 -0.153810 -0.168630 -0.126450   
399   17AAG+AUY922+2        0 -0.442500 -0.169570 -0.264150  0.134970   
401   17AAG+AUY922+3        0 -0.447500 -0.158600 -0.244360 -0.137810   
403   17AAG+AUY922+4        0 -0.291720 -0.116050 -0.256050  0.108790   
405   17AAG+AUY922+5        0 -0.051667 -0.043185 -0.075513  0.063609   
407   17AAG+AUY922+6        0 -0.027500 -0.036471 -0.078881  0.093110   
457   AUY922+17AAG+1        0 -0.032740 -0.061780  0.080494 -0.077161   
459   AUY922+17AAG+2        0 -0.100830 -0.114660 -0.211770 -0.096207   
461   AUY922+17AAG+3        0 -0.246980 -0.129550 -0.288340  0.155660   
463   AUY922+17AAG+4        0 -0.218750 -0.102870 -0.253970  0.147240   
465   AUY922+17AAG+5        0  0.046269 -0.099380 -0.162230  0.120990   
467   AUY922+17AAG+6        0  0.071875 -0.083333 -0.094583  0.143120   
469  AUY922+AUY922+1        0 -0.261670 -0.129740 -0.160260  0.137500   
471  AUY922+AUY922+2        0 -0.252930 -0.115000 -0.180040 -0.087114   
473  AUY922+AUY922+3        0 -0.257500 -0.130040 -0.216640 -0.116110   
475  AUY922+AUY922+4        0 -0.225150 -0.113680 -0.224070 -0.124950   
477  AUY922+AUY922+5        0 -0.119690  0.032366 -0.105430  0.079650   
479  AUY922+AUY922+6        0  0.037551 -0.038885 -0.038110 -0.062008   
385    17AAG+17AAG+1        0 -0.228080 -0.106320 -0.165770 -0.088614   
387    17AAG+17AAG+2        0 -0.280000 -0.129130 -0.249310 -0.113230   
389    17AAG+17AAG+3        0 -0.218750 -0.095024 -0.250190 -0.122380   
391    17AAG+17AAG+4        0  0.033386 -0.139580 -0.191310 -0.103220   
393    17AAG+17AAG+5        0  0.028372 -0.078293 -0.089651 -0.076141   
395    17AAG+17AAG+6        0 -0.064436 -0.075579 -0.120600  0.118820   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
397 -0.315680 -0.174020 -0.146800 -0.147340  ...  0.086603  0.134620   
399 -0.336240 -0.265020 -0.240410 -0.229120  ...  0.149120  0.126060   
401 -0.334700 -0.250510 -0.233340 -0.227700  ...  0.141520  0.157670   
403 -0.231450 -0.250510 -0.246450 -0.252550  ...  0.129950  0.090215   
405 -0.036511 -0.076548 -0.074988 -0.078437  ...  0.054169  0.035543   
407 -0.087237 -0.083087 -0.071404 -0.061644  ... -0.034032 -0.049821   
457 -0.222740 -0.111770  0.089944  0.135550  ... -0.097147  0.042260   
459 -0.303180 -0.239620 -0.184140 -0.162510  ... -0.091839  0.064842   
461 -0.330310 -0.291760 -0.266100 -0.271020  ...  0.135770  0.077002   
463 -0.222000 -0.272770 -0.240000 -0.237550  ...  0.103810  0.096509   
465 -0.188280 -0.170210 -0.138730 -0.145950  ... -0.055037  0.035004   
467 -0.113750 -0.100000 -0.081458 -0.081042  ... -0.061458 -0.053542   
469 -0.290380 -0.181600 -0.127050 -0.128010  ...  0.074295  0.126670   
471 -0.220200 -0.187890 -0.166990 -0.162260  ...  0.081667  0.140260   
473 -0.326200 -0.225840 -0.202500 -0.192370  ...  0.077697  0.099904   
475 -0.229360 -0.216720 -0.216470 -0.217700  ...  0.082108  0.067500   
477 -0.037983 -0.092926 -0.103120 -0.105500  ...  0.093887  0.036005   
479  0.027206 -0.031638 -0.038090 -0.038676  ... -0.059064  0.056433   
385 -0.230360 -0.184890 -0.157880 -0.152480  ...  0.093090  0.116110   
387 -0.309440 -0.259060 -0.238100 -0.226520  ...  0.078893  0.133820   
389 -0.200520 -0.250520 -0.246000 -0.237670  ...  0.098929  0.093747   
391 -0.176450 -0.177650 -0.183810 -0.188840  ... -0.058823 -0.043850   
393 -0.081104 -0.082424 -0.084659 -0.085631  ... -0.052951  0.034716   
395 -0.177460 -0.125080 -0.098109 -0.104420  ... -0.033004  0.068947   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
397 -0.204080  0.194780  0.145140  0.134620 -0.275390 -0.296960 -0.164450   
399 -0.250120  0.300720  0.219990  0.126060 -0.265570 -0.344980 -0.127390   
401 -0.315380  0.283470  0.224310  0.157670 -0.251890 -0.373510 -0.120390   
403 -0.161320  0.210750  0.196160  0.090215 -0.127900 -0.232530 -0.091183   

In [11]:
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin

frames4=[]
for i in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+PS341+'+str(i)) ])
for j in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+MG132+'+str(j)) ])
for k in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+MG132+'+str(k)) ])
for m in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+PS341+'+str(m)) ])
PROT= pd.concat(frames4)
PROT

drug_name  default       ks1       ks2       ks3       ks4       ks5  \
541  MG132+PS341+1        0 -0.387500 -0.040572  0.050581 -0.109290 -0.132140   
543  MG132+PS341+2        0 -0.335830  0.034141 -0.118200 -0.077122 -0.073561   
545  MG132+PS341+3        0 -0.142500 -0.044847 -0.080432 -0.043360 -0.079804   
547  MG132+PS341+4        0 -0.190830 -0.037294 -0.078637 -0.036844 -0.091070   
549  MG132+PS341+5        0  0.031805 -0.048918  0.037312 -0.087379 -0.037340   
551  MG132+PS341+6        0  0.094591  0.037042  0.057213 -0.081726  0.081437   
601  PS341+MG132+1        0 -0.395830  0.059105  0.216230 -0.100640 -0.157240   
603  PS341+MG132+2        0 -0.276670  0.062264  0.100680  0.039324  0.066627   
605  PS341+MG132+3        0 -0.127240  0.160770  0.283210  0.045385  0.096987   
607  PS341+MG132+4        0 -0.139170  0.158150  0.214130  0.046812  0.085973   
609  PS341+MG132+5        0  0.037551 -0.028288  0.040840 -0.068561  0.054094   
611  PS341+MG132+6        0  0.054481 -0.066327 -0.036923 -0.063545 -0.054834   
529  MG132+MG132+1        0 -0.369370 -0.039704  0.074651 -0.048647 -0.152410   
531  MG132+MG132+2        0 -0.195000 -0.057219 -0.112140  0.105680 -0.192430   
533  MG132+MG132+3        0 -0.155830  0.152270  0.171700  0.078818  0.046350   
535  MG132+MG132+4        0 -0.107500 -0.072596 -0.026868  0.121210 -0.129900   
537  MG132+MG132+5        0  0.038066 -0.066688 -0.070599 -0.039374 -0.093137   
539  MG132+MG132+6        0 -0.035000 -0.052381 -0.066146 -0.060091 -0.069101   
613  PS341+PS341+1        0 -0.427500  0.054120  0.103770 -0.091583 -0.106960   
615  PS341+PS341+2        0 -0.369370  0.061470  0.075251 -0.083468 -0.035296   
617  PS341+PS341+3        0 -0.255970  0.026078  0.060000 -0.058066  0.055841   
619  PS341+PS341+4        0 -0.189440 -0.022987  0.051309 -0.029157 -0.047565   
621  PS341+PS341+5        0 -0.033869 -0.062432 -0.027983 -0.034977 -0.068250   
623  PS341+PS341+6        0  0.035997 -0.032960  0.036705 -0.059943  0.056233   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
541 -0.050760  0.061356  0.084985  ... -0.204980  0.079745  0.140250   
543 -0.133240 -0.117210 -0.104990  ... -0.127550  0.280070 -0.184360   
545 -0.080672 -0.081859 -0.084001  ... -0.135790  0.229760 -0.094110   
547 -0.083961 -0.067137 -0.060997  ...  0.139790 -0.035300 -0.113180   
549  0.030442  0.043002  0.043913  ...  0.031882 -0.075684  0.036330   
551  0.056910  0.059571  0.051433  ... -0.072965 -0.054048 -0.044131   
601  0.172770  0.239260  0.275130  ... -0.207250 -0.188670  0.212440   
603  0.091175  0.102350  0.116600  ... -0.065144 -0.135930  0.153540   
605  0.246280  0.280510  0.290830  ...  0.071474 -0.151920  0.078205   
607  0.165600  0.206240  0.219880  ...  0.087731 -0.115330  0.019833   
609  0.040156  0.042985  0.039213  ...  0.055517 -0.107330  0.032639   
611 -0.041196 -0.036861 -0.038683  ... -0.063513  0.026103 -0.035980   
529 -0.045573  0.077823  0.102910  ... -0.147200 -0.092769  0.242970   
531 -0.126020 -0.087772 -0.087753  ... -0.122650  0.204600 -0.091255   
533  0.109300  0.185150  0.200720  ...  0.114060 -0.154260  0.127220   
535 -0.054158  0.026763  0.045888  ...  0.071918 -0.089828 -0.056244   
537 -0.067952 -0.053273 -0.051117  ... -0.049973 -0.093121 -0.028322   
539 -0.066046 -0.071606 -0.073575  ... -0.033541  0.044653 -0.056230   
613  0.047951  0.111550  0.135480  ... -0.152120 -0.171710  0.190040   
615  0.058970  0.073763  0.093683  ... -0.088342 -0.151470  0.160060   
617  0.058043  0.064442  0.067018  ... -0.052982 -0.111910  0.126800   
619  0.035954  0.048763  0.068897  ...  0.123470 -0.078087 -0.055685   
621 -0.036331 -0.022500  0.025667  ...  0.031550 -0.097590  0.036938   
623  0.036864 -0.038279  0.036501  ...  0.033410 -0.040573 -0.066561   

        ks232     ks233     ks234     ks235     ks236     ks237     ks238  
541 -0.144130 -0.129300  0.079745  0.155880  0.133880 -0.133970 -0.108340  
543  0.197100  0.102810  0.280

In [12]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames5=[]
for i in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+Apicidin+'+str(i)) ])
for j in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+SAHA+'+str(j)) ])
for k in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+Apicidin+'+str(k)) ])
for m in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+SAHA+'+str(m)) ])
HDAC= pd.concat(frames5)
HDAC

drug_name  default       ks1       ks2       ks3       ks4  \
672      SAHA+Apicidin+1        0 -0.059834  0.340110  0.390130  0.077932   
674      SAHA+Apicidin+2        0 -0.109790  0.332810  0.336710  0.109790   
676      SAHA+Apicidin+3        0  0.038581  0.241160  0.237870  0.074451   
678      SAHA+Apicidin+4        0 -0.069082  0.079449  0.059266  0.112430   
680      SAHA+Apicidin+5        0 -0.106250 -0.043794 -0.063867  0.057435   
682      SAHA+Apicidin+6        0  0.044009 -0.060000 -0.051537 -0.041997   
289      Apicidin+SAHA+1        0 -0.129170  0.333380  0.365980  0.098066   
291      Apicidin+SAHA+2        0 -0.138660  0.363450  0.402400  0.097388   
293      Apicidin+SAHA+3        0  0.090836  0.224790  0.228740  0.093226   
295      Apicidin+SAHA+4        0  0.029024  0.096415  0.108240  0.055246   
297      Apicidin+SAHA+5        0 -0.045142  0.041572  0.064937 -0.027956   
299      Apicidin+SAHA+6        0  0.039756 -0.059731 -0.070248  0.050746   
673  Apicidin+Apicidin+1        0 -0.214600  0.389600  0.424420  0.120690   
675  Apicidin+Apicidin+2        0 -0.035000  0.318060  0.344260  0.105320   
677  Apicidin+Apicidin+3        0 -0.082093  0.268840  0.241990  0.083841   
679  Apicidin+Apicidin+4        0 -0.035000  0.094167  0.080227  0.093636   
681  Apicidin+Apicidin+5        0 -0.044167 -0.035503  0.032462  0.044966   
683  Apicidin+Apicidin+6        0 -0.036667 -0.047998 -0.057048  0.073265   
288          SAHA+SAHA+1        0 -0.138660  0.366480  0.435790  0.083339   
290          SAHA+SAHA+2        0 -0.095833  0.340920  0.385140  0.079212   
292          SAHA+SAHA+3        0  0.051307  0.236780  0.229990  0.083399   
294          SAHA+SAHA+4        0  0.058049  0.083817  0.101000  0.054505   
296          SAHA+SAHA+5        0 -0.053333 -0.051991 -0.067236  0.042680   
298          SAHA+SAHA+6        0 -0.069216 -0.050392 -0.063284 -0.035931   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
672  0.290870  0.363330  0.383150  0.378910  ...  0.088412  0.119260   
674  0.283200  0.324080  0.329100  0.325440  ...  0.099784  0.150050   
676  0.297730  0.235490  0.224600  0.216060  ...  0.059385 -0.058055   
678  0.085854  0.057440  0.059194  0.059365  ...  0.082106 -0.057335   
680 -0.073059 -0.061508 -0.055215 -0.054832  ...  0.053144  0.039696   
682 -0.070790 -0.058190 -0.043190 -0.031782  ... -0.046509 -0.051552   
289  0.278300  0.344320  0.378700  0.379170  ...  0.047252  0.155370   
291  0.306650  0.388850  0.402590  0.401620  ...  0.096812  0.192400   
293  0.304810  0.227980  0.209440  0.201790  ... -0.040253  0.039815   
295  0.168910  0.107680  0.095182  0.093516  ...  0.027556 -0.054533   
297  0.091053  0.074009  0.060519  0.064104  ...  0.027814  0.022406   
299 -0.063347 -0.073193 -0.062410 -0.059101  ... -0.059957  0.033753   
673  0.323700  0.392860  0.433190  0.436160  ...  0.121560  0.146960   
675  0.266340  0.320190  0.349080  0.347260  ...  0.080862  0.088018   
677  0.271080  0.239880  0.225080  0.225160  ...  0.111910  0.078374   
679  0.100380  0.074015  0.078258  0.075758  ...  0.060000 -0.080833   
681  0.026965  0.036185  0.037325  0.037404  ...  0.050600 -0.030612   
683 -0.064164 -0.064066 -0.039407 -0.041638  ...  0.033442 -0.043986   
288  0.314940  0.412460  0.424920  0.428980  ...  0.053367  0.145810   
290  0.259180  0.359630  0.385400  0.385200  ...  0.083685  0.135250   
292  0.298260  0.226510  0.223090  0.208060  ...  0.037662  0.039134   
294  0.130480  0.107850  0.089163  0.088013  ... -0.040156 -0.069032   
296 -0.021477 -0.059421 -0.063338 -0.060349  ...  0.035254 -0.028119   
298 -0.045343 -0.060000 -0.061912 -0.063676  ...  0.046275  0.039706   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
672 -0.191370  0.191600  0.133780  0.119260 -0.053923 -0.145330 -0.073195   
674 -0.197280  0.252150  0.189730  0.150050 -0.093772 -0.178180 -0.086238   
676 -0.046870  0.046923  0.047125 -0.058055  0.161690  0.

In [13]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames6=[]
for i in range(1,7):
    frames6.append(df.loc[(df['drug_name'] =='DMSO+DMSO+'+str(i)) ])

DMSO= pd.concat(frames6)
DMSO
#len(DMSO)


drug_name  default       ks1       ks2       ks3       ks4       ks5  \
360  DMSO+DMSO+1        0 -0.040458  0.041631 -0.033216  0.089519  0.035493   
361  DMSO+DMSO+1        0  0.028564 -0.038257 -0.049343  0.047224  0.030922   
372  DMSO+DMSO+1        0  0.090836  0.042936  0.051533  0.033143  0.080786   
373  DMSO+DMSO+1        0  0.077589 -0.058936 -0.059840  0.056152 -0.044450   
744  DMSO+DMSO+1        0  0.049394  0.068186  0.071101  0.054791  0.083623   
745  DMSO+DMSO+1        0  0.138140  0.031667  0.029423  0.033269  0.031410   
756  DMSO+DMSO+1        0 -0.036667  0.025263 -0.037774 -0.029886 -0.025616   
757  DMSO+DMSO+1        0 -0.027500  0.045976  0.047774  0.067184  0.056997   
362  DMSO+DMSO+2        0 -0.034665  0.037463  0.034453  0.047030  0.078444   
363  DMSO+DMSO+2        0  0.048748  0.025792  0.048283  0.062357  0.057030   
374  DMSO+DMSO+2        0  0.029024 -0.019078 -0.028211  0.046319  0.036928   
375  DMSO+DMSO+2        0 -0.100830 -0.030089 -0.020413 -0.053206  0.046864   
746  DMSO+DMSO+2        0 -0.035000  0.036750  0.031538  0.048164  0.039679   
747  DMSO+DMSO+2        0  0.155350  0.045161  0.037836  0.040964  0.051214   
758  DMSO+DMSO+2        0 -0.039885 -0.028966 -0.037557  0.065977 -0.024511   
759  DMSO+DMSO+2        0  0.043282 -0.030620  0.028999  0.039496  0.029962   
364  DMSO+DMSO+3        0 -0.060833  0.043738  0.034322  0.020532  0.054267   
365  DMSO+DMSO+3        0 -0.054167 -0.037860 -0.078285  0.144870 -0.105070   
376  DMSO+DMSO+3        0 -0.074167  0.029225  0.046846  0.036556  0.049191   
377  DMSO+DMSO+3        0 -0.030833 -0.041578 -0.024546 -0.073358  0.057323   
748  DMSO+DMSO+3        0  0.044734 -0.055579 -0.046694  0.051509 -0.067315   
749  DMSO+DMSO+3        0  0.059126  0.035217  0.037866  0.058552  0.047368   
760  DMSO+DMSO+3        0 -0.035000 -0.035334 -0.041146 -0.070236 -0.025562   
761  DMSO+DMSO+3        0 -0.050833  0.036774  0.031280 -0.055583  0.030092   
366  DMSO+DMSO+4        0  0.053004 -0.035733 -0.037271 -0.031932  0.023626   
367  DMSO+DMSO+4        0  0.036243 -0.028715 -0.028771  0.026879  0.042090   
378  DMSO+DMSO+4        0 -0.149770 -0.039126 -0.029577 -0.067855  0.024344   
379  DMSO+DMSO+4        0 -0.116840  0.041439  0.029134 -0.049989  0.055714   
750  DMSO+DMSO+4        0 -0.033869 -0.042376 -0.046686  0.053937 -0.024178   
751  DMSO+DMSO+4        0  0.130420 -0.052241 -0.062605  0.058220 -0.073390   
762  DMSO+DMSO+4        0 -0.046188  0.027480  0.029646 -0.045633 -0.026490   
763  DMSO+DMSO+4        0 -0.065594  0.049508  0.055270 -0.085126  0.075701   
368  DMSO+DMSO+5        0  0.108760 -0.058930 -0.080637  0.021223 -0.034893   
369  DMSO+DMSO+5        0  0.030398  0.031491  0.041896  0.045956  0.042806   
380  DMSO+DMSO+5        0 -0.049167  0.027813 -0.031647  0.045554  0.046973   
381  DMSO+DMSO+5        0 -0.110760  0.035309  0.061684 -0.076701  0.066701   
752  DMSO+DMSO+5        0 -0.041032 -0.052054 -0.050206  0.030538  0.041415   
753  DMSO+DMSO+5        0  0.037551 -0.023850 -0.048429  0.031277  0.043765   
764  DMSO+DMSO+5        0 -0.052500  0.034735  0.037764 -0.095677  0.032901   
765  DMSO+DMSO+5        0 -0.035000 -0.029732 -0.024797 -0.089169  0.038979   
370  DMSO+DMSO+6        0  0.178330 -0.052500 -0.051389  0.079167 -0.044352   
371  DMSO+DMSO+6        0  0.075999 -0.020794 -0.033651  0.056283  0.053008   
382  DMSO+DMSO+6        0 -0.194710  0.049312  0.061884 -0.049855  0.068514   
383  DMSO+DMSO+6        0 -0.158330  0.057385  0.059397  0.030316  0.039397   
754  DMSO+DMSO+6        0 -0.035000 -0.042247 -0.071477  0.072036 -0.055685   
755  DMSO+DMSO+6        0  0.052609  0.040490  0.033616 -0.031387  0.053315   
766  DMSO+DMSO+6        0 -0.063281  0.056212  0.060275 -0.077504  0.040267   
767  DMSO+DMSO+6        0 -0.035000  0.032537  0.038507  0.082728 -0.038154   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
360 -0.048932  0.033310  0.037242  ...  0.044847  0.039354 -0.0

In [14]:
combi=frames+frames2+frames3+frames4+frames5+frames6
training= pd.concat(combi)
print(training)
print(len(training))



                   drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.184870 -0.099087 -0.128100 -0.090660   
14   Etoposide+Gemcitabine+2        0 -0.160830 -0.130290 -0.207700 -0.101180   
16   Etoposide+Gemcitabine+3        0 -0.251310 -0.090650 -0.233650 -0.083527   
18   Etoposide+Gemcitabine+4        0 -0.182100 -0.064928 -0.196120 -0.065672   
20   Etoposide+Gemcitabine+5        0 -0.125830  0.055525 -0.072723  0.082487   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.158330  0.057385  0.059397  0.030316   
754              DMSO+DMSO+6        0 -0.035000 -0.042247 -0.071477  0.072036   
755              DMSO+DMSO+6        0  0.052609  0.040490  0.033616 -0.031387   
766              DMSO+DMSO+6        0 -0.063281  0.056212  0.060275 -0.077504   
767              DMSO+DMSO+6        0 -0.035000  0.032537  0.038507  0.082728   

          ks5       ks6    

In [15]:
#lda model
#just sample
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X_drug=training.iloc[:, 3:240].values

y=[]
for i in range(24):
    y.append('DNA')
for j in range(24):
    y.append('MT')
for k in range(24):
    y.append('HSP')
for m in range(24):
    y.append('PROT')
for n in range(24):
    y.append('HDAC')
for k in range(48):
    y.append('DMSO')
print(len(X_drug[0]))
model = LinearDiscriminantAnalysis(n_components=4)
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
#reduce dimension for the data
X_drug2=model.fit(X_drug,y).transform(X_drug)
X_drug2
print(len(X_drug2[0]))



237
4


In [16]:
print(len(X_drug2))
print(X_drug2[-1])

168
[-12.34000887  -0.68951806   0.9604731    1.36112621]


In [17]:
#wipe out those whose concentration is not valid
def get_centroid(point_lst):
    x_sum=0
    y_sum=0
    z1_sum=0
    z2_sum=0
    z3_sum=0
    z4_sum=0


    for i in range(len(point_lst)):
        x_sum+=point_lst[i][0]
        y_sum+=point_lst[i][1]
        z1_sum+=point_lst[i][2]
        z2_sum+=point_lst[i][3]
        #z3_sum+=point_lst[i][4]
        #z4_sum+=point_lst[i][5]


    x_mean=x_sum/len(point_lst)
    y_mean=y_sum/len(point_lst)
    z1_mean=z1_sum/len(point_lst)
    z2_mean=z2_sum/len(point_lst)
    #z3_mean=z3_sum/len(point_lst)
    #z4_mean=z4_sum/len(point_lst)
    centroid=[]
    centroid.append(x_mean)
    centroid.append(y_mean)
    centroid.append(z1_mean)
    centroid.append(z2_mean)
    #centroid.append(z3_mean)
    #centroid.append(z4_mean)
    #centroid.append(point_lst[0][-1])
    return centroid



In [18]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                10.525797              -1.095634               3.747846   
1                 9.000980              -1.333177               5.046633   
2                 7.880334              -3.287024               3.999122   
3                 7.551847              -2.815300               4.554244   
4                 7.896075              -2.283806               4.823695   
..                     ...                    ...                    ...   
163             -11.937962              -0.432295               1.855338   
164             -13.064600              -1.948426               1.964826   
165             -11.650386              -0.087742               0.813444   
166             -13.272099               0.541192               0.418920   
167             -12.340009              -0.689518               0.960473   

     principal component 4  
0                -0.021216  
1                 0.778640  
2                 0.067940  
3                -0.182876  
4                -0.758695  
..                     ...  
163               0.705735  
164               0.004238  
165              -0.072147  
166              -0.417235  
167               1.361126  

[168 rows x 4 columns]

In [19]:
#predict
#still sample but useful this block 
#model2 = LinearDiscriminantAnalysis(n_components=1)
#model2.fit(X_drug2,y)
#row=X_drug2
#yhat = model2.predict(row)
# summarize prediction
#print('Predicted Class: %s' % yhat)



In [20]:
all_list=[]

for i in range(len(X_drug2)):
    all_list.append(X_drug2[i])
print(len(all_list))
all_list[120:127]

168


[array([-12.14480197,  -0.50220388,   2.35741992,   0.82286599]),
 array([-11.88122946,  -1.31993759,   1.88341227,   0.29844214]),
 array([-14.03363588,  -0.97136597,   0.29867279,  -0.50022972]),
 array([-13.20621967,  -0.7820917 ,   1.87527133,  -0.07498161]),
 array([-12.1288692 ,   0.29932025,  -1.98083523,  -0.32902043]),
 array([-12.07912491,   1.03115142,   1.74718257,  -0.71012883]),
 array([-12.80260447,  -0.59329959,   0.59607683,  -0.13443053])]

In [21]:
X_training=[]
X_testing=[]
#X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]+all_list[120]
X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]
for i in range(120,168,8):
    X_training+=all_list[i:i+7]

X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
for j in range(120,168,8):
    X_testing.append(all_list[j])
    print(all_list[j])

#X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
#X_testing.append()
print(len(X_training))
print(len(X_testing))
y=[]
for i in range(18):
    y.append('DNA')
for j in range(18):
    y.append("MT")
for k in range(18):
    y.append("HSP")
for m in range(18):
    y.append("PROT")
for n in range(18):
    y.append("HDAC")
for k in range(42):
    y.append("DMSO")


[-12.14480197  -0.50220388   2.35741992   0.82286599]
[-12.25047433  -0.9865331    1.08839789  -1.26548623]
[-13.78162735  -2.50209005  -0.0598096   -1.01060139]
[-11.46901793   0.85684053   1.44292434   0.40526427]
[-10.92319686  -0.91180669   0.23448483   0.28999717]
[-13.73655346  -1.98352676   1.87405618  -1.72973024]
132
36


In [22]:

dmso_lst2=[]
for i in range(48):
    dmso_lst2.append(all_list[i+120])
print(len(dmso_lst2))
cen_dmso=get_centroid(dmso_lst2)
print(cen_dmso)


48
[-12.728719243958052, -0.595491341701775, 0.9845714026224407, -0.37428662208962576]


In [23]:
#calculating the distance
from math import sqrt
def euclidean_distance(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(len(row1)-1):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [24]:
dist_lst=[]
for i in range(len(dmso_lst2)):
    dist_lst.append(euclidean_distance(dmso_lst2[i],cen_dmso))
dist_lst.sort()
print(len(dist_lst))
max_ave=sum(dist_lst[-5:-1])/len(dist_lst[-5:-1])
max_ave
max_ave*=2
max_ave


48


5.372530684652879

In [25]:
#selecting data
effect=[]
dist_lst2=[]
for i in range(120):
    selection_dist=euclidean_distance(all_list[i],cen_dmso)
    dist_lst2.append(selection_dist)
dist_lst2.sort()
print(dist_lst2[0])

14.041814537058837


In [26]:
model2 = LinearDiscriminantAnalysis(n_components=4)
model2.fit(X_training,y)
yhat2=model2.predict(X_testing)

print(yhat2)
print(len(yhat2))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [27]:
def accuracy(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(int(length/6.0)):
        list3.append(list2[0])
    for j in range(int(length/6.0)):
        list3.append(list2[1])
    for m in range(int(length/6.0)):
        list3.append(list2[2])
    for n in range(int(length/6.0)):
        list3.append(list2[3])
    for k in range(int(length/6.0)):
        list3.append(list2[4])
    for k in range(int(length/6.0)):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [28]:
#test accuracy
'%.2f%%' % ((accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))*100)


'100.00%'

In [29]:
training["drug_name"]
train_drug_name_without_concentration=[]
for each in training['drug_name']:
    train_drug_name_without_concentration.append(each[:-2])
    #print(training["drug_name"][i][0:-1])
    

train_drug_name_without_concentration
train_drug_name_without_concentration2=[]
#dna,mt,hsp,prot,hdac
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('DNA')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('MT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HSP')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('PROT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HDAC')
for i in range(48):
    train_drug_name_without_concentration2.append("DMSO")

train_drug_name_without_concentration2   


['DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'DMSO',
 'DMSO'

In [30]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append('DMSO')
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=train_drug_name_without_concentration2)
#training['drug_name']
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [31]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append("DMSO")
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=training['drug_name'])
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [32]:
# Create a function
def select_n_components(var_ratio, goal_var: float) -> int:
    # Set initial variance explained so far
    total_variance = 0.0
    
    # Set initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for explained_variance in var_ratio:
        
        # Add the explained variance to the total
        total_variance += explained_variance
        
        # Add one to the number of components
        n_components += 1
        
        # If we reach our goal level of explained variance
        if total_variance >= goal_var:
            # End the loop
            break
            
    # Return the number of components
    return n_components

In [33]:
lda = LinearDiscriminantAnalysis(n_components=None)
y5=[]
for i in range(18):
    y5.append('DNA')
for j in range(18):
    y5.append("MT")
for k in range(18):
    y5.append("HSP")
for m in range(18):
    y5.append("PROT")
for n in range(18):
    y5.append("HDAC")
for k in range(42):
    y5.append("DMSO")

X_lda=lda.fit(X_training,y5)


In [34]:
# Create array of explained variance ratios
lda_var_ratios = lda.explained_variance_ratio_
lda_var_ratios

array([0.56989838, 0.1924261 , 0.1336627 , 0.10401281])

In [35]:
# Run function
print(select_n_components(lda_var_ratios, 0.95))
print(select_n_components(lda_var_ratios, 0.85))
print(select_n_components(lda_var_ratios, 0.75))
print(select_n_components(lda_var_ratios, 0.65))
print(select_n_components(lda_var_ratios, 0.35))


4
3
2
2
1


In [36]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                10.525797              -1.095634               3.747846   
1                 9.000980              -1.333177               5.046633   
2                 7.880334              -3.287024               3.999122   
3                 7.551847              -2.815300               4.554244   
4                 7.896075              -2.283806               4.823695   
..                     ...                    ...                    ...   
163             -11.937962              -0.432295               1.855338   
164             -13.064600              -1.948426               1.964826   
165             -11.650386              -0.087742               0.813444   
166             -13.272099               0.541192               0.418920   
167             -12.340009              -0.689518               0.960473   

     principal component 4  
0                -0.021216  
1                 0.778640  
2                 0.067940  
3                -0.182876  
4                -0.758695  
..                     ...  
163               0.705735  
164               0.004238  
165              -0.072147  
166              -0.417235  
167               1.361126  

[168 rows x 4 columns]

In [37]:
training

drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.184870 -0.099087 -0.128100 -0.090660   
14   Etoposide+Gemcitabine+2        0 -0.160830 -0.130290 -0.207700 -0.101180   
16   Etoposide+Gemcitabine+3        0 -0.251310 -0.090650 -0.233650 -0.083527   
18   Etoposide+Gemcitabine+4        0 -0.182100 -0.064928 -0.196120 -0.065672   
20   Etoposide+Gemcitabine+5        0 -0.125830  0.055525 -0.072723  0.082487   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.158330  0.057385  0.059397  0.030316   
754              DMSO+DMSO+6        0 -0.035000 -0.042247 -0.071477  0.072036   
755              DMSO+DMSO+6        0  0.052609  0.040490  0.033616 -0.031387   
766              DMSO+DMSO+6        0 -0.063281  0.056212  0.060275 -0.077504   
767              DMSO+DMSO+6        0 -0.035000  0.032537  0.038507  0.082728   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12  -0.179700 -0.136530 -0.126740 -0.120790  ...  0.057665  0.114990   
14  -0.231780 -0.226070 -0.216740 -0.206720  ...  0.071715  0.117700   
16  -0.137960 -0.229940 -0.246240 -0.240170  ...  0.112950  0.140700   
18  -0.115260 -0.191780 -0.191640 -0.195310  ...  0.084220  0.127640   
20   0.053150 -0.065715 -0.081916 -0.086398  ...  0.097900  0.050722   
..        ...       ...       ...       ...  ...       ...       ...   
383  0.039397  0.068621  0.057098  0.052644  ...  0.050115  0.066063   
754 -0.055685 -0.064447 -0.061233 -0.068129  ... -0.025266  0.034931   
755  0.053315  0.034489  0.030144  0.027769  ... -0.031363 -0.051054   
766  0.040267  0.062169  0.057532  0.058796  ... -0.040901  0.067883   
767 -0.038154  0.046283  0.048734  0.049263  ...  0.018404  0.030697   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12  -0.270030  0.151400  0.107700  0.114990 -0.138540 -0.247210 -0.088777   
14  -0.295330  0.153960  0.114980  0.117700 -0.107390 -0.212550 -0.094376   
16  -0.205850  0.197110  0.165930  0.140700 -0.048163 -0.160220 -0.098555   
18  -0.114820  0.163960  0.141680  0.127640 -0.053194 -0.121520 -0.072039   
20  -0.076864  0.131670  0.127770  0.050722 -0.042034 -0.044921  0.054350   
..        ...       ...       ...       ...       ...       ...       ...   
383  0.048103  0.082586  0.076207  0.066063 -0.115260 -0.092069 -0.047989   
754 -0.043589  0.037315 -0.031861  0.034931  0.033640 -0.056613 -0.051455   
755 -0.044989 -0.033120 -0.038797 -0.051054  0.062066  0.051890  0.026741   
766 -0.045857  0.060618  0.036172  0.067883 -0.067277 -0.083154 -0.082065   
767  0.027218  0.033547  0.027961  0.030697 -0.034024 -0.024326 -0.046260   

        ks238  
12   0.280320  
14   0.283920  
16   0.185980  
18   0.114630  
20   0.066102  
..        ...  
383  0.043908  
754  0.043782  
755  0.045863  
766  0.055028  
767 -0.031593  

[168 rows x 240 columns]

In [38]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn5 = KNeighborsClassifier(n_neighbors=20)
knn5.fit(X_training, y)
y_pred_5 = knn5.predict(X_testing)
print(y_pred_5)
print(accuracy(y_pred_5,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))
#print("Accuracy with k=5", accuracy_score(y_test, y_pred_5)*100)

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
1.0


In [39]:
import numpy as np
all_list2=[]
for i in range(len(all_list)):
    all_list2.append(np.ndarray.tolist(all_list[i]))

print(len(all_list2))

168


In [40]:
#starts with bootstrap sampling
#24,24,24,24,24,48
#6,6,6,6,6,12


import random
def bootstrap(all_list):
    part1=all_list[:24]
    
    part2=all_list[24:48]
    part3=all_list[48:72]
    part4=all_list[72:96]
    part5=all_list[96:120]
    part6=all_list[120:168]

    testing_data=[]
    toremovelst=[]
    testing_data2=[]
    toremovelst2=[]
    testing_data3=[]
    toremovelst3=[]
    testing_data4=[]
    toremovelst4=[]
    testing_data5=[]
    toremovelst5=[]
    testing_data6=[]
    toremovelst6=[]
    #1
    
    
    toremoveindexlst=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst)):
        toremoveindex=toremoveindexlst[i]

        target=part1[toremoveindex]
        toremovelst.append(target)
        testing_data.append(target)
    
        
    for i in range(len(toremovelst)):
        part1.remove(toremovelst[i])
    #2
    toremoveindexlst2=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst2)):
        toremoveindex2=toremoveindexlst2[i]

        target2=part2[toremoveindex2]
        toremovelst2.append(target2)
        testing_data.append(target2)
    
        
    for i in range(len(toremovelst2)):
        part2.remove(toremovelst2[i])
    #3
    toremoveindexlst3=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst3)):
        toremoveindex3=toremoveindexlst3[i]

        target3=part3[toremoveindex3]
        toremovelst3.append(target3)
        testing_data.append(target3)

    for i in range(len(toremovelst3)):
        part3.remove(toremovelst3[i])
    #4
    toremoveindexlst4=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst4)):
        toremoveindex4=toremoveindexlst4[i]

        target4=part4[toremoveindex4]
        toremovelst4.append(target4)
        testing_data.append(target4)
        
    for i in range(len(toremovelst4)):
        part4.remove(toremovelst4[i])
    #5
    toremoveindexlst5=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst5)):
        toremoveindex5=toremoveindexlst5[i]

        target5=part5[toremoveindex5]
        toremovelst5.append(target5)
        testing_data.append(target5)

    for i in range(len(toremovelst5)):
        part5.remove(toremovelst5[i])

    #6
    toremoveindexlst6=random.sample(range(48), 12)
    for i in range(len(toremoveindexlst6)):
        toremoveindex6=toremoveindexlst6[i]

        target6=part6[toremoveindex6]
        toremovelst6.append(target6)
        testing_data.append(target6)
    
        
    for i in range(len(toremovelst6)):
        part6.remove(toremovelst6[i])
    
    
        





        
    
    





    return part1,part2,part3,part4,part5,part6,testing_data



In [41]:
part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)



In [42]:
training_data=part1+part2+part3+part4+part5+part6
print(len(training_data),len(part6))
y6=[]
for i in range(18):
    y6.append('DNA')
for j in range(18):
    y6.append("MT")
for k in range(18):
    y6.append("HSP")
for m in range(18):
    y6.append("PROT")
for n in range(18):
    y6.append("HDAC")
for k in range(36):
    y6.append("DMSO")

126 36


In [43]:
model6 = LinearDiscriminantAnalysis(n_components=4)
model6.fit(training_data,y6)
yhat6=model6.predict(X_testing)

print(yhat6)
print(len(yhat6))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [44]:
def accuracy2(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(6):
        list3.append(list2[0])
    for j in range(6):
        list3.append(list2[1])
    for m in range(6):
        list3.append(list2[2])
    for n in range(6):
        list3.append(list2[3])
    for k in range(6):
        list3.append(list2[4])
    for k in range(12):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [45]:
a1=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


In [46]:
#bootstrap 

In [47]:
#just to predict, then we will know the effects of bootstrap sampling
accuracylst=[]
def bootstrap_predict_accuracy():
    part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)
    training_data=part1+part2+part3+part4+part5+part6


    model6 = LinearDiscriminantAnalysis(n_components=4)
    model6.fit(training_data,y6)
    yhat6=model6.predict(X_testing)
    a=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


    accuracylst.append(a)

for i in range(10):
    bootstrap_predict_accuracy()
ave_accuracy=sum(accuracylst)/len(accuracylst)

    

In [48]:
ave_accuracy

1.0