In [179]:
#a code block that deals with concentration and drug names
#we do not use this block for now.

import pandas as pd
f1 = pd.read_csv('B.csv')
f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('A_ks5.csv')
file = [f1,f2,f3,f5]
train = pd.concat(file,axis=1)
train.to_csv("train.csv", index=0, sep=',')


In [180]:
#do some further processing with "A" because there are some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('A_ks5.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('modified_A.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                


-0.294442


In [181]:
#test file A
import pandas as pd
df_A=pd.read_csv("A_ks5.csv")
df_A.shape
#df_A2=pd.read_csv("A_modified.csv")
#df_A2.shape


(767, 239)

In [182]:
#a block that is used to concate the drug names(drug combinations and related concentration)

import csv
res_list=[]
with open('train.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        data=[]
        data.append(row[0]+'+'+row[1]+"+"+row[2])
        res_list.append(data)

        
        
with open('concatenated.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerows(res_list)

In [183]:
#a block that is used to concate concentration and ks numbers.
import pandas as pd
f1 = pd.read_csv('concatenated.csv')
#f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('modified_A.csv')
file = [f1,f5]
train = pd.concat(file,axis=1)
train.to_csv("train3.csv", index=0, sep=',')

In [184]:
#a block that sets the fields for the drug data
import csv
fields=['drug_name','default']
for i in range(1,239):
    fields.append('ks'+str(i))
rows=[]
with open('train3.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        rows.append(row)

        
        
with open('drug_withfields2.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerow(fields)
    writer.writerows(rows)

In [185]:
#do some further processing with "drug_withfields" because there are still some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('drug_withfields2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('drug_with_fields.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                

-0.294442


In [186]:
df=pd.read_csv('drug_with_fields.csv')
#one type first type. dna
df11=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+2') ]
df13=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+3') ]
df14=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+4') ]
df15=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+5') ]
df16=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+6') ]
df21=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+1') ]
df22=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+2') ]
df23=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+3') ]
df24=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+4') ]
df25=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+5') ]
df26=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+6') ]
df31=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df32=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]
df33=df.loc[(df['drug_name'] =='Etoposide+Etoposide+3') ]
df34=df.loc[(df['drug_name'] =='Etoposide+Etoposide+4') ]
df35=df.loc[(df['drug_name'] =='Etoposide+Etoposide+5') ]
df36=df.loc[(df['drug_name'] =='Etoposide+Etoposide+6') ]
df41=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+1') ]
df42=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+2') ]
df43=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+3') ]
df44=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+4') ]
df45=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+5') ]
df46=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+6') ]
frames = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
dna = pd.concat(frames)
dna


drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.749170 -0.669410 -0.927020   
14    Etoposide+Gemcitabine+2        0 -0.913330 -0.459310 -0.413220   
16    Etoposide+Gemcitabine+3        0 -0.690000  0.299020  0.126810   
18    Etoposide+Gemcitabine+4        0 -0.677500  0.258400  0.152130   
20    Etoposide+Gemcitabine+5        0 -0.060833 -0.167140 -0.198800   
22    Etoposide+Gemcitabine+6        0  0.083015 -0.050783  0.086035   
72    Gemcitabine+Etoposide+1        0 -0.713330 -0.774560 -0.961700   
74    Gemcitabine+Etoposide+2        0 -0.780000 -0.722470 -0.922870   
76    Gemcitabine+Etoposide+3        0 -0.887500 -0.541820 -0.639910   
78    Gemcitabine+Etoposide+4        0  0.107510  0.072807  0.043609   
80    Gemcitabine+Etoposide+5        0  0.100400 -0.083630  0.070463   
82    Gemcitabine+Etoposide+6        0  0.133120 -0.129150 -0.104200   
0       Etoposide+Etoposide+1        0 -0.930830 -0.494530 -0.571140   
2       Etoposide+Etoposide+2        0 -0.925000 -0.400790 -0.318350   
4       Etoposide+Etoposide+3        0 -0.612500  0.097551 -0.134220   
6       Etoposide+Etoposide+4        0  0.097702 -0.056872  0.052675   
8       Etoposide+Etoposide+5        0  0.086735  0.059167  0.080377   
10      Etoposide+Etoposide+6        0  0.101740 -0.058135  0.029234   
84  Gemcitabine+Gemcitabine+1        0 -0.701670 -0.739040 -0.955280   
86  Gemcitabine+Gemcitabine+2        0 -0.665830 -0.725630 -0.960370   
88  Gemcitabine+Gemcitabine+3        0 -0.878330 -0.520350 -0.636090   
90  Gemcitabine+Gemcitabine+4        0 -0.697500  0.215210 -0.091668   
92  Gemcitabine+Gemcitabine+5        0 -0.035000 -0.205680 -0.212370   
94  Gemcitabine+Gemcitabine+6        0  0.106630 -0.058514  0.065298   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.965710 -0.987910 -0.922450 -0.889720 -0.870230  ... -0.337330  0.136410   
14 -0.696840 -0.882330 -0.497390 -0.380400 -0.361150  ...  0.137990  0.272160   
16  0.259950  0.251080  0.149220  0.113770  0.086765  ...  0.551860  0.247790   
18  0.207060  0.146180  0.151390  0.143780  0.126430  ...  0.485480  0.231640   
20  0.093564 -0.258180 -0.186680 -0.175810 -0.170990  ... -0.052231  0.031219   
22  0.068023  0.040280  0.069896  0.098187  0.105420  ... -0.099344  0.039748   
72 -0.986490 -0.994910 -0.968090 -0.944310 -0.923210  ... -0.426610  0.111720   
74 -0.968220 -0.994490 -0.928630 -0.905500 -0.887490  ... -0.352870  0.114080   
76 -0.801420 -0.903400 -0.665160 -0.605320 -0.569120  ...  0.112570  0.292570   
78  0.252200 -0.057031 -0.069156  0.059811  0.107200  ... -0.140180  0.047199   
80  0.188350 -0.059757 -0.030308  0.102570  0.119030  ... -0.155170  0.035656   
82  0.212200 -0.154010 -0.137190 -0.081325 -0.058404  ... -0.159840  0.054025   
0  -0.799580 -0.885820 -0.605470 -0.502670 -0.483900  ... -0.081045  0.191610   
2  -0.538470 -0.806570 -0.364790 -0.259440 -0.227850  ...  0.209710  0.219110   
4   0.145150 -0.135310 -0.134520 -0.132050 -0.126850  ...  0.448330  0.139830   
6   0.092692 -0.035013  0.022697  0.067232  0.089390  ... -0.135830  0.052788   
8   0.131050  0.028573  0.041073  0.097591  0.110090  ... -0.094087  0.048276   
10  0.118040 -0.071427 -0.024583  0.042422  0.067318  ... -0.105350  0.043098   
84 -0.974470 -0.997500 -0.956020 -0.948350 -0.936790  ... -0.373150  0.164250   
86 -0.980240 -0.999170 -0.968460 -0.942910 -0.922550  ... -0.364990  0.141870   
88 -0.784970 -0.893300 -0.631550 -0.585780 -0.570160  ...  0.133530  0.228150   
90  0.313230 -0.075671 -0.090671  0.093784  0.087096  ...  0.495020  0.301100   
92  0.109260 -0.316220 -0.222360 -0.173480 -0.156270  ... -0.108000  0.050404   
94  0.195070 -0.075471 -0.022524  0.091501  0.116910  ... -0.142740  0.041577   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.145360 -0.306520 -0.297390  0.136410  0.235710  0.167310 -0.203070   
14 -0.289340  0.270370  0.205260  0.27216

In [187]:

#one type first type. mt
df11=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+1') ]
df12=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+2') ]
df13=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+3') ]
df14=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+4') ]
df15=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+5') ]
df16=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+6') ]
df21=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+2') ]
df23=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+3') ]
df24=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+4') ]
df25=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+5') ]
df26=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+6') ]
df31=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df32=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]
df33=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+3') ]
df34=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+4') ]
df35=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+5') ]
df36=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+6') ]
df41=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+1') ]
df42=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+2') ]
df43=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+3') ]
df44=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+4') ]
df45=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+5') ]
df46=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+6') ]
frames2 = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
mt= pd.concat(frames)
mt



drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.749170 -0.669410 -0.927020   
14    Etoposide+Gemcitabine+2        0 -0.913330 -0.459310 -0.413220   
16    Etoposide+Gemcitabine+3        0 -0.690000  0.299020  0.126810   
18    Etoposide+Gemcitabine+4        0 -0.677500  0.258400  0.152130   
20    Etoposide+Gemcitabine+5        0 -0.060833 -0.167140 -0.198800   
22    Etoposide+Gemcitabine+6        0  0.083015 -0.050783  0.086035   
72    Gemcitabine+Etoposide+1        0 -0.713330 -0.774560 -0.961700   
74    Gemcitabine+Etoposide+2        0 -0.780000 -0.722470 -0.922870   
76    Gemcitabine+Etoposide+3        0 -0.887500 -0.541820 -0.639910   
78    Gemcitabine+Etoposide+4        0  0.107510  0.072807  0.043609   
80    Gemcitabine+Etoposide+5        0  0.100400 -0.083630  0.070463   
82    Gemcitabine+Etoposide+6        0  0.133120 -0.129150 -0.104200   
0       Etoposide+Etoposide+1        0 -0.930830 -0.494530 -0.571140   
2       Etoposide+Etoposide+2        0 -0.925000 -0.400790 -0.318350   
4       Etoposide+Etoposide+3        0 -0.612500  0.097551 -0.134220   
6       Etoposide+Etoposide+4        0  0.097702 -0.056872  0.052675   
8       Etoposide+Etoposide+5        0  0.086735  0.059167  0.080377   
10      Etoposide+Etoposide+6        0  0.101740 -0.058135  0.029234   
84  Gemcitabine+Gemcitabine+1        0 -0.701670 -0.739040 -0.955280   
86  Gemcitabine+Gemcitabine+2        0 -0.665830 -0.725630 -0.960370   
88  Gemcitabine+Gemcitabine+3        0 -0.878330 -0.520350 -0.636090   
90  Gemcitabine+Gemcitabine+4        0 -0.697500  0.215210 -0.091668   
92  Gemcitabine+Gemcitabine+5        0 -0.035000 -0.205680 -0.212370   
94  Gemcitabine+Gemcitabine+6        0  0.106630 -0.058514  0.065298   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.965710 -0.987910 -0.922450 -0.889720 -0.870230  ... -0.337330  0.136410   
14 -0.696840 -0.882330 -0.497390 -0.380400 -0.361150  ...  0.137990  0.272160   
16  0.259950  0.251080  0.149220  0.113770  0.086765  ...  0.551860  0.247790   
18  0.207060  0.146180  0.151390  0.143780  0.126430  ...  0.485480  0.231640   
20  0.093564 -0.258180 -0.186680 -0.175810 -0.170990  ... -0.052231  0.031219   
22  0.068023  0.040280  0.069896  0.098187  0.105420  ... -0.099344  0.039748   
72 -0.986490 -0.994910 -0.968090 -0.944310 -0.923210  ... -0.426610  0.111720   
74 -0.968220 -0.994490 -0.928630 -0.905500 -0.887490  ... -0.352870  0.114080   
76 -0.801420 -0.903400 -0.665160 -0.605320 -0.569120  ...  0.112570  0.292570   
78  0.252200 -0.057031 -0.069156  0.059811  0.107200  ... -0.140180  0.047199   
80  0.188350 -0.059757 -0.030308  0.102570  0.119030  ... -0.155170  0.035656   
82  0.212200 -0.154010 -0.137190 -0.081325 -0.058404  ... -0.159840  0.054025   
0  -0.799580 -0.885820 -0.605470 -0.502670 -0.483900  ... -0.081045  0.191610   
2  -0.538470 -0.806570 -0.364790 -0.259440 -0.227850  ...  0.209710  0.219110   
4   0.145150 -0.135310 -0.134520 -0.132050 -0.126850  ...  0.448330  0.139830   
6   0.092692 -0.035013  0.022697  0.067232  0.089390  ... -0.135830  0.052788   
8   0.131050  0.028573  0.041073  0.097591  0.110090  ... -0.094087  0.048276   
10  0.118040 -0.071427 -0.024583  0.042422  0.067318  ... -0.105350  0.043098   
84 -0.974470 -0.997500 -0.956020 -0.948350 -0.936790  ... -0.373150  0.164250   
86 -0.980240 -0.999170 -0.968460 -0.942910 -0.922550  ... -0.364990  0.141870   
88 -0.784970 -0.893300 -0.631550 -0.585780 -0.570160  ...  0.133530  0.228150   
90  0.313230 -0.075671 -0.090671  0.093784  0.087096  ...  0.495020  0.301100   
92  0.109260 -0.316220 -0.222360 -0.173480 -0.156270  ... -0.108000  0.050404   
94  0.195070 -0.075471 -0.022524  0.091501  0.116910  ... -0.142740  0.041577   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.145360 -0.306520 -0.297390  0.136410  0.235710  0.167310 -0.203070   
14 -0.289340  0.270370  0.205260  0.27216

In [188]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames3=[]
for i in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+AUY922+'+str(i)) ])
for j in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+17AAG+'+str(j)) ])
for k in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+AUY922+'+str(k)) ])
for m in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+17AAG+'+str(m)) ])
HSP= pd.concat(frames3)
HSP


drug_name  default       ks1       ks2       ks3       ks4  \
397   17AAG+AUY922+1        0 -0.687500 -0.755260 -0.976050 -0.989520   
399   17AAG+AUY922+2        0 -0.825000 -0.707500 -0.900000 -0.978330   
401   17AAG+AUY922+3        0 -0.901670 -0.624760 -0.745490 -0.910350   
403   17AAG+AUY922+4        0 -0.212590 -0.045150 -0.105950  0.138100   
405   17AAG+AUY922+5        0  0.041125 -0.062162 -0.045596  0.138780   
407   17AAG+AUY922+6        0  0.072607  0.077800  0.108570  0.095616   
457   AUY922+17AAG+1        0 -0.617500 -0.711270 -0.956650 -0.983560   
459   AUY922+17AAG+2        0 -0.870830 -0.466670 -0.526110 -0.780000   
461   AUY922+17AAG+3        0 -0.687500  0.268900 -0.082731  0.328500   
463   AUY922+17AAG+4        0 -0.685830  0.205200 -0.101370  0.276860   
465   AUY922+17AAG+5        0  0.092078 -0.142130 -0.176780  0.237510   
467   AUY922+17AAG+6        0  0.086807 -0.080649 -0.091017  0.262560   
469  AUY922+AUY922+1        0 -0.500830 -0.824920 -0.988020 -0.997140   
471  AUY922+AUY922+2        0 -0.714170 -0.738300 -0.950710 -0.983230   
473  AUY922+AUY922+3        0 -0.760000 -0.752280 -0.912620 -0.969860   
475  AUY922+AUY922+4        0 -0.781670  0.176640 -0.113040  0.299460   
477  AUY922+AUY922+5        0 -0.062247 -0.260270 -0.332000  0.151170   
479  AUY922+AUY922+6        0  0.094453 -0.056431  0.024914 -0.018491   
385    17AAG+17AAG+1        0 -0.861670 -0.679570 -0.838320 -0.955340   
387    17AAG+17AAG+2        0 -0.898330 -0.425800 -0.486410 -0.687730   
389    17AAG+17AAG+3        0 -0.580000  0.050205 -0.170540 -0.059912   
391    17AAG+17AAG+4        0  0.123770 -0.074506 -0.067362  0.109620   
393    17AAG+17AAG+5        0  0.103830 -0.070053 -0.093880  0.073408   
395    17AAG+17AAG+6        0  0.116620 -0.076437 -0.046308  0.120910   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
397 -0.997500 -0.976050 -0.971550 -0.954580  ... -0.430090 -0.045055   
399 -0.987500 -0.909170 -0.884170 -0.863330  ... -0.365830  0.105000   
401 -0.942800 -0.778430 -0.707540 -0.668760  ... -0.311990  0.122720   
403 -0.125270 -0.140810 -0.099238 -0.083805  ...  0.127000  0.055021   
405 -0.093122 -0.079141 -0.038862  0.030323  ... -0.053139  0.045375   
407  0.047839  0.069354  0.108910  0.125410  ... -0.061909  0.039102   
457 -0.995900 -0.964020 -0.941880 -0.926140  ... -0.332990  0.094657   
459 -0.910560 -0.551390 -0.504720 -0.485000  ...  0.140000  0.229440   
461 -0.089468 -0.081637 -0.072430 -0.067992  ...  0.535290  0.248180   
463 -0.130360 -0.100220 -0.079942 -0.077863  ...  0.447060  0.263450   
465 -0.268390 -0.245390 -0.150500 -0.114020  ... -0.139190  0.034783   
467 -0.173160 -0.164350 -0.066861 -0.042175  ... -0.118740 -0.036071   
469 -0.998800 -0.989220 -0.983600 -0.980840  ... -0.475160  0.040314   
471 -0.994480 -0.954260 -0.925510 -0.897170  ... -0.349280  0.129500   
473 -0.992310 -0.912720 -0.897030 -0.880270  ... -0.344360  0.127250   
475 -0.145990 -0.121720 -0.105750 -0.090565  ...  0.538220  0.301600   
477 -0.456140 -0.360700 -0.291960 -0.262450  ... -0.057064  0.068009   
479 -0.062686 -0.034803  0.036248  0.052053  ... -0.113150  0.055665   
385 -0.958010 -0.838230 -0.805820 -0.790750  ... -0.198660  0.195630   
387 -0.852260 -0.499650 -0.444240 -0.426290  ...  0.229190  0.225830   
389 -0.170250 -0.171580 -0.168360 -0.160250  ...  0.392620  0.205000   
391 -0.096618 -0.121330 -0.059557 -0.035920  ... -0.103270 -0.029803   
393 -0.102620 -0.139060 -0.090679 -0.056269  ... -0.104840  0.022707   
395 -0.102580 -0.068888 -0.033459  0.025073  ... -0.118240  0.044498   

        ks231     ks232     ks233     ks234    ks235    ks236     ks237  \
397  0.163330 -0.445040 -0.421380 -0.045055  0.36891  0.29652 -0.122430   
399  0.118330 -0.355000 -0.344170  0.105000  0.27750  0.21667 -0.170830   
401 -0.130750 -0.291750 -0.269310  0.122720 -0.24902 -0.29693 -0.254250   
403 -0.071852  0.180470  0.171570  0.055021 -0.14462 -0.16088 -0.077014   
405  0.04

In [189]:
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin

frames4=[]
for i in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+PS341+'+str(i)) ])
for j in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+MG132+'+str(j)) ])
for k in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+MG132+'+str(k)) ])
for m in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+PS341+'+str(m)) ])
PROT= pd.concat(frames4)
PROT

drug_name  default       ks1       ks2       ks3       ks4       ks5  \
541  MG132+PS341+1        0 -0.988330  0.204550  0.490610 -0.466820 -0.147270   
543  MG132+PS341+2        0 -0.629170  0.433960  0.379030  0.161740  0.430830   
545  MG132+PS341+3        0 -0.409170  0.256740  0.175900  0.226020  0.120820   
547  MG132+PS341+4        0 -0.342500  0.250800  0.244160  0.164610  0.140700   
549  MG132+PS341+5        0 -0.046438  0.081620  0.094815  0.102460 -0.028970   
551  MG132+PS341+6        0  0.129920 -0.068248  0.061794  0.063990 -0.032913   
601  PS341+MG132+1        0 -0.317470 -0.844290 -0.999150 -0.999170 -1.000000   
603  PS341+MG132+2        0 -0.956670 -0.142860  0.326790 -0.229400 -0.215710   
605  PS341+MG132+3        0 -0.698740  0.362200  0.361490  0.115390  0.290760   
607  PS341+MG132+4        0 -0.475000  0.344120  0.364830  0.139640  0.368740   
609  PS341+MG132+5        0 -0.127980 -0.074591 -0.059814 -0.024528 -0.058333   
611  PS341+MG132+6        0  0.139410 -0.097196 -0.043439 -0.038001 -0.077974   
529  MG132+MG132+1        0 -0.320000 -0.846870 -0.998290 -0.999170 -1.000000   
531  MG132+MG132+2        0 -0.639170  0.214840  0.288780 -0.060869  0.027829   
533  MG132+MG132+3        0 -0.448330  0.234150  0.193620  0.091442  0.095146   
535  MG132+MG132+4        0 -0.376460  0.175200  0.200250  0.120270  0.131310   
537  MG132+MG132+5        0 -0.056717  0.077550  0.090337  0.114540 -0.055216   
539  MG132+MG132+6        0  0.124210 -0.087693 -0.032779  0.036694 -0.111280   
613  PS341+PS341+1        0 -0.250000 -0.864740 -0.997660 -0.999170 -1.000000   
615  PS341+PS341+2        0 -0.861670  0.493330  0.557500  0.075833  0.493330   
617  PS341+PS341+3        0 -0.595000  0.401070  0.498680  0.085083  0.226890   
619  PS341+PS341+4        0 -0.505450  0.379650  0.407830  0.137260  0.373970   
621  PS341+PS341+5        0 -0.140490 -0.044115 -0.053316  0.102880 -0.124030   
623  PS341+PS341+6        0  0.112100  0.059556  0.093113  0.030352  0.102850   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
541  0.485150  0.499770  0.460610  ...  0.378110  0.383940 -0.519700   
543  0.349370  0.359510  0.368470  ...  0.551670  0.129240 -0.055764   
545  0.123790  0.188730  0.214750  ...  0.328920  0.095963 -0.063551   
547  0.211330  0.257470  0.264390  ...  0.294790  0.084982 -0.049263   
549  0.061817  0.100800  0.107850  ...  0.042222 -0.038748  0.036114   
551  0.028012  0.072540  0.082882  ... -0.137470  0.024990  0.023410   
601 -1.000000 -0.999150 -0.997460  ... -0.595790 -0.129110  0.521820   
603  0.292860  0.366550  0.379880  ...  0.170240  0.170000 -0.162380   
605  0.314900  0.362070  0.361380  ...  0.530840  0.059453 -0.103820   
607  0.370740  0.353000  0.337120  ...  0.402240  0.068881 -0.070857   
609 -0.062987 -0.060571  0.064933  ...  0.068106  0.061402 -0.066157   
611 -0.061916 -0.030657  0.043506  ... -0.140550  0.028355  0.047181   
529 -0.998290 -0.998290 -0.995760  ... -0.583500 -0.153390  0.511220   
531  0.248460  0.317930  0.321920  ...  0.226240  0.150610 -0.103570   
533  0.145780  0.211960  0.241340  ...  0.345510  0.097377 -0.097720   
535  0.188470  0.213180  0.212680  ...  0.280020  0.098996 -0.093924   
537  0.055401  0.105040  0.122030  ...  0.048111  0.047893 -0.031469   
539 -0.063507  0.024454  0.045902  ... -0.145300  0.030305  0.043179   
613 -0.999220 -0.996100 -0.991420  ... -0.617160 -0.154220  0.539510   
615  0.554170  0.511670  0.490830  ...  0.609170 -0.055833 -0.243330   
617  0.429980  0.489530  0.517160  ...  0.356520  0.104540 -0.049256   
619  0.397300  0.388490  0.386370  ...  0.442560  0.072424 -0.020291   
621 -0.076084 -0.041468 -0.037740  ...  0.080117  0.033649  0.044650   
623  0.073302  0.080489  0.090841  ... -0.090641  0.036167  0.034556   

        ks232     ks233     ks234     ks235     ks236     ks237     ks238  
541  0.485080  0.486890  0.383940 -0.656890 -0.654770 -0.435230  0.565530  
543  0.623680  0.611810  0.129

In [190]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames5=[]
for i in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+Apicidin+'+str(i)) ])
for j in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+SAHA+'+str(j)) ])
for k in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+Apicidin+'+str(k)) ])
for m in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+SAHA+'+str(m)) ])
HDAC= pd.concat(frames5)
HDAC

drug_name  default       ks1       ks2       ks3       ks4  \
672      SAHA+Apicidin+1        0 -0.819170 -0.719220 -0.865900 -0.940780   
674      SAHA+Apicidin+2        0 -0.639170  0.557510  0.598390  0.115160   
676      SAHA+Apicidin+3        0 -0.079362  0.363130  0.424230  0.152130   
678      SAHA+Apicidin+4        0  0.042066  0.064977  0.082751  0.068676   
680      SAHA+Apicidin+5        0  0.045482 -0.121280 -0.086435  0.040694   
682      SAHA+Apicidin+6        0  0.052281 -0.062670 -0.034032 -0.028311   
289      Apicidin+SAHA+1        0 -0.805000 -0.705380 -0.932300 -0.959650   
291      Apicidin+SAHA+2        0 -0.650830  0.636690  0.697760  0.173100   
293      Apicidin+SAHA+3        0  0.050020  0.323170  0.443300  0.105150   
295      Apicidin+SAHA+4        0  0.141710 -0.040410  0.108520 -0.032015   
297      Apicidin+SAHA+5        0  0.123910 -0.078472  0.076635 -0.035787   
299      Apicidin+SAHA+6        0  0.189250 -0.104780  0.043633  0.021472   
673  Apicidin+Apicidin+1        0 -0.781670 -0.755520 -0.972000 -0.986500   
675  Apicidin+Apicidin+2        0 -0.620000  0.633600  0.663650  0.157110   
677  Apicidin+Apicidin+3        0 -0.102860  0.356880  0.410640  0.138420   
679  Apicidin+Apicidin+4        0  0.089211  0.071938  0.114040  0.053434   
681  Apicidin+Apicidin+5        0  0.051761 -0.091303 -0.026639 -0.031385   
683  Apicidin+Apicidin+6        0  0.139410 -0.108400 -0.086694  0.042368   
288          SAHA+SAHA+1        0 -0.764170 -0.740900 -0.954870 -0.977370   
290          SAHA+SAHA+2        0 -0.650830  0.630790  0.676920  0.167740   
292          SAHA+SAHA+3        0 -0.050000  0.361100  0.448260  0.162890   
294          SAHA+SAHA+4        0  0.083482  0.102670  0.187060  0.068716   
296          SAHA+SAHA+5        0  0.082080 -0.095090  0.045131 -0.038340   
298          SAHA+SAHA+6        0  0.119230 -0.111520 -0.030594 -0.056651   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
672 -0.954210 -0.872760 -0.826870 -0.793480  ... -0.158290  0.122030   
674  0.534800  0.599450  0.601010  0.581840  ...  0.513520  0.170930   
676  0.419280  0.422010  0.406750  0.391410  ...  0.120260  0.042665   
678  0.072660  0.068002  0.085445  0.079475  ... -0.061610 -0.034680   
680 -0.125620 -0.093616 -0.081189 -0.067276  ... -0.097808  0.044751   
682 -0.053935 -0.042351  0.017437  0.023533  ... -0.103150  0.029251   
289 -0.987230 -0.937750 -0.911380 -0.889150  ... -0.203840  0.081258   
291  0.642820  0.703780  0.683010  0.645450  ...  0.581390  0.183440   
293  0.444200  0.449360  0.430900  0.413740  ...  0.041315  0.023062   
295  0.083251  0.105200  0.092807  0.085888  ... -0.155180  0.052958   
297  0.033707  0.062920  0.077586  0.076516  ... -0.157020  0.047651   
299 -0.030832  0.031133  0.049691  0.053917  ... -0.182640  0.031323   
673 -0.997500 -0.961840 -0.939340 -0.921340  ... -0.270560  0.084436   
675  0.637890  0.661120  0.648740  0.621050  ...  0.600990  0.125100   
677  0.405690  0.406500  0.385280  0.371240  ...  0.148430 -0.035986   
679  0.114270  0.110510  0.107040  0.106980  ... -0.102890  0.029339   
681 -0.036877 -0.027991  0.037166  0.039893  ... -0.122020  0.029522   
683 -0.111760 -0.108760 -0.069625 -0.055139  ... -0.153340  0.042060   
288 -0.989740 -0.957440 -0.918400 -0.892630  ... -0.296220  0.132880   
290  0.599980  0.677670  0.658850  0.630060  ...  0.538630  0.154080   
292  0.448480  0.446840  0.442590  0.420530  ...  0.115710  0.047349   
294  0.153600  0.179590  0.182010  0.171780  ... -0.091766  0.034585   
296 -0.036715  0.043464  0.051123  0.056143  ... -0.123530  0.058774   
298 -0.055880 -0.027947  0.038263  0.039357  ... -0.135570  0.036210   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
672 -0.127860 -0.152370 -0.135520  0.122030 -0.378410 -0.368750 -0.294340   
674 -0.087101  0.607680  0.600680  0.170930 -0.555800 -0.530110 -0.154950   
676  0.061202  0.140080  0.148740  0.042665  0.169720  0.

In [191]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames6=[]
for i in range(1,7):
    frames6.append(df.loc[(df['drug_name'] =='DMSO+DMSO+'+str(i)) ])

DMSO= pd.concat(frames6)
DMSO
#len(DMSO)


drug_name  default       ks1       ks2       ks3       ks4       ks5  \
360  DMSO+DMSO+1        0 -0.050000  0.088765  0.045054  0.201330  0.026972   
361  DMSO+DMSO+1        0  0.023127  0.040922  0.049528  0.045583 -0.032832   
372  DMSO+DMSO+1        0  0.078791 -0.021792  0.078186 -0.032950  0.051335   
373  DMSO+DMSO+1        0  0.035676  0.034145  0.071192 -0.045774  0.073008   
744  DMSO+DMSO+1        0 -0.065346  0.120600  0.065723  0.168690  0.065016   
745  DMSO+DMSO+1        0  0.034188  0.105910  0.118920  0.033165  0.071428   
756  DMSO+DMSO+1        0 -0.033766 -0.020477  0.046106 -0.057283 -0.044341   
757  DMSO+DMSO+1        0  0.026336  0.038513  0.056108 -0.044023  0.067181   
362  DMSO+DMSO+2        0 -0.025911  0.026684  0.027831  0.096734 -0.024139   
363  DMSO+DMSO+2        0  0.053535 -0.024524  0.028197  0.047200  0.024892   
374  DMSO+DMSO+2        0  0.036716  0.030891  0.040907 -0.074596  0.027648   
375  DMSO+DMSO+2        0  0.015952 -0.054167 -0.032143 -0.090357 -0.049167   
746  DMSO+DMSO+2        0 -0.042973 -0.025315 -0.043370 -0.045655 -0.043962   
747  DMSO+DMSO+2        0  0.062548  0.056347  0.076880  0.067773  0.044976   
758  DMSO+DMSO+2        0  0.030810 -0.034466 -0.021589  0.019510 -0.033170   
759  DMSO+DMSO+2        0  0.042815 -0.042039 -0.044535 -0.046190 -0.056454   
364  DMSO+DMSO+3        0  0.082548 -0.038465  0.051054  0.029949  0.032434   
365  DMSO+DMSO+3        0 -0.144430 -0.101920 -0.397750  0.295320 -0.449850   
376  DMSO+DMSO+3        0  0.021702  0.028221  0.090171 -0.068765  0.046430   
377  DMSO+DMSO+3        0  0.020272 -0.037954 -0.029839 -0.082009 -0.056146   
748  DMSO+DMSO+3        0 -0.054279  0.028470 -0.031194 -0.022164 -0.020311   
749  DMSO+DMSO+3        0  0.069111  0.015944  0.042643 -0.023433  0.033328   
760  DMSO+DMSO+3        0  0.028384 -0.024146 -0.027435 -0.026338 -0.020557   
761  DMSO+DMSO+3        0 -0.028609  0.022010 -0.046257 -0.088892 -0.023359   
366  DMSO+DMSO+4        0  0.020750 -0.048989  0.065069 -0.028279 -0.063373   
367  DMSO+DMSO+4        0  0.076425  0.018880  0.066227 -0.029380  0.031968   
378  DMSO+DMSO+4        0 -0.032500 -0.041194  0.032750 -0.062640  0.039106   
379  DMSO+DMSO+4        0 -0.036267 -0.047202 -0.053804 -0.076376 -0.075042   
750  DMSO+DMSO+4        0 -0.026483  0.027493 -0.025319  0.032801  0.023422   
751  DMSO+DMSO+4        0  0.056415  0.045805  0.080453  0.032066  0.043492   
762  DMSO+DMSO+4        0 -0.028609  0.033775  0.040972 -0.050117  0.032340   
763  DMSO+DMSO+4        0  0.037693 -0.027580 -0.027702 -0.054280 -0.034034   
368  DMSO+DMSO+5        0  0.045460  0.051983  0.110060 -0.036580  0.083190   
369  DMSO+DMSO+5        0  0.059001 -0.036537  0.073850 -0.061462  0.024383   
380  DMSO+DMSO+5        0 -0.016632 -0.056883 -0.038241 -0.049820 -0.034391   
381  DMSO+DMSO+5        0 -0.051240 -0.049365  0.048352 -0.074154 -0.038442   
752  DMSO+DMSO+5        0 -0.033766 -0.044447 -0.039277 -0.032006 -0.046491   
753  DMSO+DMSO+5        0  0.035950  0.027403  0.038798 -0.049981 -0.019322   
764  DMSO+DMSO+5        0 -0.043862 -0.029911 -0.044284 -0.028284 -0.084616   
765  DMSO+DMSO+5        0  0.033201 -0.050266 -0.026608 -0.081249 -0.063121   
370  DMSO+DMSO+6        0  0.072135  0.055973  0.122970 -0.043977  0.097684   
371  DMSO+DMSO+6        0  0.069733  0.032678  0.099262 -0.048546  0.083506   
382  DMSO+DMSO+6        0 -0.052500 -0.027284 -0.033449 -0.037950 -0.047513   
383  DMSO+DMSO+6        0 -0.054484  0.056548  0.056706  0.053135  0.022540   
754  DMSO+DMSO+6        0 -0.032901  0.023610 -0.024707 -0.038758 -0.030139   
755  DMSO+DMSO+6        0  0.040747 -0.040153  0.050000  0.023503  0.047512   
766  DMSO+DMSO+6        0  0.035169  0.038537  0.037045  0.062430  0.022459   
767  DMSO+DMSO+6        0 -0.069091  0.067601  0.036944  0.123810 -0.030884   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
360 -0.033317  0.053878  0.056809  ...  0.073015 -0.019309  0.0

In [192]:
combi=frames+frames2+frames3+frames4+frames5+frames6
training= pd.concat(combi)
print(training)
print(len(training))



                   drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.749170 -0.669410 -0.927020 -0.965710   
14   Etoposide+Gemcitabine+2        0 -0.913330 -0.459310 -0.413220 -0.696840   
16   Etoposide+Gemcitabine+3        0 -0.690000  0.299020  0.126810  0.259950   
18   Etoposide+Gemcitabine+4        0 -0.677500  0.258400  0.152130  0.207060   
20   Etoposide+Gemcitabine+5        0 -0.060833 -0.167140 -0.198800  0.093564   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.054484  0.056548  0.056706  0.053135   
754              DMSO+DMSO+6        0 -0.032901  0.023610 -0.024707 -0.038758   
755              DMSO+DMSO+6        0  0.040747 -0.040153  0.050000  0.023503   
766              DMSO+DMSO+6        0  0.035169  0.038537  0.037045  0.062430   
767              DMSO+DMSO+6        0 -0.069091  0.067601  0.036944  0.123810   

          ks5       ks6    

In [193]:
#lda model
#just sample
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X_drug=training.iloc[:, 3:240].values

y=[]
for i in range(24):
    y.append('DNA')
for j in range(24):
    y.append('MT')
for k in range(24):
    y.append('HSP')
for m in range(24):
    y.append('PROT')
for n in range(24):
    y.append('HDAC')
for k in range(48):
    y.append('DMSO')
print(len(X_drug[0]))
model = LinearDiscriminantAnalysis(n_components=4)
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
#reduce dimension for the data
X_drug2=model.fit(X_drug,y).transform(X_drug)
X_drug2
print(len(X_drug2[0]))



237
4


In [194]:
print(len(X_drug2))
print(X_drug2[-1])

168
[-11.66517297  -0.03949836   0.176347    -0.76999122]


In [195]:
#wipe out those whose concentration is not valid
def get_centroid(point_lst):
    x_sum=0
    y_sum=0
    z1_sum=0
    z2_sum=0
    z3_sum=0
    z4_sum=0


    for i in range(len(point_lst)):
        x_sum+=point_lst[i][0]
        y_sum+=point_lst[i][1]
        z1_sum+=point_lst[i][2]
        z2_sum+=point_lst[i][3]
        #z3_sum+=point_lst[i][4]
        #z4_sum+=point_lst[i][5]


    x_mean=x_sum/len(point_lst)
    y_mean=y_sum/len(point_lst)
    z1_mean=z1_sum/len(point_lst)
    z2_mean=z2_sum/len(point_lst)
    #z3_mean=z3_sum/len(point_lst)
    #z4_mean=z4_sum/len(point_lst)
    centroid=[]
    centroid.append(x_mean)
    centroid.append(y_mean)
    centroid.append(z1_mean)
    centroid.append(z2_mean)
    #centroid.append(z3_mean)
    #centroid.append(z4_mean)
    #centroid.append(point_lst[0][-1])
    return centroid



In [196]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                 5.458710              -3.010897              -2.844358   
1                 5.674542              -2.580582              -3.685344   
2                 4.980717              -3.047598              -3.191974   
3                 5.546080              -2.786623              -3.114503   
4                 3.832139              -2.785175              -3.578390   
..                     ...                    ...                    ...   
163              -8.612544              -0.316407              -0.071905   
164             -11.079353               1.018951              -0.986696   
165             -11.043056              -0.237225              -1.725754   
166             -10.763662              -1.695279               0.307424   
167             -11.665173              -0.039498               0.176347   

     principal component 4  
0                 6.381750  
1                 6.061704  
2                 6.613889  
3                 6.429688  
4                 5.211350  
..                     ...  
163              -1.686388  
164              -0.745355  
165              -0.827417  
166              -1.846010  
167              -0.769991  

[168 rows x 4 columns]

In [197]:
#predict
#still sample but useful this block 
#model2 = LinearDiscriminantAnalysis(n_components=1)
#model2.fit(X_drug2,y)
#row=X_drug2
#yhat = model2.predict(row)
# summarize prediction
#print('Predicted Class: %s' % yhat)



In [198]:
all_list=[]

for i in range(len(X_drug2)):
    all_list.append(X_drug2[i])
print(len(all_list))
all_list[120:127]

168


[array([-8.77390923,  0.79572352, -0.68825258,  0.80366804]),
 array([-11.0641967 ,  -1.79303831,  -2.20441442,  -0.75132398]),
 array([-1.01431362e+01,  1.12190383e-04, -1.39880711e+00, -1.76689690e-01]),
 array([-10.24719429,   1.86238778,  -1.16688337,  -0.66615587]),
 array([-8.30646705, -0.95749846, -0.88256995,  1.82502237]),
 array([-9.26683667, -2.15171148, -0.45293189, -0.86592221]),
 array([-9.37248081, -1.14688868,  0.26941872, -2.05672627])]

In [199]:
X_training=[]
X_testing=[]
#X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]+all_list[120]
X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]
for i in range(120,168,8):
    X_training+=all_list[i:i+7]

X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
for j in range(120,168,8):
    X_testing.append(all_list[j])
    print(all_list[j])

#X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
#X_testing.append()
print(len(X_training))
print(len(X_testing))
y=[]
for i in range(18):
    y.append('DNA')
for j in range(18):
    y.append("MT")
for k in range(18):
    y.append("HSP")
for m in range(18):
    y.append("PROT")
for n in range(18):
    y.append("HDAC")
for k in range(42):
    y.append("DMSO")


[-8.77390923  0.79572352 -0.68825258  0.80366804]
[-11.28264665  -0.89122094  -0.44425103   1.5779437 ]
[-9.56203128  0.02327983  0.07168416  0.27327523]
[-11.37323109   0.38820901  -0.73977947   0.1621462 ]
[-12.00910466   0.22537951  -0.50990613  -1.57833629]
[-10.80895062  -0.78569403  -1.15821254   1.40879626]
132
36


In [200]:

dmso_lst2=[]
for i in range(48):
    dmso_lst2.append(all_list[i+120])
print(len(dmso_lst2))
cen_dmso=get_centroid(dmso_lst2)
print(cen_dmso)


48
[-10.369477297010029, -0.4387755962716618, -0.5988150269458361, 0.052833811895691314]


In [201]:
#calculating the distance
from math import sqrt
def euclidean_distance(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(len(row1)-1):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [202]:
dist_lst=[]
for i in range(len(dmso_lst2)):
    dist_lst.append(euclidean_distance(dmso_lst2[i],cen_dmso))
dist_lst.sort()
print(len(dist_lst))
max_ave=sum(dist_lst[-5:-1])/len(dist_lst[-5:-1])
max_ave
max_ave*=2
max_ave


48


5.802213527791475

In [203]:
#selecting data
effect=[]
dist_lst2=[]
for i in range(120):
    selection_dist=euclidean_distance(all_list[i],cen_dmso)
    dist_lst2.append(selection_dist)
dist_lst2.sort()
print(dist_lst2[0])

11.44390090210147


In [204]:
model2 = LinearDiscriminantAnalysis(n_components=4)
model2.fit(X_training,y)
yhat2=model2.predict(X_testing)

print(yhat2)
print(len(yhat2))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [205]:
def accuracy(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(int(length/6.0)):
        list3.append(list2[0])
    for j in range(int(length/6.0)):
        list3.append(list2[1])
    for m in range(int(length/6.0)):
        list3.append(list2[2])
    for n in range(int(length/6.0)):
        list3.append(list2[3])
    for k in range(int(length/6.0)):
        list3.append(list2[4])
    for k in range(int(length/6.0)):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [206]:
#test accuracy
'%.2f%%' % ((accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))*100)


'100.00%'

In [207]:
training["drug_name"]
train_drug_name_without_concentration=[]
for each in training['drug_name']:
    train_drug_name_without_concentration.append(each[:-2])
    #print(training["drug_name"][i][0:-1])
    

train_drug_name_without_concentration
train_drug_name_without_concentration2=[]
#dna,mt,hsp,prot,hdac
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('DNA')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('MT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HSP')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('PROT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HDAC')
for i in range(48):
    train_drug_name_without_concentration2.append("DMSO")

train_drug_name_without_concentration2   


['DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'DMSO',
 'DMSO'

In [208]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append('DMSO')
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=train_drug_name_without_concentration2)
#training['drug_name']
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [209]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append("DMSO")
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=training['drug_name'])
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [210]:
# Create a function
def select_n_components(var_ratio, goal_var: float) -> int:
    # Set initial variance explained so far
    total_variance = 0.0
    
    # Set initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for explained_variance in var_ratio:
        
        # Add the explained variance to the total
        total_variance += explained_variance
        
        # Add one to the number of components
        n_components += 1
        
        # If we reach our goal level of explained variance
        if total_variance >= goal_var:
            # End the loop
            break
            
    # Return the number of components
    return n_components

In [211]:
lda = LinearDiscriminantAnalysis(n_components=None)
y5=[]
for i in range(18):
    y5.append('DNA')
for j in range(18):
    y5.append("MT")
for k in range(18):
    y5.append("HSP")
for m in range(18):
    y5.append("PROT")
for n in range(18):
    y5.append("HDAC")
for k in range(42):
    y5.append("DMSO")

X_lda=lda.fit(X_training,y5)


In [212]:
# Create array of explained variance ratios
lda_var_ratios = lda.explained_variance_ratio_
lda_var_ratios

array([0.63711558, 0.14356985, 0.11528802, 0.10402656])

In [213]:
# Run function
print(select_n_components(lda_var_ratios, 0.95))
print(select_n_components(lda_var_ratios, 0.85))
print(select_n_components(lda_var_ratios, 0.75))
print(select_n_components(lda_var_ratios, 0.65))
print(select_n_components(lda_var_ratios, 0.35))


4
3
2
2
1


In [214]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                 5.458710              -3.010897              -2.844358   
1                 5.674542              -2.580582              -3.685344   
2                 4.980717              -3.047598              -3.191974   
3                 5.546080              -2.786623              -3.114503   
4                 3.832139              -2.785175              -3.578390   
..                     ...                    ...                    ...   
163              -8.612544              -0.316407              -0.071905   
164             -11.079353               1.018951              -0.986696   
165             -11.043056              -0.237225              -1.725754   
166             -10.763662              -1.695279               0.307424   
167             -11.665173              -0.039498               0.176347   

     principal component 4  
0                 6.381750  
1                 6.061704  
2                 6.613889  
3                 6.429688  
4                 5.211350  
..                     ...  
163              -1.686388  
164              -0.745355  
165              -0.827417  
166              -1.846010  
167              -0.769991  

[168 rows x 4 columns]

In [215]:
training

drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.749170 -0.669410 -0.927020 -0.965710   
14   Etoposide+Gemcitabine+2        0 -0.913330 -0.459310 -0.413220 -0.696840   
16   Etoposide+Gemcitabine+3        0 -0.690000  0.299020  0.126810  0.259950   
18   Etoposide+Gemcitabine+4        0 -0.677500  0.258400  0.152130  0.207060   
20   Etoposide+Gemcitabine+5        0 -0.060833 -0.167140 -0.198800  0.093564   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.054484  0.056548  0.056706  0.053135   
754              DMSO+DMSO+6        0 -0.032901  0.023610 -0.024707 -0.038758   
755              DMSO+DMSO+6        0  0.040747 -0.040153  0.050000  0.023503   
766              DMSO+DMSO+6        0  0.035169  0.038537  0.037045  0.062430   
767              DMSO+DMSO+6        0 -0.069091  0.067601  0.036944  0.123810   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12  -0.987910 -0.922450 -0.889720 -0.870230  ... -0.337330  0.136410   
14  -0.882330 -0.497390 -0.380400 -0.361150  ...  0.137990  0.272160   
16   0.251080  0.149220  0.113770  0.086765  ...  0.551860  0.247790   
18   0.146180  0.151390  0.143780  0.126430  ...  0.485480  0.231640   
20  -0.258180 -0.186680 -0.175810 -0.170990  ... -0.052231  0.031219   
..        ...       ...       ...       ...  ...       ...       ...   
383  0.022540  0.044246  0.046786  0.045873  ...  0.034921  0.040714   
754 -0.030139 -0.031500 -0.019386  0.029038  ...  0.029591 -0.035263   
755  0.047512  0.050217  0.046320  0.042159  ... -0.037163  0.027777   
766  0.022459  0.042075  0.037348  0.031066  ...  0.024476 -0.017844   
767 -0.030884 -0.025960  0.038131  0.037096  ...  0.060808  0.037045   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12  -0.145360 -0.306520 -0.297390  0.136410  0.235710  0.167310 -0.203070   
14  -0.289340  0.270370  0.205260  0.272160 -0.627590 -0.608650 -0.403970   
16  -0.315200  0.722750  0.682450  0.247790 -0.531130 -0.569710 -0.181620   
18  -0.226070  0.623180  0.595200  0.231640 -0.474370 -0.498440 -0.153010   
20  -0.091645 -0.042901 -0.048864  0.031219 -0.108130 -0.122700 -0.088380   
..        ...       ...       ...       ...       ...       ...       ...   
383 -0.025635  0.053810  0.046548  0.040714  0.031270  0.034286 -0.026349   
754  0.039139  0.038929  0.049717 -0.035263  0.024070  0.033969  0.039007   
755 -0.025349 -0.026051 -0.035638  0.027777  0.032834  0.049933 -0.028290   
766  0.048467  0.027821  0.037879 -0.017844  0.032547  0.040583 -0.021958   
767  0.031439  0.084520  0.080177  0.037045  0.029949  0.052727 -0.040000   

        ks238  
12   0.135950  
14   0.399480  
16   0.395390  
18   0.282530  
20   0.100400  
..        ...  
383 -0.024881  
754 -0.029900  
755 -0.025389  
766 -0.037541  
767 -0.051263  

[168 rows x 240 columns]

In [216]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn5 = KNeighborsClassifier(n_neighbors=20)
knn5.fit(X_training, y)
y_pred_5 = knn5.predict(X_testing)
print(y_pred_5)
print(accuracy(y_pred_5,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))
#print("Accuracy with k=5", accuracy_score(y_test, y_pred_5)*100)

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
1.0


In [217]:
import numpy as np
all_list2=[]
for i in range(len(all_list)):
    all_list2.append(np.ndarray.tolist(all_list[i]))

print(len(all_list2))

168


In [218]:
#starts with bootstrap sampling
#24,24,24,24,24,48
#6,6,6,6,6,12


import random
def bootstrap(all_list):
    part1=all_list[:24]
    
    part2=all_list[24:48]
    part3=all_list[48:72]
    part4=all_list[72:96]
    part5=all_list[96:120]
    part6=all_list[120:168]

    testing_data=[]
    toremovelst=[]
    testing_data2=[]
    toremovelst2=[]
    testing_data3=[]
    toremovelst3=[]
    testing_data4=[]
    toremovelst4=[]
    testing_data5=[]
    toremovelst5=[]
    testing_data6=[]
    toremovelst6=[]
    #1
    
    
    toremoveindexlst=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst)):
        toremoveindex=toremoveindexlst[i]

        target=part1[toremoveindex]
        toremovelst.append(target)
        testing_data.append(target)
    
        
    for i in range(len(toremovelst)):
        part1.remove(toremovelst[i])
    #2
    toremoveindexlst2=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst2)):
        toremoveindex2=toremoveindexlst2[i]

        target2=part2[toremoveindex2]
        toremovelst2.append(target2)
        testing_data.append(target2)
    
        
    for i in range(len(toremovelst2)):
        part2.remove(toremovelst2[i])
    #3
    toremoveindexlst3=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst3)):
        toremoveindex3=toremoveindexlst3[i]

        target3=part3[toremoveindex3]
        toremovelst3.append(target3)
        testing_data.append(target3)

    for i in range(len(toremovelst3)):
        part3.remove(toremovelst3[i])
    #4
    toremoveindexlst4=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst4)):
        toremoveindex4=toremoveindexlst4[i]

        target4=part4[toremoveindex4]
        toremovelst4.append(target4)
        testing_data.append(target4)
        
    for i in range(len(toremovelst4)):
        part4.remove(toremovelst4[i])
    #5
    toremoveindexlst5=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst5)):
        toremoveindex5=toremoveindexlst5[i]

        target5=part5[toremoveindex5]
        toremovelst5.append(target5)
        testing_data.append(target5)

    for i in range(len(toremovelst5)):
        part5.remove(toremovelst5[i])

    #6
    toremoveindexlst6=random.sample(range(48), 12)
    for i in range(len(toremoveindexlst6)):
        toremoveindex6=toremoveindexlst6[i]

        target6=part6[toremoveindex6]
        toremovelst6.append(target6)
        testing_data.append(target6)
    
        
    for i in range(len(toremovelst6)):
        part6.remove(toremovelst6[i])
    
    
        





        
    
    





    return part1,part2,part3,part4,part5,part6,testing_data



In [219]:
part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)



In [226]:
training_data=part1+part2+part3+part4+part5+part6
print(len(training_data),len(part6))
y6=[]
for i in range(18):
    y6.append('DNA')
for j in range(18):
    y6.append("MT")
for k in range(18):
    y6.append("HSP")
for m in range(18):
    y6.append("PROT")
for n in range(18):
    y6.append("HDAC")
for k in range(36):
    y6.append("DMSO")

126 36


In [231]:
model6 = LinearDiscriminantAnalysis(n_components=4)
model6.fit(training_data,y6)
yhat6=model6.predict(X_testing)

print(yhat6)
print(len(yhat6))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [229]:
def accuracy2(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(6):
        list3.append(list2[0])
    for j in range(6):
        list3.append(list2[1])
    for m in range(6):
        list3.append(list2[2])
    for n in range(6):
        list3.append(list2[3])
    for k in range(6):
        list3.append(list2[4])
    for k in range(12):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [230]:
a1=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


1.0

In [ ]:
#bootstrap 

In [234]:
#just to predict, then we will know the effects of bootstrap sampling
accuracylst=[]
def bootstrap_predict_accuracy():
    part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)
    training_data=part1+part2+part3+part4+part5+part6


    model6 = LinearDiscriminantAnalysis(n_components=4)
    model6.fit(training_data,y6)
    yhat6=model6.predict(X_testing)
    a=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


    accuracylst.append(a)

for i in range(10):
    bootstrap_predict_accuracy()
ave_accuracy=sum(accuracylst)/len(accuracylst)

    

In [236]:
ave_accuracy

1.0

In [ ]:
len(part1)
len(testing_data)

6

In [ ]:
print(len(all_list))

168


In [ ]:
alist=[1,2,3,4,5]
alist.remove(3)
print(alist)

[1, 2, 4, 5]
