In [79]:
#a code block that deals with concentration and drug names
#we do not use this block for now.
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin
#cross_class 

import pandas as pd
f1 = pd.read_csv('B_ks2.csv')
f2 = pd.read_csv('C_ks2.csv')
f3=pd.read_csv('D_ks2.csv')
f4=pd.read_csv('E_ks2.csv')
f5=pd.read_csv('A_ks2.csv')
file = [f1,f2,f3,f5]
train = pd.concat(file,axis=1)
train.to_csv("train.csv", index=0, sep=',')


In [80]:
#do some further processing with "A" because there are some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('A_ks2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('modified_A.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                


-0.294442


In [81]:
#test file A
import pandas as pd
df_A=pd.read_csv("A_ks2.csv")
df_A.shape
#df_A2=pd.read_csv("A_modified.csv")
#df_A2.shape


(1535, 239)

In [82]:
#a block that is used to concate the drug names(drug combinations and related concentration)

import csv
res_list=[]
with open('train.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        data=[]
        data.append(row[0]+'+'+row[1]+"+"+row[2])
        res_list.append(data)

        
        
with open('concatenated.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerows(res_list)

In [83]:
#a block that is used to concate concentration and ks numbers.
import pandas as pd
f1 = pd.read_csv('concatenated.csv')
#f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D_ks2.csv')
f4=pd.read_csv('E_ks2.csv')
f5=pd.read_csv('modified_A.csv')
file = [f1,f5]
train = pd.concat(file,axis=1)
train.to_csv("train3.csv", index=0, sep=',')

In [84]:
#a block that sets the fields for the drug data
import csv
fields=['drug_name','default']
for i in range(1,239):
    fields.append('ks'+str(i))
rows=[]
with open('train3.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        rows.append(row)

        
        
with open('drug_withfields2.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerow(fields)
    writer.writerows(rows)

In [85]:
#do some further processing with "drug_withfields" because there are still some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('drug_withfields2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('drug_with_fields.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                

-0.294442


In [89]:
df=pd.read_csv('drug_with_fields.csv')
#one type first type. dna
df11=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+2') ]

df21=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+1') ]
df22=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+2') ]

df31=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df32=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]

df41=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+1') ]
df42=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+2') ]

df51=df.loc[(df['drug_name'] =='Gemcitabine+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='Gemcitabine+DMSO+2') ]



df61=df.loc[(df['drug_name'] =='Etoposide+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Etoposide+DMSO+2') ]



frames = [df11, df12,df21,df22,df31,df32,df41,df42,df51,df52,df61,df62]
dna = pd.concat(frames)
dna


drug_name  default      ks1       ks2       ks3       ks4  \
288   Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.272120   
289   Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.361410   
312   Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.374890   
313   Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.181460   
290   Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.259660   
291   Gemcitabine+Etoposide+2        0 -0.43083  0.296090  0.133160  0.268950   
314   Gemcitabine+Etoposide+2        0 -0.24625  0.185470 -0.092140  0.235070   
315   Gemcitabine+Etoposide+2        0 -0.28042  0.289890  0.133600  0.204580   
1260    Etoposide+Etoposide+1        0 -0.87250  0.430230  0.261280  0.266420   
1261    Etoposide+Etoposide+1        0 -0.64125  0.469260  0.331120  0.251450   
1284    Etoposide+Etoposide+1        0 -0.92292  0.321250  0.202080  0.192920   
1285    Etoposide+Etoposide+1        0 -0.79250  0.478660  0.342870  0.243060   
1262    Etoposide+Etoposide+2        0  0.13685  0.093075  0.069296 -0.054434   
1263    Etoposide+Etoposide+2        0 -0.55375 -0.157010 -0.165160  0.073749   
1286    Etoposide+Etoposide+2        0  0.19224 -0.136410 -0.160640 -0.098558   
1287    Etoposide+Etoposide+2        0 -0.30625  0.283270  0.301550 -0.081369   
60         Gemcitabine+DMSO+1        0 -0.43506  0.238280  0.086834  0.189750   
61         Gemcitabine+DMSO+1        0 -0.28375 -0.075667 -0.250820  0.200940   
84         Gemcitabine+DMSO+1        0 -0.19125  0.073316 -0.200130  0.156070   
85         Gemcitabine+DMSO+1        0 -0.32292 -0.339030 -0.549870  0.162410   
62         Gemcitabine+DMSO+2        0 -0.39208 -0.058333 -0.224310  0.166300   
63         Gemcitabine+DMSO+2        0 -0.15833 -0.191540 -0.391550  0.151590   
86         Gemcitabine+DMSO+2        0 -0.32967 -0.383580 -0.566420 -0.096000   
87         Gemcitabine+DMSO+2        0 -0.38042 -0.284750 -0.471880  0.068732   
1296         Etoposide+DMSO+1        0 -0.86542  0.368750  0.297920  0.134580   
1297         Etoposide+DMSO+1        0 -0.88583 -0.216250 -0.141250  0.271670   
1320         Etoposide+DMSO+1        0 -0.92000  0.152130 -0.222040  0.260790   
1321         Etoposide+DMSO+1        0 -0.92458 -0.308580 -0.408860 -0.124850   
1298         Etoposide+DMSO+2        0  0.16973  0.197440  0.212300  0.076551   
1299         Etoposide+DMSO+2        0  0.13454 -0.057376 -0.085138  0.037170   
1322         Etoposide+DMSO+2        0  0.18417 -0.078435 -0.092622 -0.056961   
1323         Etoposide+DMSO+2        0  0.11348  0.087708  0.108820 -0.024613   

           ks5       ks6       ks7       ks8  ...     ks229     ks230  \
288  -0.405750 -0.503060 -0.456620 -0.454380  ...  0.309020  0.098262   
289  -0.148340 -0.246130 -0.205880 -0.194610  ...  0.314070  0.058262   
312  -0.284660 -0.363750 -0.341210 -0.338950  ...  0.299810  0.085338   
313  -0.408660 -0.504910 -0.482440 -0.487010  ...  0.282460  0.126550   
290  -0.177040 -0.263640 -0.233270 -0.225690  ...  0.253050  0.160250   
291   0.241030 -0.068173  0.137450  0.165820  ...  0.319190  0.132600   
314   0.144350 -0.110970 -0.089130 -0.081101  ...  0.265940  0.086148   
315   0.206040  0.105150  0.125610  0.147320  ...  0.276900  0.066092   
1260  0.266220  0.239780  0.233630  0.220140  ...  0.637980  0.104290   
1261  0.549360  0.363800  0.289990  0.292180  ...  0.656250 -0.037638   
1284  0.430830  0.194580  0.176250  0.173750  ...  0.570420  0.165830   
1285  0.491010  0.361770  0.306620  0.321320  ...  0.616350  0.060051   
1262  0.164140  0.081740  0.044532 -0.048380  ...  0.084730 -0.028454   
1263 -0.144340 -0.155850 -0.169430 -0.158590  ...  0.260930  0.114340   
1286  0.115670 -0.129650 -0.176250 -0.185990  ...  0.073462 -0.063077   
1287  0.322800  0.319580  0.275480  0.276900  ...  0.209350  0.027083   
60    0.263890 -0.093564 -0.085325  0.081236  ...  0.274400  0.151520   
61   -0.132450 -0.258640 -0.2550

In [90]:

#one type first type. mt
df11=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+1') ]
df12=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+2') ]

df21=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+2') ]

df31=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df32=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]

df41=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+1') ]
df42=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+2') ]

df51=df.loc[(df['drug_name'] =='Paclitaxel+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='Paclitaxel+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='Vinblastine+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Vinblastine+DMSO+2') ]



frames2 = [df11, df12,df21,df22,df31,df32,df41,df42,df51,df52,df61,df62]
mt= pd.concat(frames2)
mt
#print(len(dna),len(mt))



drug_name  default      ks1       ks2       ks3      ks4  \
588   Paclitaxel+Vinblastine+1        0 -0.27500 -0.258880 -0.086688 -0.13499   
589   Paclitaxel+Vinblastine+1        0 -0.20375 -0.267970 -0.136310 -0.13175   
612   Paclitaxel+Vinblastine+1        0 -0.49583 -0.346390 -0.183470 -0.19861   
613   Paclitaxel+Vinblastine+1        0 -0.53167 -0.304310 -0.166310 -0.16731   
590   Paclitaxel+Vinblastine+2        0 -0.27583 -0.142300 -0.156530  0.14773   
591   Paclitaxel+Vinblastine+2        0 -0.32125 -0.265340 -0.346260 -0.12321   
614   Paclitaxel+Vinblastine+2        0 -0.24792 -0.239510 -0.275520 -0.11819   
615   Paclitaxel+Vinblastine+2        0 -0.23958 -0.230550 -0.257150 -0.13883   
1164   Paclitaxel+Paclitaxel+1        0 -0.75917 -0.581090 -0.394530 -0.39493   
1165   Paclitaxel+Paclitaxel+1        0 -0.76292 -0.463100 -0.236850 -0.27625   
1188   Paclitaxel+Paclitaxel+1        0 -0.89875 -0.495110 -0.249690 -0.29585   
1189   Paclitaxel+Paclitaxel+1        0 -0.65500 -0.345930 -0.212800 -0.15639   
1166   Paclitaxel+Paclitaxel+2        0 -0.76292 -0.298510 -0.153210 -0.25071   
1167   Paclitaxel+Paclitaxel+2        0 -0.67458 -0.252440 -0.093939 -0.18939   
1190   Paclitaxel+Paclitaxel+2        0 -0.47708 -0.221080 -0.291030  0.15201   
1191   Paclitaxel+Paclitaxel+2        0 -0.81625 -0.149960  0.050048 -0.17892   
816          Paclitaxel+DMSO+1        0 -0.48667 -0.319640 -0.132950 -0.30168   
817          Paclitaxel+DMSO+1        0 -0.68292 -0.354630 -0.111990 -0.34956   
840          Paclitaxel+DMSO+1        0 -0.72458 -0.424650 -0.201600 -0.31538   
841          Paclitaxel+DMSO+1        0 -0.62792 -0.350440 -0.162220 -0.33031   
818          Paclitaxel+DMSO+2        0 -0.65125 -0.220030 -0.153250 -0.20715   
819          Paclitaxel+DMSO+2        0 -0.65042 -0.115350 -0.136910 -0.14007   
842          Paclitaxel+DMSO+2        0 -0.76542 -0.165950 -0.178110 -0.13727   
843          Paclitaxel+DMSO+2        0 -0.67625 -0.196890 -0.092061 -0.18154   
972         Vinblastine+DMSO+1        0 -0.53500 -0.178750 -0.195340  0.10686   
973         Vinblastine+DMSO+1        0 -0.57167 -0.135670 -0.106230 -0.12021   
996         Vinblastine+DMSO+1        0 -0.49500 -0.259960 -0.192130 -0.18467   
997         Vinblastine+DMSO+1        0 -0.46792 -0.194520 -0.163120 -0.09825   
974         Vinblastine+DMSO+2        0 -0.15458 -0.239900 -0.369590  0.28835   
975         Vinblastine+DMSO+2        0 -0.15042 -0.307400 -0.466850  0.33771   
998         Vinblastine+DMSO+2        0 -0.39000 -0.050435 -0.080462  0.22177   
999         Vinblastine+DMSO+2        0  0.10907 -0.045425 -0.104990  0.13264   

           ks5      ks6       ks7       ks8  ...     ks229     ks230  \
588  -0.609590 -0.31824 -0.040134  0.170860  ... -0.491700 -0.354070   
589  -0.602510 -0.36357 -0.084163  0.123060  ... -0.458200 -0.295470   
612  -0.716530 -0.41583 -0.111670  0.095139  ... -0.412780 -0.322500   
613  -0.674520 -0.40416 -0.091777  0.114900  ... -0.526330 -0.393490   
590  -0.404610 -0.37457 -0.115130  0.106660  ... -0.293980 -0.201980   
591  -0.615680 -0.52210 -0.293780 -0.173460  ... -0.246290 -0.166910   
614  -0.567600 -0.47661 -0.219540 -0.087308  ... -0.348340 -0.152310   
615  -0.567190 -0.48083 -0.221390 -0.066476  ... -0.318830 -0.228960   
1164 -0.802460 -0.53512 -0.317220 -0.180090  ... -0.230990 -0.235670   
1165 -0.668040 -0.41399 -0.172620 -0.127620  ...  0.268810  0.125770   
1188 -0.708040 -0.41210 -0.198210 -0.131110  ...  0.398730  0.153210   
1189 -0.626970 -0.44532 -0.148150  0.059829  ...  0.098538 -0.123220   
1166 -0.677140 -0.38381 -0.104760  0.212800  ... -0.334700 -0.197260   
1167 -0.624690 -0.35943 -0.035102  0.220040  ... -0.229970 -0.198070   
1190 -0.518330 -0.46538 -0.223550 -0.129410  ... -0.126900 -0.126990   
1191 -0.565120 -0.30623  0.096483  0.253520  ... -0.087025 -0.203490   
816  -0.791950 -0.47082 -0.101560  0.238770  ... -0.550130 -0.325980   
817  -0.767830 -0.45376 -0.075402  0.225410  ... -0

In [91]:
1536-192*3
#960
#8*3=24 
#8+6+4+2=20 20*2=40
#select 2 out of 10
#45-5=40
960//40


24

In [92]:

frames3=[]
for i in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+AUY922+'+str(i)) ])
for j in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+17AAG+'+str(j)) ])
for k in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+AUY922+'+str(k)) ])
for m in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+17AAG+'+str(m)) ])

df51=df.loc[(df['drug_name'] =='17AAG+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='17AAG+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='AUY922+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='AUY922+DMSO+2') ]
another_lst=[df51,df52,df61,df62]
frames3=frames3+another_lst
HSP= pd.concat(frames3)
HSP


drug_name  default      ks1      ks2      ks3       ks4      ks5  \
432    17AAG+AUY922+1        0  0.12512 -0.46275 -0.35777 -0.228330 -0.72383   
433    17AAG+AUY922+1        0 -0.14583 -0.36235 -0.28347 -0.148500 -0.56642   
456    17AAG+AUY922+1        0 -0.13625 -0.35090 -0.28563 -0.133080 -0.57341   
457    17AAG+AUY922+1        0 -0.20167 -0.42543 -0.35686 -0.223910 -0.70629   
434    17AAG+AUY922+2        0 -0.30042 -0.29033 -0.26982 -0.130900 -0.49008   
435    17AAG+AUY922+2        0 -0.17417 -0.30279 -0.28715 -0.119090 -0.49773   
458    17AAG+AUY922+2        0 -0.24708 -0.45449 -0.35224 -0.217140 -0.72476   
459    17AAG+AUY922+2        0 -0.14708 -0.41732 -0.35095 -0.188140 -0.62754   
1356  AUY922+AUY922+1        0 -0.84708 -0.33663 -0.34076 -0.133110 -0.55045   
1357  AUY922+AUY922+1        0 -0.69042 -0.42670 -0.47650 -0.188580 -0.74933   
1380  AUY922+AUY922+1        0 -0.84000 -0.22256 -0.24263 -0.081178 -0.44293   
1381  AUY922+AUY922+1        0 -0.95208 -0.24786  0.14181 -0.174970 -0.21879   
1358  AUY922+AUY922+2        0 -0.69500 -0.27855 -0.28250 -0.163270 -0.53495   
1359  AUY922+AUY922+2        0 -0.59708 -0.42794 -0.43216 -0.181830 -0.69676   
1382  AUY922+AUY922+2        0 -0.82542 -0.42339 -0.41547 -0.250000 -0.71629   
1383  AUY922+AUY922+2        0 -0.91167 -0.15316 -0.16318 -0.079468 -0.45368   
480      17AAG+DMSO+1        0 -0.14625 -0.30794 -0.22791 -0.182310 -0.59108   
481      17AAG+DMSO+1        0 -0.25375 -0.44188 -0.37461 -0.187470 -0.63871   
504      17AAG+DMSO+1        0 -0.19000 -0.48273 -0.41934 -0.203270 -0.72075   
505      17AAG+DMSO+1        0  0.13105 -0.37524 -0.27833 -0.153200 -0.63105   
482      17AAG+DMSO+2        0 -0.16083 -0.24619 -0.21730 -0.088039 -0.47427   
483      17AAG+DMSO+2        0 -0.22125 -0.38109 -0.32378 -0.231010 -0.66516   
506      17AAG+DMSO+2        0 -0.26667 -0.24889 -0.21335 -0.142850 -0.49517   
507      17AAG+DMSO+2        0 -0.13292 -0.44319 -0.31731 -0.220220 -0.73763   
1440    AUY922+DMSO+1        0 -0.51542 -0.44488 -0.46637 -0.239470 -0.76751   
1441    AUY922+DMSO+1        0 -0.33667 -0.44346 -0.48285 -0.266440 -0.79378   
1464    AUY922+DMSO+1        0 -0.85458 -0.47946 -0.45686 -0.234560 -0.77358   
1465    AUY922+DMSO+1        0 -0.85875 -0.21683 -0.29485  0.135770 -0.47052   
1442    AUY922+DMSO+2        0 -0.45083 -0.33226 -0.36054 -0.159620 -0.63379   
1443    AUY922+DMSO+2        0 -0.36042 -0.31285 -0.35152 -0.142930 -0.59856   
1466    AUY922+DMSO+2        0 -0.69042 -0.31179 -0.32003 -0.167240 -0.56429   
1467    AUY922+DMSO+2        0 -0.71708 -0.33458 -0.38875 -0.160830 -0.67000   

          ks6      ks7      ks8  ...     ks229     ks230     ks231    ks232  \
432  -0.53077 -0.29647 -0.25058  ... -0.196410 -0.107040  0.166990 -0.24339   
433  -0.47063 -0.24710 -0.18895  ... -0.207880 -0.148320  0.149010 -0.28328   
456  -0.44494 -0.25381 -0.21069  ... -0.178750 -0.107690  0.137840 -0.23651   
457  -0.48697 -0.31005 -0.28401  ... -0.099377 -0.133100  0.141100 -0.19154   
434  -0.38280 -0.24551 -0.19899  ... -0.112720 -0.077571  0.054277 -0.16137   
435  -0.42034 -0.24592 -0.18161  ... -0.128840 -0.088680  0.094486 -0.20953   
458  -0.50393 -0.30702 -0.25454  ... -0.167390 -0.135430  0.174850 -0.23421   
459  -0.49221 -0.30424 -0.25095  ... -0.094999 -0.069764  0.095069 -0.14731   
1356 -0.41231 -0.31322 -0.29606  ...  0.103860  0.125720 -0.129170  0.18193   
1357 -0.54492 -0.45168 -0.41736  ...  0.202750  0.121040 -0.159010  0.27716   
1380 -0.31846 -0.23879 -0.20859  ...  0.424310  0.160000 -0.453330  0.50359   
1381 -0.14618  0.12181  0.20578  ...  0.250160  0.356820 -0.373120  0.37339   
1358 -0.41002 -0.25253 -0.21798  ...  0.187040  0.099155 -0.240810  0.22788   
1359 -0.53566 -0.38952 -0.35700  ...  0.196980 -0.085123 -0.129590  0.24408   
1382 -0.47630 -0.40116 -0.38000  ...  0.194260  0.135510 -0.170280  0.29304   
1383 -0.33309 -0.15144  0.25874  ...  0.415170  0.314760 -0.553200  0.56149   
480  -0.41540 -0.20273 -0.16

In [93]:
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin

frames4=[]
for i in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='MG132+PS341+'+str(i)) ])
for j in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='PS341+MG132+'+str(j)) ])
for k in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='MG132+MG132+'+str(k)) ])
for m in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='PS341+PS341+'+str(m)) ])
df51=df.loc[(df['drug_name'] =='MG132+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='MG132+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='PS341+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='PS341+DMSO+2') ]
another_lst=[df51,df52,df61,df62]
frames4=frames4+another_lst
PROT= pd.concat(frames4)
PROT

drug_name  default      ks1      ks2      ks3      ks4      ks5  \
396   PS341+MG132+1        0 -0.57083 -0.65243 -0.68537 -0.58167 -0.93353   
397   PS341+MG132+1        0 -0.37625 -0.56318 -0.67811 -0.41361 -0.90242   
420   PS341+MG132+1        0 -0.52917 -0.65365 -0.69407 -0.60150 -0.94298   
421   PS341+MG132+1        0 -0.41667 -0.61814 -0.65463 -0.47647 -0.92267   
398   PS341+MG132+2        0 -0.58542 -0.51228 -0.50626 -0.37930 -0.83408   
399   PS341+MG132+2        0 -0.67458 -0.61303 -0.49983 -0.48690 -0.91470   
422   PS341+MG132+2        0 -0.53917 -0.50482 -0.53827 -0.47248 -0.90456   
423   PS341+MG132+2        0 -0.42417 -0.57130 -0.52389 -0.45215 -0.91534   
1308  MG132+MG132+1        0 -0.84458 -0.60884 -0.68654 -0.42920 -0.88794   
1309  MG132+MG132+1        0 -0.47292 -0.62086 -0.69725 -0.45806 -0.91361   
1332  MG132+MG132+1        0 -0.90542 -0.70768 -0.73528 -0.62794 -0.94200   
1333  MG132+MG132+1        0 -0.78500 -0.61185 -0.69503 -0.47560 -0.91222   
1310  MG132+MG132+2        0 -0.75000 -0.47825 -0.51677 -0.33117 -0.79784   
1311  MG132+MG132+2        0 -0.88792 -0.62346 -0.58088 -0.47403 -0.90611   
1334  MG132+MG132+2        0 -0.74250 -0.63011 -0.63920 -0.43407 -0.89362   
1335  MG132+MG132+2        0 -0.86792 -0.55105 -0.64143 -0.49059 -0.88123   
1392   MG132+DMSO+1        0 -0.72625 -0.67204 -0.73244 -0.54572 -0.92628   
1393   MG132+DMSO+1        0 -0.75917 -0.57608 -0.61486 -0.44152 -0.87070   
1416   MG132+DMSO+1        0 -0.89167 -0.57853 -0.67535 -0.39119 -0.82000   
1417   MG132+DMSO+1        0 -0.92458 -0.64048 -0.75300 -0.76253 -0.98208   
1394   MG132+DMSO+2        0 -0.55792 -0.42314 -0.42486 -0.18923 -0.72776   
1395   MG132+DMSO+2        0 -0.35875 -0.36896 -0.37138 -0.15965 -0.63534   
1418   MG132+DMSO+2        0 -0.78917 -0.41867 -0.44089 -0.22199 -0.71321   
1419   MG132+DMSO+2        0 -0.85042 -0.45605 -0.46367 -0.14458 -0.67356   
492    PS341+DMSO+1        0 -0.34250 -0.58296 -0.57761 -0.45306 -0.91576   
493    PS341+DMSO+1        0 -0.28292 -0.61297 -0.53655 -0.46007 -0.90849   
516    PS341+DMSO+1        0 -0.38042 -0.54972 -0.55672 -0.45425 -0.89565   
517    PS341+DMSO+1        0 -0.23172 -0.48411 -0.50299 -0.39327 -0.83802   
494    PS341+DMSO+2        0 -0.29500 -0.59352 -0.57258 -0.46462 -0.90974   
495    PS341+DMSO+2        0 -0.37208 -0.52970 -0.41591 -0.38692 -0.88047   
518    PS341+DMSO+2        0 -0.21792 -0.47768 -0.41633 -0.34686 -0.83277   
519    PS341+DMSO+2        0 -0.25250 -0.58686 -0.55543 -0.45509 -0.91309   

          ks6      ks7      ks8  ...    ks229     ks230     ks231    ks232  \
396  -0.73263 -0.63684 -0.60739  ... -0.25803  0.055219 -0.452680 -0.22772   
397  -0.71855 -0.63371 -0.60988  ... -0.52192 -0.080365 -0.252330 -0.48349   
420  -0.72470 -0.64522 -0.60870  ... -0.61905 -0.129820  0.092136 -0.61050   
421  -0.71600 -0.59480 -0.55225  ... -0.59904 -0.089020 -0.080417 -0.57804   
398  -0.60931 -0.46338 -0.41122  ... -0.30921  0.145150 -0.441540 -0.22485   
399  -0.66218 -0.45717 -0.44547  ... -0.59956 -0.109160  0.156280 -0.56316   
422  -0.65721 -0.48219 -0.45505  ... -0.67721 -0.245250  0.496100 -0.71539   
423  -0.64535 -0.47736 -0.43619  ... -0.65825 -0.132850  0.230810 -0.65668   
1308 -0.75922 -0.65186 -0.58035  ...  0.30923  0.238210  0.073787  0.42528   
1309 -0.73821 -0.65962 -0.61879  ...  0.30090  0.137700 -0.490720  0.38185   
1332 -0.75988 -0.67819 -0.63054  ...  0.20958  0.307880 -0.154520  0.35181   
1333 -0.72843 -0.64201 -0.60089  ...  0.27042  0.272320 -0.049026  0.43183   
1310 -0.60294 -0.46838 -0.42775  ...  0.26308  0.209820 -0.109690  0.38948   
1311 -0.69999 -0.53331 -0.50601  ...  0.37247  0.325540 -0.259490  0.60346   
1334 -0.68069 -0.56980 -0.52486  ...  0.31206  0.249770 -0.434050  0.44478   
1335 -0.66750 -0.58715 -0.55996  ...  0.31862  0.267430 -0.120500  0.40792   
1392 -0.76380 -0.69278 -0.65930  ...  0.29319  0.276600 -0.265640  0.42888   
1393 -0.70600 -0.57020 -0.51363  ...  0.29257  0.164690 -0.54242

In [94]:
frames5=[]
for i in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+Apicidin+'+str(i)) ])
for j in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+SAHA+'+str(j)) ])
for k in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+Apicidin+'+str(k)) ])
for m in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+SAHA+'+str(m)) ])

df51=df.loc[(df['drug_name'] =='SAHA+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='SAHA+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='Apicidin+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Apicidin+DMSO+2') ]

another_lst=[df51,df52,df61,df62]
frames5=frames5+another_lst
HDAC= pd.concat(frames5)
HDAC

drug_name  default      ks1       ks2       ks3       ks4  \
912       Apicidin+SAHA+1        0 -0.69042 -0.296930 -0.340530 -0.174020   
913       Apicidin+SAHA+1        0 -0.35208 -0.181170 -0.191110 -0.094006   
936       Apicidin+SAHA+1        0 -0.52667 -0.206170 -0.250750 -0.101510   
937       Apicidin+SAHA+1        0 -0.39542 -0.174210 -0.215880 -0.088104   
914       Apicidin+SAHA+2        0 -0.56542 -0.066917  0.114750 -0.041456   
915       Apicidin+SAHA+2        0 -0.46417 -0.165090 -0.113100 -0.090829   
938       Apicidin+SAHA+2        0 -0.66417 -0.152530 -0.185580 -0.097895   
939       Apicidin+SAHA+2        0 -0.45500 -0.070569  0.151470 -0.074440   
1212  Apicidin+Apicidin+1        0 -0.55792 -0.194790 -0.234200 -0.093386   
1213  Apicidin+Apicidin+1        0 -0.80833 -0.120190 -0.160510 -0.157220   
1236  Apicidin+Apicidin+1        0 -0.58250 -0.143510 -0.156190 -0.074442   
1237  Apicidin+Apicidin+1        0 -0.89583 -0.224400 -0.272890 -0.113330   
1214  Apicidin+Apicidin+2        0 -0.55792 -0.056940  0.111860 -0.122950   
1215  Apicidin+Apicidin+2        0 -0.35333 -0.047568  0.063691 -0.118290   
1238  Apicidin+Apicidin+2        0 -0.66833  0.076006  0.147360 -0.088779   
1239  Apicidin+Apicidin+2        0 -0.69333 -0.081991 -0.085370 -0.111020   
1152          SAHA+DMSO+1        0 -0.56458 -0.224350 -0.219800 -0.124640   
1153          SAHA+DMSO+1        0 -0.48458 -0.182050 -0.165830 -0.118490   
1176          SAHA+DMSO+1        0 -0.87250 -0.285130 -0.310550  0.211160   
1177          SAHA+DMSO+1        0 -0.69667 -0.133160 -0.222900  0.304060   
1154          SAHA+DMSO+2        0 -0.38250 -0.135980 -0.154600  0.124340   
1155          SAHA+DMSO+2        0 -0.48208 -0.140340 -0.123450 -0.090430   
1178          SAHA+DMSO+2        0 -0.57500  0.085833 -0.145000  0.285830   
1179          SAHA+DMSO+2        0 -0.63000  0.226250  0.083826  0.361780   
1104      Apicidin+DMSO+1        0 -0.23958 -0.124910 -0.163290  0.151590   
1105      Apicidin+DMSO+1        0 -0.52375 -0.097286 -0.111520  0.085041   
1128      Apicidin+DMSO+1        0 -0.49208 -0.111460 -0.147710  0.085778   
1129      Apicidin+DMSO+1        0 -0.56125 -0.127980 -0.202720  0.132560   
1106      Apicidin+DMSO+2        0  0.28421 -0.150070 -0.250800  0.295560   
1107      Apicidin+DMSO+2        0 -0.28125 -0.027019 -0.112140  0.206540   
1130      Apicidin+DMSO+2        0 -0.49208  0.080930 -0.047459  0.174400   
1131      Apicidin+DMSO+2        0 -0.48708  0.046407  0.076933 -0.125010   

           ks5       ks6       ks7       ks8  ...     ks229     ks230  \
912  -0.665450 -0.450950 -0.317120 -0.273750  ... -0.567390 -0.135720   
913  -0.547370 -0.272550 -0.160080  0.198330  ... -0.426550 -0.163430   
936  -0.567610 -0.309630 -0.218430 -0.191720  ... -0.430630 -0.157520   
937  -0.527070 -0.323800 -0.203650 -0.182740  ... -0.427930 -0.136910   
914  -0.390910 -0.128700  0.145360  0.228880  ... -0.236700 -0.126050   
915  -0.471170 -0.211960 -0.099283  0.132420  ... -0.335470 -0.103260   
938  -0.535070 -0.217190 -0.165560  0.174230  ... -0.310840 -0.108500   
939  -0.392960 -0.094577  0.179360  0.249200  ... -0.218330 -0.080448   
1212 -0.562520 -0.399930 -0.193930 -0.152750  ... -0.434320 -0.096292   
1213 -0.547080 -0.235050  0.163890  0.270370  ... -0.356440 -0.109720   
1236 -0.533810 -0.243370 -0.134280  0.227060  ... -0.367730 -0.113450   
1237 -0.602480 -0.422150 -0.244200 -0.234280  ... -0.396210 -0.106100   
1214 -0.363080 -0.098344  0.158050  0.217040  ... -0.147820  0.106290   
1215 -0.303940 -0.085672  0.083717  0.138260  ... -0.159380  0.105200   
1238 -0.249170 -0.067184  0.170500  0.196450  ... -0.103690  0.138820   
1239 -0.444260 -0.193750 -0.071667  0.098796  ... -0.098287  0.113330   
1152 -0.595320 -0.336990 -0.198980 -0.193580  ... -0.429520 -0.150500   
1153 -0.559840 -0.290530 -0.145170  0.189360  ... -0.312250 -0.123530   
1176 -0.528040 -0.403810 -0.272220 -0.253050  ... -0.340750 -0.243840   
1177 -0.397460

In [95]:
frames6=[]
for i in range(1,3):
    frames6.append(df.loc[(df['drug_name'] =='DMSO+DMSO+'+str(i)) ])

DMSO= pd.concat(frames6)
DMSO
#len(DMSO)


drug_name  default      ks1       ks2       ks3       ks4       ks5  \
1404  DMSO+DMSO+1        0  0.26423 -0.191470 -0.279800  0.146180 -0.195440   
1405  DMSO+DMSO+1        0 -0.28583  0.170760  0.252280 -0.124140  0.169460   
1428  DMSO+DMSO+1        0 -0.19833  0.160910  0.183850 -0.112090  0.192170   
1429  DMSO+DMSO+1        0 -0.82292  0.648170  0.663170 -0.118250  0.496000   
1452  DMSO+DMSO+1        0 -0.33340 -0.086441 -0.138140  0.111720 -0.121250   
1453  DMSO+DMSO+1        0  0.13743  0.030150  0.046624 -0.066784  0.130540   
1476  DMSO+DMSO+1        0 -0.38417 -0.113400 -0.118880 -0.173330  0.091425   
1477  DMSO+DMSO+1        0 -0.54083 -0.132630 -0.110940 -0.141690 -0.142570   
1488  DMSO+DMSO+1        0  0.25978 -0.419300 -0.519300  0.103630 -0.450930   
1489  DMSO+DMSO+1        0  0.12452 -0.038936 -0.201300  0.252770 -0.117710   
1500  DMSO+DMSO+1        0 -0.30417 -0.256940 -0.259370 -0.094463 -0.216520   
1501  DMSO+DMSO+1        0  0.18471  0.142200  0.145240 -0.039861  0.201490   
1512  DMSO+DMSO+1        0  0.24417  0.102680  0.095019  0.087185  0.114840   
1513  DMSO+DMSO+1        0 -0.11750 -0.100570 -0.195160  0.259640 -0.167770   
1524  DMSO+DMSO+1        0  0.31438 -0.038593 -0.085611 -0.024620  0.100680   
1525  DMSO+DMSO+1        0 -0.49583 -0.182500 -0.248060 -0.099583 -0.121390   
1406  DMSO+DMSO+2        0  0.20772 -0.062188 -0.110120  0.059334  0.046472   
1407  DMSO+DMSO+2        0 -0.10208 -0.142430 -0.131840 -0.036788 -0.059414   
1430  DMSO+DMSO+2        0  0.13163  0.020900  0.077371 -0.088747  0.092360   
1431  DMSO+DMSO+2        0 -0.29708 -0.168800 -0.093349 -0.043894 -0.123350   
1454  DMSO+DMSO+2        0  0.17875  0.032522  0.050735 -0.071262  0.061112   
1455  DMSO+DMSO+2        0  0.34978 -0.125790 -0.130910 -0.075205  0.049501   
1478  DMSO+DMSO+2        0  0.20621 -0.459950 -0.456920 -0.167270 -0.331130   
1479  DMSO+DMSO+2        0 -0.11292 -0.048638 -0.059902 -0.067991  0.036220   
1490  DMSO+DMSO+2        0  0.35535 -0.159130 -0.338850  0.376710 -0.256850   
1491  DMSO+DMSO+2        0  0.36697  0.051450 -0.149660  0.431630 -0.054828   
1502  DMSO+DMSO+2        0 -0.16208  0.098648  0.090666  0.061739  0.079592   
1503  DMSO+DMSO+2        0 -0.10833 -0.218940 -0.218850 -0.153680 -0.075702   
1514  DMSO+DMSO+2        0  0.15515  0.058406 -0.092225  0.322010  0.061095   
1515  DMSO+DMSO+2        0 -0.11708  0.144440  0.143580  0.136450  0.118600   
1526  DMSO+DMSO+2        0 -0.26842  0.166930  0.207920 -0.140920  0.120280   
1527  DMSO+DMSO+2        0 -0.43083  0.314670  0.426560 -0.168680  0.121230   

           ks6       ks7       ks8  ...     ks229     ks230     ks231  \
1404 -0.281620 -0.266000 -0.262080  ... -0.132900 -0.046385  0.194800   
1405  0.256800  0.230590  0.239440  ...  0.156740  0.077679 -0.244190   
1428  0.191130  0.166070  0.169120  ...  0.118590 -0.042965 -0.091366   
1429  0.640670  0.651830  0.651750  ...  0.423830  0.105080  0.148170   
1452 -0.135060 -0.134610 -0.134170  ...  0.065650 -0.032644 -0.043951   
1453  0.059049 -0.057778 -0.064968  ... -0.041036 -0.049338  0.070652   
1476  0.093706 -0.130370 -0.140640  ...  0.145880  0.046776 -0.138550   
1477 -0.073021 -0.115630 -0.119270  ...  0.214040  0.095849 -0.262320   
1488 -0.521280 -0.504490 -0.501650  ... -0.193020 -0.062632  0.179430   
1489 -0.241730 -0.169140 -0.152510  ... -0.094881 -0.052948  0.147010   
1500 -0.235940 -0.264490 -0.265000  ...  0.084362  0.044840 -0.051968   
1501  0.167780  0.120350  0.114670  ... -0.107960 -0.044059  0.150640   
1512  0.071767  0.091039  0.092708  ... -0.069310 -0.029260  0.086638   
1513 -0.235880 -0.175570 -0.163950  ...  0.115940 -0.052720  0.084819   
1524 -0.052829 -0.104650 -0.098313  ... -0.060541 -0.079512  0.166030   
1525 -0.235690 -0.233330 -0.230140  ...  0.131390  0.030694 -0.060833   
1406 -0.089871 -0.116540 -0.116350  ... -0.086647 -0.077675  0.130840   
1407 -0.113490 -0.129910 -0.132300  ... -0.043730 -0.051072  0.074235   
1430  0.07704

In [111]:
#add only 5 please
frames7=[]
for i in range(1,3):
    frames7.append(df.loc[(df['drug_name'] =='Gemcitabine+17AAG+'+str(i)) ])

Gem17AAG= pd.concat(frames7)
Gem17AAG
#len(DMSO)

drug_name  default      ks1      ks2      ks3      ks4      ks5  \
0   Gemcitabine+17AAG+1        0 -0.41708 -0.54193 -0.36498 -0.30632 -0.79929   
1   Gemcitabine+17AAG+1        0 -0.40000 -0.59338 -0.38970 -0.42476 -0.88461   
24  Gemcitabine+17AAG+1        0 -0.37208 -0.41800 -0.27813 -0.23909 -0.70837   
25  Gemcitabine+17AAG+1        0 -0.38042 -0.46610 -0.24839 -0.21649 -0.71542   
2   Gemcitabine+17AAG+2        0 -0.32967 -0.54450 -0.28783 -0.34717 -0.82517   
3   Gemcitabine+17AAG+2        0 -0.38042 -0.47685 -0.28620 -0.30996 -0.78920   
26  Gemcitabine+17AAG+2        0 -0.28125 -0.37121 -0.29124 -0.11267 -0.61088   
27  Gemcitabine+17AAG+2        0 -0.36042 -0.50265 -0.41171 -0.27661 -0.79014   

        ks6      ks7      ks8  ...     ks229     ks230     ks231     ks232  \
0  -0.58251 -0.33667 -0.31465  ...  0.184100  0.060118 -0.171780  0.213250   
1  -0.58410 -0.32108 -0.29055  ...  0.122220  0.090601 -0.188930  0.172610   
24 -0.46769 -0.23290 -0.20497  ...  0.079543 -0.090847 -0.104410 -0.096371   
25 -0.46879 -0.20429 -0.15831  ... -0.081784 -0.101090 -0.094700 -0.154330   
2  -0.53008 -0.24200 -0.20550  ... -0.104500 -0.123170 -0.069417 -0.168330   
3  -0.52138 -0.23138 -0.19159  ...  0.085960 -0.058587 -0.168620 -0.115580   
26 -0.45158 -0.24776 -0.20655  ... -0.049528 -0.119490 -0.128310 -0.112020   
27 -0.55973 -0.32946 -0.27005  ...  0.118730  0.054283 -0.190450  0.149840   

       ks233     ks234    ks235    ks236    ks237    ks238  
0   0.209031  0.060118 -0.50231 -0.40405 -0.20024  0.22675  
1   0.155130  0.090601 -0.55024 -0.41396 -0.22386  0.21220  
24  0.109060 -0.090847 -0.36044 -0.28094 -0.15823  0.14249  
25 -0.144770 -0.101090 -0.37066 -0.29964 -0.21212  0.14785  
2  -0.156250 -0.123170 -0.40633 -0.30492 -0.17233  0.12958  
3   0.122920 -0.058587 -0.39679 -0.32741 -0.18960  0.19951  
26 -0.106190 -0.119490 -0.27414 -0.25645 -0.18639  0.17534  
27  0.136560  0.054283 -0.44198 -0.36032 -0.18587  0.21330  

[8 rows x 240 columns]

In [110]:
#add only 5 please
frames8=[]
for i in range(1,3):
    frames8.append(df.loc[(df['drug_name'] =='Gemcitabine+AUY922+'+str(i)) ])
for i in range(1,3):
    frames8.append(df.loc[(df['drug_name'] =='AUY922+Gemcitabine+'+str(i)) ])

GemAUY922= pd.concat(frames8)
GemAUY922
#len(DMSO)

drug_name  default      ks1      ks2      ks3      ks4  \
12  Gemcitabine+AUY922+1        0 -0.42000 -0.48131 -0.28588 -0.35503   
13  Gemcitabine+AUY922+1        0 -0.45375 -0.48980 -0.29175 -0.32211   
36  Gemcitabine+AUY922+1        0 -0.35042 -0.49994 -0.33369 -0.32106   
37  Gemcitabine+AUY922+1        0 -0.39208 -0.43630 -0.28645 -0.27221   
14  Gemcitabine+AUY922+2        0 -0.53375 -0.50978 -0.36746 -0.38134   
15  Gemcitabine+AUY922+2        0 -0.33250 -0.42179 -0.27222 -0.26381   
38  Gemcitabine+AUY922+2        0 -0.38042 -0.47254 -0.27181 -0.31635   
39  Gemcitabine+AUY922+2        0 -0.37875 -0.35658 -0.20693 -0.23411   

        ks5      ks6      ks7      ks8  ...     ks229     ks230     ks231  \
12 -0.80547 -0.57013 -0.23232 -0.20892  ...  0.090792 -0.118000 -0.137130   
13 -0.76957 -0.53412 -0.23368 -0.19930  ...  0.113440 -0.082257 -0.171070   
36 -0.78480 -0.55949 -0.29107 -0.25230  ...  0.113720  0.102010 -0.125340   
37 -0.68771 -0.48466 -0.22812 -0.19618  ...  0.076342 -0.083012 -0.158260   
14 -0.81416 -0.57207 -0.28038 -0.21275  ...  0.089092 -0.117760 -0.138710   
15 -0.70861 -0.50255 -0.22998 -0.19208  ... -0.055778 -0.118450 -0.065994   
38 -0.75013 -0.50019 -0.23002 -0.16717  ...  0.099679  0.059856 -0.171460   
39 -0.64882 -0.40572 -0.15304  0.16328  ...  0.073379 -0.091407 -0.157370   

      ks232     ks233     ks234    ks235    ks236    ks237    ks238  
12 -0.11571 -0.108760 -0.118000 -0.38747 -0.32066 -0.15840  0.17546  
13  0.17370  0.157110 -0.082257 -0.45532 -0.36244 -0.17700  0.19622  
36  0.18284  0.178080  0.102010 -0.47819 -0.35131 -0.22594  0.14449  
37  0.12400  0.121420 -0.083012 -0.39493 -0.32571 -0.19661  0.19529  
14  0.14212  0.132430 -0.117760 -0.47226 -0.32684 -0.21994  0.17028  
15 -0.14348 -0.126740 -0.118450 -0.30543 -0.23696 -0.13457  0.11448  
38  0.14089  0.125560  0.059856 -0.46297 -0.37461 -0.24422  0.21946  
39  0.10386 -0.093481 -0.091407 -0.38214 -0.31728 -0.19926  0.20081  

[8 rows x 240 columns]

In [108]:
#add only 5 please
frames9=[]
for i in range(1,3):
    frames9.append(df.loc[(df['drug_name'] =='Gemcitabine+Paclitaxel+'+str(i)) ])
#for i in range(1,3):
  #  frames9.append(df.loc[(df['drug_name'] =='+'+str(i)) ])

GemPac= pd.concat(frames9)
GemPac
#len(DMSO)

drug_name  default      ks1      ks2      ks3      ks4  \
96   Gemcitabine+Paclitaxel+1        0 -0.50958 -0.46225 -0.22972 -0.37749   
97   Gemcitabine+Paclitaxel+1        0 -0.39000 -0.39977 -0.13628 -0.31389   
120  Gemcitabine+Paclitaxel+1        0 -0.34917 -0.35129 -0.12724 -0.30858   
121  Gemcitabine+Paclitaxel+1        0 -0.35667 -0.41441 -0.13572 -0.33299   
98   Gemcitabine+Paclitaxel+2        0 -0.47125 -0.25583 -0.38686  0.20568   
99   Gemcitabine+Paclitaxel+2        0 -0.34667 -0.31574 -0.46454 -0.10733   
122  Gemcitabine+Paclitaxel+2        0 -0.28375 -0.29167 -0.47875  0.14360   
123  Gemcitabine+Paclitaxel+2        0 -0.39083 -0.35732 -0.45878 -0.10568   

         ks5      ks6       ks7      ks8  ...     ks229     ks230    ks231  \
96  -0.84934 -0.52407 -0.154030  0.12840  ... -0.461010 -0.296640  0.29262   
97  -0.78437 -0.47072 -0.054414  0.19639  ... -0.478020 -0.273600  0.25124   
120 -0.79370 -0.45658 -0.098986  0.25475  ... -0.462290 -0.264810  0.27627   
121 -0.85071 -0.52343 -0.092388  0.22110  ... -0.464140 -0.269110  0.24749   
98  -0.36702 -0.42840 -0.377830 -0.36011  ...  0.167000 -0.076294  0.23031   
99  -0.44621 -0.49022 -0.450340 -0.42033  ...  0.085428 -0.071938  0.21949   
122 -0.44659 -0.48940 -0.467780 -0.46798  ...  0.137040 -0.049451  0.22435   
123 -0.49232 -0.47798 -0.447260 -0.42375  ... -0.034018 -0.061012  0.27649   

        ks232     ks233     ks234     ks235    ks236    ks237    ks238  
96  -0.576170 -0.574670 -0.296640  0.137410  0.17458 -0.19402 -0.24249  
97  -0.568120 -0.535110 -0.273600  0.102970  0.16286 -0.18024 -0.19751  
120 -0.501420 -0.495670 -0.264810  0.079768  0.14846 -0.21164 -0.20388  
121 -0.562870 -0.542070 -0.269110  0.065418  0.16548 -0.19527 -0.20956  
98   0.130390  0.200830 -0.076294 -0.203510  0.15241 -0.10866 -0.21206  
99   0.094063  0.151270 -0.071938 -0.182730  0.14572 -0.13443 -0.20208  
122  0.154540  0.205980 -0.049451 -0.180150  0.14054 -0.12034 -0.22302  
123 -0.058720  0.099643 -0.061012 -0.134850  0.15628 -0.17307 -0.24485  

[8 rows x 240 columns]

In [109]:
#add only 5 please
frames10=[]
for i in range(1,3):
    frames10.append(df.loc[(df['drug_name'] =='Gemcitabine+Apicidin+'+str(i)) ])
   
#for i in range(1,3):
#    frames8.append(df.loc[(df['drug_name'] =='AUY922+Gemcitabine+'+str(i)) ])
#print(frames10)
GemApi= pd.concat(frames10)
GemApi
#len(DMSO)

drug_name  default      ks1       ks2       ks3       ks4  \
144  Gemcitabine+Apicidin+1        0 -0.37042 -0.354790 -0.376730 -0.132120   
145  Gemcitabine+Apicidin+1        0 -0.22125 -0.311400 -0.347100 -0.117800   
168  Gemcitabine+Apicidin+1        0 -0.28208 -0.367830 -0.357590 -0.148520   
169  Gemcitabine+Apicidin+1        0 -0.21667 -0.321240 -0.308700 -0.134850   
146  Gemcitabine+Apicidin+2        0 -0.40542 -0.067984 -0.103780  0.101190   
147  Gemcitabine+Apicidin+2        0 -0.31125 -0.098822 -0.136400  0.146070   
170  Gemcitabine+Apicidin+2        0 -0.22458 -0.068598 -0.108300 -0.037267   
171  Gemcitabine+Apicidin+2        0 -0.27019 -0.033096  0.064408  0.039915   

         ks5      ks6       ks7      ks8  ...     ks229     ks230    ks231  \
144 -0.68285 -0.51716 -0.350040 -0.32008  ... -0.572590 -0.166210  0.35783   
145 -0.62113 -0.48454 -0.319270 -0.27605  ... -0.539310 -0.143100  0.31013   
168 -0.64672 -0.50793 -0.303410 -0.25926  ... -0.575030 -0.134400  0.33457   
169 -0.63847 -0.43018 -0.266280 -0.23699  ... -0.552080 -0.097649  0.30443   
146 -0.31077 -0.19916 -0.090258  0.14453  ... -0.120990 -0.061994  0.15302   
147 -0.28619 -0.24830 -0.131290 -0.10962  ...  0.131780  0.044722  0.09120   
170 -0.30266 -0.14648 -0.100700  0.14760  ...  0.099887 -0.045447  0.16152   
171 -0.23628 -0.15287  0.081754  0.17347  ...  0.134540 -0.059352  0.12966   

        ks232    ks233     ks234     ks235    ks236     ks237     ks238  
144 -0.574990 -0.56663 -0.166210  0.485570  0.44661 -0.109850 -0.310960  
145 -0.572500 -0.56513 -0.143100  0.479370  0.42423 -0.110740 -0.285030  
168 -0.559730 -0.57154 -0.134400  0.462540  0.41141 -0.135500 -0.295550  
169 -0.572440 -0.57339 -0.097649  0.426120  0.36936 -0.156110 -0.247720  
146 -0.157090 -0.13629 -0.061994 -0.072616  0.17196 -0.066915 -0.149600  
147  0.167460  0.19789  0.044722 -0.191760  0.16164 -0.082621 -0.089007  
170  0.099576  0.12886 -0.045447 -0.152420  0.18198 -0.053902 -0.158750  
171  0.157660  0.17556 -0.059352 -0.225000  0.17178 -0.054184 -0.128230  

[8 rows x 240 columns]

In [142]:
combi=frames+frames2+frames3+frames4+frames5+frames7+frames8+frames9+frames10+frames6
#32 points 160. 
#32
#8 points
#224
training= pd.concat(combi)
#192+4*8=frames7+frames8+frames9+frames10
print(len(training))


224


In [148]:
training

drug_name  default      ks1       ks2       ks3      ks4  \
288   Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.27212   
289   Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.36141   
312   Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.37489   
313   Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.18146   
290   Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.25966   
...                       ...      ...      ...       ...       ...      ...   
1503              DMSO+DMSO+2        0 -0.10833 -0.218940 -0.218850 -0.15368   
1514              DMSO+DMSO+2        0  0.15515  0.058406 -0.092225  0.32201   
1515              DMSO+DMSO+2        0 -0.11708  0.144440  0.143580  0.13645   
1526              DMSO+DMSO+2        0 -0.26842  0.166930  0.207920 -0.14092   
1527              DMSO+DMSO+2        0 -0.43083  0.314670  0.426560 -0.16868   

           ks5      ks6       ks7       ks8  ...     ks229     ks230  \
288  -0.405750 -0.50306 -0.456620 -0.454380  ...  0.309020  0.098262   
289  -0.148340 -0.24613 -0.205880 -0.194610  ...  0.314070  0.058262   
312  -0.284660 -0.36375 -0.341210 -0.338950  ...  0.299810  0.085338   
313  -0.408660 -0.50491 -0.482440 -0.487010  ...  0.282460  0.126550   
290  -0.177040 -0.26364 -0.233270 -0.225690  ...  0.253050  0.160250   
...        ...      ...       ...       ...  ...       ...       ...   
1503 -0.075702 -0.18815 -0.230440 -0.234840  ... -0.183620 -0.058209   
1514  0.061095 -0.14118 -0.070689 -0.054594  ... -0.030696 -0.070114   
1515  0.118600  0.10983  0.153210  0.159460  ...  0.129850 -0.044044   
1526  0.120280  0.21838  0.196360  0.203860  ...  0.053572 -0.093384   
1527  0.121230  0.44859  0.404460  0.407570  ...  0.126320  0.048968   

         ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
288   0.087180  0.399560  0.409440  0.098262 -0.308850 -0.227210  0.098363   
289  -0.141980  0.355410  0.380740  0.058262 -0.132720 -0.186760  0.078267   
312  -0.077312  0.363630  0.383620  0.085338 -0.211410 -0.194220  0.077165   
313   0.074616  0.374620  0.377060  0.126550 -0.305530 -0.230910  0.058352   
290  -0.146910  0.385550  0.390930  0.160250 -0.221980 -0.241610  0.059718   
...        ...       ...       ...       ...       ...       ...       ...   
1503  0.187390 -0.226000 -0.214100 -0.058209  0.148670  0.221960  0.083449   
1514  0.116940 -0.074759 -0.045337 -0.070114  0.169490  0.144980  0.054948   
1515  0.051471  0.114040  0.124020 -0.044044 -0.039142 -0.064804 -0.022770   
1526  0.093702 -0.070864 -0.058081 -0.093384  0.107860  0.121960  0.082383   
1527 -0.264860  0.161010  0.131090  0.048968 -0.155020 -0.267220 -0.113010   

         ks238  
288  -0.091499  
289   0.094994  
312   0.084654  
313  -0.081113  
290   0.144270  
...        ...  
1503 -0.185260  
1514 -0.117670  
1515 -0.046471  
1526 -0.077445  
1527  0.270060  

[224 rows x 240 columns]

In [143]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X_drug = training.iloc[:, 2:240].values

X_drug = StandardScaler().fit_transform(X_drug)

pca_drug = PCA(n_components=8)
components = pca_drug.fit_transform(X_drug)
components
principalDf = pd.DataFrame(data = components
             , columns = ['principal component 1', 'principal component 2','principal component 3', 'principal component 4','principal component 5', 'principal component 6','principal component 7', 'principal component 8'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                -9.216502              -1.083127               3.947371   
1               -10.918911              -4.814663               0.720057   
2                -9.372126              -2.370081               2.849906   
3                -8.814571              -1.230811               4.180942   
4                -8.916498              -2.519523               3.889260   
..                     ...                    ...                    ...   
219               4.030108              -9.494641               5.920126   
220              -0.284967             -11.457702               3.728207   
221              -4.543987             -13.146017               3.223278   
222               0.052153             -13.356379               5.225454   
223              -3.086579              -9.599235               6.137186   

     principal component 4  principal component 5  principal component 6  \
0                -6.173289              -5.368235              -4.980317   
1                -5.669278              -1.005640              -1.107816   
2                -4.975155              -1.419633              -3.204572   
3                -4.594129              -3.795005              -5.765496   
4                -6.869041               0.307287              -1.719183   
..                     ...                    ...                    ...   
219              -0.558454              -2.190695              -4.709146   
220              -1.281739               1.394912              -0.666050   
221               8.865108               4.309105               1.162847   
222               4.477060              -4.657628               2.193209   
223               7.710428               6.000421               6.686870   

     principal component 7  principal component 8  
0                -3.094478              -2.744125  
1                -1.591809              -3.715696  
2                -1.838390              -3.522514  
3                -2.744910              -3.650515  
4                -0.877274              -0.910961  
..                     ...                    ...  
219               0.442542               2.693970  
220               1.123574               1.650439  
221               1.550086              -2.146888  
222               3.890734               0.127012  
223               2.551928               1.778550  

[224 rows x 8 columns]

In [144]:
type(training.iloc[:, 0].values)
import numpy as np
all_names=np.ndarray.tolist(training.iloc[:,0].values)

In [145]:
components2=np.ndarray.tolist(components)

for i in range(len(all_names)):
    components2[i].append(all_names[i])
#components2
len(components2)

224

In [146]:
#class preparation
train_drug_name_without_concentration2=[]
#dna,mt,hsp,prot,hdac
for i in range(32):
    train_drug_name_without_concentration2.append('DNA')
for i in range(32):
    train_drug_name_without_concentration2.append('MT')
for i in range(32):
    train_drug_name_without_concentration2.append('HSP')
for i in range(32):
    train_drug_name_without_concentration2.append('PROT')
for i in range(32):
    train_drug_name_without_concentration2.append('HDAC')

for i in range(8):
    train_drug_name_without_concentration2.append("Gem17AAG")
for i in range(8):
    train_drug_name_without_concentration2.append("GemAUY922")
for i in range(8):
    train_drug_name_without_concentration2.append("GemPac")
for i in range(8):
    train_drug_name_without_concentration2.append("GemApi")
for i in range(32):
    train_drug_name_without_concentration2.append("DMSO")


#train_drug_name_without_concentration2 

In [147]:
import plotly.express as px
fig = px.scatter(components, x=0, y=1, color=train_drug_name_without_concentration2)
fig.show()

In [121]:
def get_centroid(point_lst):
    x_sum=0
    y_sum=0
    z1_sum=0
    z2_sum=0
    z3_sum=0
    z4_sum=0
    z5_sum=0
    z6_sum=0


    for i in range(len(point_lst)):
        x_sum+=point_lst[i][0]
        y_sum+=point_lst[i][1]
        z1_sum+=point_lst[i][2]
        z2_sum+=point_lst[i][3]
        z3_sum+=point_lst[i][4]
        z4_sum+=point_lst[i][5]
        z5_sum+=point_lst[i][6]
        z6_sum+=point_lst[i][7]


    x_mean=x_sum/len(point_lst)
    y_mean=y_sum/len(point_lst)
    z1_mean=z1_sum/len(point_lst)
    z2_mean=z2_sum/len(point_lst)
    z3_mean=z3_sum/len(point_lst)
    z4_mean=z4_sum/len(point_lst)
    z5_mean=z5_sum/len(point_lst)
    z6_mean=z6_sum/len(point_lst)
    centroid=[]
    centroid.append(x_mean)
    centroid.append(y_mean)
    centroid.append(z1_mean)
    centroid.append(z2_mean)
    centroid.append(z3_mean)
    centroid.append(z4_mean)
    centroid.append(z5_mean)
    centroid.append(z6_mean)
    
    return centroid


In [122]:
training

drug_name  default      ks1       ks2       ks3       ks4  \
288  Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.272120   
289  Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.361410   
312  Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.374890   
313  Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.181460   
290  Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.259660   
..                       ...      ...      ...       ...       ...       ...   
169   Gemcitabine+Apicidin+1        0 -0.21667 -0.321240 -0.308700 -0.134850   
146   Gemcitabine+Apicidin+2        0 -0.40542 -0.067984 -0.103780  0.101190   
147   Gemcitabine+Apicidin+2        0 -0.31125 -0.098822 -0.136400  0.146070   
170   Gemcitabine+Apicidin+2        0 -0.22458 -0.068598 -0.108300 -0.037267   
171   Gemcitabine+Apicidin+2        0 -0.27019 -0.033096  0.064408  0.039915   

         ks5      ks6       ks7      ks8  ...     ks229     ks230     ks231  \
288 -0.40575 -0.50306 -0.456620 -0.45438  ...  0.309020  0.098262  0.087180   
289 -0.14834 -0.24613 -0.205880 -0.19461  ...  0.314070  0.058262 -0.141980   
312 -0.28466 -0.36375 -0.341210 -0.33895  ...  0.299810  0.085338 -0.077312   
313 -0.40866 -0.50491 -0.482440 -0.48701  ...  0.282460  0.126550  0.074616   
290 -0.17704 -0.26364 -0.233270 -0.22569  ...  0.253050  0.160250 -0.146910   
..       ...      ...       ...      ...  ...       ...       ...       ...   
169 -0.63847 -0.43018 -0.266280 -0.23699  ... -0.552080 -0.097649  0.304430   
146 -0.31077 -0.19916 -0.090258  0.14453  ... -0.120990 -0.061994  0.153020   
147 -0.28619 -0.24830 -0.131290 -0.10962  ...  0.131780  0.044722  0.091200   
170 -0.30266 -0.14648 -0.100700  0.14760  ...  0.099887 -0.045447  0.161520   
171 -0.23628 -0.15287  0.081754  0.17347  ...  0.134540 -0.059352  0.129660   

        ks232    ks233     ks234     ks235    ks236     ks237     ks238  
288  0.399560  0.40944  0.098262 -0.308850 -0.22721  0.098363 -0.091499  
289  0.355410  0.38074  0.058262 -0.132720 -0.18676  0.078267  0.094994  
312  0.363630  0.38362  0.085338 -0.211410 -0.19422  0.077165  0.084654  
313  0.374620  0.37706  0.126550 -0.305530 -0.23091  0.058352 -0.081113  
290  0.385550  0.39093  0.160250 -0.221980 -0.24161  0.059718  0.144270  
..        ...      ...       ...       ...      ...       ...       ...  
169 -0.572440 -0.57339 -0.097649  0.426120  0.36936 -0.156110 -0.247720  
146 -0.157090 -0.13629 -0.061994 -0.072616  0.17196 -0.066915 -0.149600  
147  0.167460  0.19789  0.044722 -0.191760  0.16164 -0.082621 -0.089007  
170  0.099576  0.12886 -0.045447 -0.152420  0.18198 -0.053902 -0.158750  
171  0.157660  0.17556 -0.059352 -0.225000  0.17178 -0.054184 -0.128230  

[224 rows x 240 columns]

In [155]:
len(principalDf[-32:])

32

In [154]:
#DMSO filtering part
dmso_centroid=get_centroid(components[-32:])


In [156]:
dmso_lst=components[-32:]

In [157]:
#calculating the distance
from math import sqrt
def euclidean_distance(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(len(row1)-1):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [158]:
dist_lst=[]
for i in range(len(dmso_lst)):
    dist_lst.append(euclidean_distance(dmso_lst[i],dmso_centroid))
dist_lst.sort()
print(len(dist_lst))
max_ave=sum(dist_lst[-5:-1])/len(dist_lst[-5:-1])
max_ave
max_ave*=2
max_ave

32


26.337767055828216

In [159]:
#outlier computation
# method 1.
#distance ditribution
Q1 = np.percentile(dist_lst , 25)
Q3 = np.percentile(dist_lst , 75)
# method 2.
Q1,Q3 = np.percentile(dist_lst , [25,75])


In [160]:
IQR = Q3 - Q1
ul = Q3+1.5*IQR
ll = Q1-1.5*IQR


15.75209113630288 1.7482176047531697


In [161]:
Q1

6.999670179084311

In [162]:
Q3

10.500638561971739

In [163]:
def euclidean_distance2(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(8):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [274]:
dist_lst2=[]
filtered_lst=[]
index_lst=[]
for i in range(len(components2[:192])):
    dist_lst2.append(euclidean_distance2(components2[i],dmso_centroid))
    if euclidean_distance2(components2[i],dmso_centroid)>max_ave:
        filtered_lst.append(components2[i])
        index_lst.append(i)



#filtered_lst
#dist_lst2
print(len(filtered_lst))
print(len(dist_lst2))
print(len(index_lst))
#filtered_lst


10
192
10


In [166]:
dist_lst2=[]
filtered_lst=[]
index_lst=[]
for i in range(len(components2[:192])):
    dist_lst2.append(euclidean_distance2(components2[i],dmso_centroid))
    if euclidean_distance2(components2[i],dmso_centroid)>ul:
        filtered_lst.append(components2[i])
        index_lst.append(i)



#filtered_lst
#dist_lst2
print(len(filtered_lst))
print(len(dist_lst2))
print(len(index_lst))
#filtered_lst


144
192
144


In [134]:
#index_lst

In [167]:
# labels for class. second time
#17AAG, AUY922,Pac,Api
class_name=[]
cnt1=cnt2=cnt3=cnt4=cnt5=0
cnt6=cnt7=cnt8=cnt9=0

for i in range(len(index_lst)):
    if index_lst[i]<32:
        class_name.append('DNA')
        cnt1+=1

    
    elif index_lst[i]<64:
        class_name.append('MT')
        cnt2+=1

    
    elif index_lst[i]<96:
        class_name.append('HSP')
        cnt3+=1
    
    elif index_lst[i]<128:
        cnt4+=1
        
        class_name.append('PROT')
    
    elif index_lst[i]<160:
        cnt5+=1
        class_name.append('HDAC')
    elif index_lst[i]<168:
        cnt6+=1
        class_name.append('Gem17AAG')
    elif index_lst[i]<176:
        cnt7+=1
        class_name.append('GemAUY922')
    elif index_lst[i]<184:
        cnt8+=1
        class_name.append('GemPac')
    elif index_lst[i]<192:
        cnt9+=1
        class_name.append('GemApi')
    

for i in range(32):
    class_name.append("DMSO")
len(class_name)
predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5,cnt6,cnt7,cnt8,cnt9]
print(predict_counter)


[20, 21, 32, 31, 14, 8, 8, 6, 4]


In [181]:
#second scatterplot
components5=[]
for i in range(len(index_lst)):
    components5.append(components[i])
for i in range(144,176):
    components5.append(components[i])
components5

[array([-9.21650209, -1.08312698,  3.94737088, -6.17328931, -5.36823481,
        -4.98031749, -3.09447778, -2.74412497]),
 array([-10.91891087,  -4.81466258,   0.72005684,  -5.66927845,
         -1.00564042,  -1.10781626,  -1.5918093 ,  -3.71569556]),
 array([-9.37212639, -2.37008071,  2.84990586, -4.97515506, -1.41963316,
        -3.20457182, -1.83839027, -3.52251421]),
 array([-8.81457077, -1.23081122,  4.18094153, -4.59412874, -3.79500542,
        -5.76549619, -2.74490987, -3.65051547]),
 array([-8.9164977 , -2.51952264,  3.88925953, -6.8690408 ,  0.30728716,
        -1.71918287, -0.87727358, -0.91096059]),
 array([-9.8753512 , -4.46086382,  2.32220555, -8.38973443,  5.11451322,
         5.87830473,  2.24342021,  0.11359708]),
 array([-10.82322607,  -6.9316511 ,  -0.8297888 ,  -2.76518286,
          6.55328852,  -2.01033341,  -0.23630664,  -1.44157461]),
 array([-10.12586795,  -6.87905918,   0.89136295,  -8.50739731,
          2.32731617,   4.26082775,   1.42267313,  -0.7098113 ]),


In [182]:
len(filtered_lst)

144

In [183]:
fig = px.scatter(components5, x=0, y=1, color=class_name)
#training['drug_name']
fig.show()

In [187]:
#after using pca to do the filter, we gonna use LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(32):
    y2.append('DNA')
for j in range(32):
    y2.append('MT')
for k in range(32):
    y2.append('HSP')
for m in range(32):
    y2.append('PROT')
for n in range(32):
    y2.append('HDAC')

for i in range(8):
    y2.append('Gem17AAG')
for i in range(8):
    y2.append('GemAUY922')
for i in range(8):
    y2.append('GemPac')

for i in range(8):
    y2.append('GemApi')


for k in range(32):
    y2.append("DMSO")
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug5=training.iloc[:,2:240].values
X_drug5=model.fit(X_drug5,y2).transform(X_drug5)

In [257]:
len(training)

224

In [176]:
len(X_drug5)

224

In [177]:
# Create a function
def select_n_components(var_ratio, goal_var: float) -> int:
    # Set initial variance explained so far
    total_variance = 0.0
    
    # Set initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for explained_variance in var_ratio:
        
        # Add the explained variance to the total
        total_variance += explained_variance
        
        # Add one to the number of components
        n_components += 1
        
        # If we reach our goal level of explained variance
        if total_variance >= goal_var:
            # End the loop
            break
            
    # Return the number of components
    return n_components

In [178]:
lda = LinearDiscriminantAnalysis(n_components=None)
X_lda=lda.fit(X_drug5,y2)
lda_var_ratios = lda.explained_variance_ratio_
print(lda_var_ratios)
print(select_n_components(lda_var_ratios, 0.95))
print(select_n_components(lda_var_ratios, 0.85))
print(select_n_components(lda_var_ratios, 0.75))
print(select_n_components(lda_var_ratios, 0.65))
print(select_n_components(lda_var_ratios, 0.35))
#print(X_drug5)

[0.45936731 0.38699944 0.10306715 0.0505661 ]
4
3
2
2
1


In [179]:
filtered_lda=np.ndarray.tolist(X_drug5)

In [189]:
len(X_drug5)

224

In [188]:
#filtered_lda
filtered_drug=[]
for i in range(len(index_lst)):
    filtered_drug.append(filtered_lda[i])
for i in range(144,176):
    filtered_drug.append(filtered_lda[i])
print(len(filtered_drug),len(class_name))


176 176


In [190]:
fig = px.scatter(filtered_drug, x=0, y=1, color=class_name)
#training['drug_name']
fig.show()

In [191]:
#original figure
class_name
fig = px.scatter(X_drug5, x=0, y=1, color=train_drug_name_without_concentration2)
#training['drug_name']
fig.show()

In [252]:
#bootstrapping
for i in range(len(filtered_lst)):
    print(filtered_lst[i][-1])

Gemcitabine+Etoposide+1
Gemcitabine+Etoposide+1
Gemcitabine+Etoposide+2
Gemcitabine+Etoposide+2
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Etoposide+DMSO+1
Etoposide+DMSO+1
Etoposide+DMSO+1
Etoposide+DMSO+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+2
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+2
17AAG+AUY922+2
17AAG+AUY922+2
17AAG+AUY922+2
AUY922+AUY92

In [ ]:
filtered_lst=

In [193]:
len(filtered_lst)

144

In [267]:
def accuracy(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(cnt1//4):
        list3.append(list2[0])
    for j in range(cnt2//4):
        list3.append(list2[1])
    for m in range(cnt3//4):
        list3.append(list2[2])
    for n in range(cnt4//4):
        list3.append(list2[3])
    for k in range(cnt5//4):
        list3.append(list2[4])
    
    for i in range(cnt6//4):
        list3.append(list2[5])
    for i in range(cnt7//4):
        list3.append(list2[6])
    for i in range(cnt8//4):
        list3.append(list2[7])
    for i in range(cnt9//4):
        list3.append(list2[8])
    for k in range(8):
        list3.append(list2[9])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [195]:
len(index_lst)

144

In [196]:
lst=[1,2,3,4,5,6]
print(lst[:4])

[1, 2, 3, 4]


In [197]:
print(predict_counter)
#predict:1,5,7,4,1  18
#training:84-18=56
#56+24=90

[20, 21, 32, 31, 14, 8, 8, 6, 4]


In [201]:
#training and testing data preparation
#

import random
global random_chosen
global chosen_index_lst
global left_lst

random_chosen=[]
chosen_index_lst=[]

chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
cnt_newstart=cnt1+cnt2+cnt3+cnt4+cnt5
chosen_index_lst+=random.sample(index_lst[cnt_newstart:cnt_newstart+cnt6],cnt6//4)
chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6:cnt_newstart+cnt6+cnt7],cnt7//4)
chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7:cnt_newstart+cnt6+cnt7+cnt8],cnt8//4)
chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7+cnt8:cnt_newstart+cnt6+cnt7+cnt8+cnt9],cnt9//4)
chosen_index_lst

#print([cnt1,cnt2,cnt3,cnt4,cnt5])
#print(chosen_index_lst)
left_lst=list(set(index_lst)^set(chosen_index_lst))
#print(left_lst)
#print(len(chosen_index_lst))
#print(len(left_lst))
#print(len(chosen_index_lst)+len(left_lst))

In [202]:
len(chosen_index_lst)
len(index_lst)
len(left_lst)

110

In [261]:
testing_index

[27,
 10,
 8,
 19,
 17,
 44,
 40,
 37,
 50,
 55,
 74,
 85,
 89,
 87,
 65,
 68,
 64,
 66,
 97,
 107,
 103,
 111,
 99,
 124,
 98,
 144,
 139,
 129,
 165,
 167,
 175,
 171,
 178,
 184,
 223,
 201,
 198,
 197,
 215,
 221,
 195,
 196]

In [262]:
print([cnt5,cnt6,cnt7,cnt8,cnt9])

[14, 8, 8, 6, 4]


In [203]:
#training and testing dataset
import random

global training_index
global testing_index
global dmso_left
global left_lst

dmso_index=[]
for i in range(192,224):
    dmso_index.append(i)
dmso_chosen=random.sample(dmso_index,32//4)
#chosen_index_lst+=dmso_chosen
dmso_left=list(set(dmso_index)^set(dmso_chosen))
print(len(dmso_left))
training_index=left_lst+dmso_left
testing_index=chosen_index_lst+dmso_chosen
#print(len(training_index))
#print(len(testing_index))


24


In [204]:
len(dmso_left)
len(left_lst)

110

In [256]:
len(X_drug5)

224

In [206]:
#training data and testing data

global X_train
global X_test
X_train=[]
X_test=[]
for i in range(len(training_index)):
    X_train.append(X_drug5[training_index[i]])
for i in range(len(testing_index)):
    X_test.append(X_drug5[testing_index[i]])


In [207]:
len(index_lst)

144

In [209]:
# labels for class. second time

global class_name_train
index_lst2=training_index
print(len(index_lst2))
#class_name_train=[]
#cnt1=cnt2=cnt3=cnt4=cnt5=0
class_name_train=[]
for i in range(len(index_lst2)):
    if index_lst2[i]<32:
        class_name_train.append('DNA')
        
        #cnt1+=1

    
    elif index_lst2[i]<64:
        class_name_train.append('MT')
        
        #cnt2+=1

    
    elif index_lst2[i]<96:
        class_name_train.append('HSP')
        
    #cnt3+=1

    elif index_lst2[i]<128:
        #cnt4+=1
        
        class_name_train.append('PROT')
        
    
    elif index_lst2[i]<160:
        #cnt5+=1
        class_name_train.append('HDAC')
    elif index_lst2[i]<168:
        #cnt5+=1
        class_name_train.append('Gem17AAG')
    elif index_lst2[i]<176:
        #cnt5+=1
        class_name_train.append('GemAUY922')
    elif index_lst2[i]<184:
        #cnt5+=1
        class_name_train.append('GemPac')
    elif index_lst2[i]<192:
        #cnt5+=1
        class_name_train.append('GemApi')


#10 drugs, 5 classes   40
#10 drugs -> permutations/ combinations//2  10*9 //2 =45 
#
        
print(len(class_name_train))
for i in range(24):
    class_name_train.append("DMSO")
print(len(class_name_train))
#print(len(class_name))
#predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
#print(predict_counter)
#class_name_train=class_name

134
110
134


In [210]:
len(training_index)
len(testing_index)

42

In [255]:
len(filtered_lst)

144

In [260]:
training

drug_name  default      ks1       ks2       ks3      ks4  \
288   Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.27212   
289   Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.36141   
312   Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.37489   
313   Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.18146   
290   Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.25966   
...                       ...      ...      ...       ...       ...      ...   
1503              DMSO+DMSO+2        0 -0.10833 -0.218940 -0.218850 -0.15368   
1514              DMSO+DMSO+2        0  0.15515  0.058406 -0.092225  0.32201   
1515              DMSO+DMSO+2        0 -0.11708  0.144440  0.143580  0.13645   
1526              DMSO+DMSO+2        0 -0.26842  0.166930  0.207920 -0.14092   
1527              DMSO+DMSO+2        0 -0.43083  0.314670  0.426560 -0.16868   

           ks5      ks6       ks7       ks8  ...     ks229     ks230  \
288  -0.405750 -0.50306 -0.456620 -0.454380  ...  0.309020  0.098262   
289  -0.148340 -0.24613 -0.205880 -0.194610  ...  0.314070  0.058262   
312  -0.284660 -0.36375 -0.341210 -0.338950  ...  0.299810  0.085338   
313  -0.408660 -0.50491 -0.482440 -0.487010  ...  0.282460  0.126550   
290  -0.177040 -0.26364 -0.233270 -0.225690  ...  0.253050  0.160250   
...        ...      ...       ...       ...  ...       ...       ...   
1503 -0.075702 -0.18815 -0.230440 -0.234840  ... -0.183620 -0.058209   
1514  0.061095 -0.14118 -0.070689 -0.054594  ... -0.030696 -0.070114   
1515  0.118600  0.10983  0.153210  0.159460  ...  0.129850 -0.044044   
1526  0.120280  0.21838  0.196360  0.203860  ...  0.053572 -0.093384   
1527  0.121230  0.44859  0.404460  0.407570  ...  0.126320  0.048968   

         ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
288   0.087180  0.399560  0.409440  0.098262 -0.308850 -0.227210  0.098363   
289  -0.141980  0.355410  0.380740  0.058262 -0.132720 -0.186760  0.078267   
312  -0.077312  0.363630  0.383620  0.085338 -0.211410 -0.194220  0.077165   
313   0.074616  0.374620  0.377060  0.126550 -0.305530 -0.230910  0.058352   
290  -0.146910  0.385550  0.390930  0.160250 -0.221980 -0.241610  0.059718   
...        ...       ...       ...       ...       ...       ...       ...   
1503  0.187390 -0.226000 -0.214100 -0.058209  0.148670  0.221960  0.083449   
1514  0.116940 -0.074759 -0.045337 -0.070114  0.169490  0.144980  0.054948   
1515  0.051471  0.114040  0.124020 -0.044044 -0.039142 -0.064804 -0.022770   
1526  0.093702 -0.070864 -0.058081 -0.093384  0.107860  0.121960  0.082383   
1527 -0.264860  0.161010  0.131090  0.048968 -0.155020 -0.267220 -0.113010   

         ks238  
288  -0.091499  
289   0.094994  
312   0.084654  
313  -0.081113  
290   0.144270  
...        ...  
1503 -0.185260  
1514 -0.117670  
1515 -0.046471  
1526 -0.077445  
1527  0.270060  

[224 rows x 240 columns]

In [259]:
test_drug=[]
for i in range(len(testing_index)):
    print(training[testing_index[i]])




KeyError: 27

[array([-12.75565238,  -5.81132026, -22.31559534,  -0.65583723]),
 array([-13.32401945,  -5.92410897, -21.43706909,   0.18759633]),
 array([-14.15017488,  -5.08740156, -23.60396495,  -1.50060385]),
 array([-10.58278958,  -6.97088988, -23.8043653 ,  -0.50508564]),
 array([-14.77702397,  -5.19816618, -22.82887028,  -0.759222  ]),
 array([10.90986157, -4.31161646, 10.70741766,  5.03866779]),
 array([13.07099901, -3.35265606, 11.37534287,  3.40940915]),
 array([11.96255987, -4.17221658, 12.53552539,  4.27422977]),
 array([12.51924865, -4.81063918, 11.67938599,  3.6281821 ]),
 array([11.78385999, -4.54875015, 12.21389579,  3.82669093]),
 array([-7.40539692, 36.60842434,  0.22853415, 15.01978657]),
 array([-7.04217394, 36.48561588, -2.04410356, 16.7777961 ]),
 array([-7.67529591, 35.2921851 ,  0.94593895, 15.98374208]),
 array([-6.46187437, 34.83105036, -0.32357753, 13.85606057]),
 array([-5.67664902, 34.7454564 , -2.08855121, 18.59170161]),
 array([-5.59581705, 35.20112598, -0.56819891, 14.

In [266]:
#prediction LDA
model2 = LinearDiscriminantAnalysis(n_components=4)
model2.fit(X_train,class_name_train)
yhat2=model2.predict(X_test)

print(yhat2)
print(len(yhat2))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP' 'HSP' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'PROT' 'HDAC' 'HDAC' 'HDAC' 'Gem17AAG' 'Gem17AAG' 'GemAUY922' 'GemAUY922'
 'GemPac' 'GemApi' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO']
42


In [265]:
print([cnt1,cnt2,cnt3,cnt4,cnt5])

[20, 21, 32, 31, 14]


In [268]:
#accuracy
accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","Gem17AAG","GemAUY922","GemPac","GemApi","DMSO"])

1.0

In [269]:
accuracy_lst=[]
def pipeline():
    import random
    global random_chosen
    global chosen_index_lst
    global left_lst

    random_chosen=[]
    chosen_index_lst=[]

    chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
    chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
    cnt_newstart=cnt1+cnt2+cnt3+cnt4+cnt5
    chosen_index_lst+=random.sample(index_lst[cnt_newstart:cnt_newstart+cnt6],cnt6//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6:cnt_newstart+cnt6+cnt7],cnt7//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7:cnt_newstart+cnt6+cnt7+cnt8],cnt8//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7+cnt8:cnt_newstart+cnt6+cnt7+cnt8+cnt9],cnt9//4)
    #chosen_index_lst

    #print([cnt1,cnt2,cnt3,cnt4,cnt5])
    #print(chosen_index_lst)
    left_lst=list(set(index_lst)^set(chosen_index_lst))
    #print(left_lst)
    #print(len(chosen_index_lst))
    #print(len(left_lst))
    #print(len(chosen_index_lst)+len(left_lst))

    # %%
    #len(chosen_index_lst)
    #len(index_lst)
    #len(left_lst)

    # %%
    #training and testing dataset
    import random

    global training_index
    global testing_index
    global dmso_left
    

    dmso_index=[]
    for i in range(192,224):
        dmso_index.append(i)
    dmso_chosen=random.sample(dmso_index,32//4)
    #chosen_index_lst+=dmso_chosen
    dmso_left=list(set(dmso_index)^set(dmso_chosen))
    #print(len(dmso_left))
    training_index=left_lst+dmso_left
    testing_index=chosen_index_lst+dmso_chosen
    #print(len(training_index))
    #print(len(testing_index))


    # %%
    #len(dmso_left)
    #len(left_lst)

    # %%
    #training data and testing data

    global X_train
    global X_test
    X_train=[]
    X_test=[]
    for i in range(len(training_index)):
        X_train.append(X_drug5[training_index[i]])
    for i in range(len(testing_index)):
        X_test.append(X_drug5[testing_index[i]])


    # %%
    #len(index_lst)

    # %%
    # labels for class. second time

    global class_name_train
    index_lst2=training_index
    #print(len(index_lst2))
    #class_name_train=[]
    #cnt1=cnt2=cnt3=cnt4=cnt5=0
    class_name_train=[]
    for i in range(len(index_lst2)):
        if index_lst2[i]<32:
            class_name_train.append('DNA')
            
            #cnt1+=1

    
        elif index_lst2[i]<64:
            class_name_train.append('MT')
            
            #cnt2+=1

        
        elif index_lst2[i]<96:
            class_name_train.append('HSP')
            
        #cnt3+=1

        elif index_lst2[i]<128:
            #cnt4+=1
            
            class_name_train.append('PROT')
            
        
        elif index_lst2[i]<160:
            #cnt5+=1
            class_name_train.append('HDAC')
        elif index_lst2[i]<168:
            #cnt5+=1
            class_name_train.append('Gem17AAG')
        elif index_lst2[i]<176:
            #cnt5+=1
            class_name_train.append('GemAUY922')
        elif index_lst2[i]<184:
            #cnt5+=1
            class_name_train.append('GemPac')
        elif index_lst2[i]<192:
            #cnt5+=1
            class_name_train.append('GemApi')
            
    #print(len(class_name_train))
    for i in range(24):
        class_name_train.append("DMSO")
    #print(len(class_name_train))
    #print(len(class_name))
    #predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
    #print(predict_counter)
    #class_name_train=class_name

    # %%
    #len(training_index)
    #len(testing_index)

    # %%
    #prediction LDA
    model2 = LinearDiscriminantAnalysis(n_components=4)
    model2.fit(X_train,class_name_train)
    yhat2=model2.predict(X_test)

    #print(yhat2)
    #print(len(yhat2))





    

    # %%
    #accuracy
    
    result.append(yhat2)
    accuracy_score=accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","Gem17AAG","GemAUY922","GemPac","GemApi","DMSO"])
    accuracy_lst.append(accuracy_score)

    # %%
    
    

In [273]:
#ten times test (LDA)
accuracy_lst=[]
result=[]
for i in range(20):
    pipeline()
#print(accuracy_lst)
print("average accuracy: "+str(sum(accuracy_lst)/len(accuracy_lst)))
#print(result)
accuracy_lst


average accuracy: 1.0


[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [271]:
accuracy_lst=[]
def pipeline():
    import random
    global random_chosen
    global chosen_index_lst
    global left_lst

    random_chosen=[]
    chosen_index_lst=[]

    chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
    chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
    cnt_newstart=cnt1+cnt2+cnt3+cnt4+cnt5
    chosen_index_lst+=random.sample(index_lst[cnt_newstart:cnt_newstart+cnt6],cnt6//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6:cnt_newstart+cnt6+cnt7],cnt7//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7:cnt_newstart+cnt6+cnt7+cnt8],cnt8//4)
    chosen_index_lst+=random.sample(index_lst[cnt_newstart+cnt6+cnt7+cnt8:cnt_newstart+cnt6+cnt7+cnt8+cnt9],cnt9//4)
    #chosen_index_lst

    #print([cnt1,cnt2,cnt3,cnt4,cnt5])
    #print(chosen_index_lst)
    left_lst=list(set(index_lst)^set(chosen_index_lst))
    #print(left_lst)
    #print(len(chosen_index_lst))
    #print(len(left_lst))
    #print(len(chosen_index_lst)+len(left_lst))

    # %%
    #len(chosen_index_lst)
    #len(index_lst)
    #len(left_lst)

    # %%
    #training and testing dataset
    import random

    global training_index
    global testing_index
    global dmso_left
    

    dmso_index=[]
    for i in range(192,224):
        dmso_index.append(i)
    dmso_chosen=random.sample(dmso_index,32//4)
    #chosen_index_lst+=dmso_chosen
    dmso_left=list(set(dmso_index)^set(dmso_chosen))
    #print(len(dmso_left))
    training_index=left_lst+dmso_left
    testing_index=chosen_index_lst+dmso_chosen
    #print(len(training_index))
    #print(len(testing_index))


    # %%
    #len(dmso_left)
    #len(left_lst)

    # %%
    #training data and testing data

    global X_train
    global X_test
    X_train=[]
    X_test=[]
    for i in range(len(training_index)):
        X_train.append(X_drug5[training_index[i]])
    for i in range(len(testing_index)):
        X_test.append(X_drug5[testing_index[i]])


    # %%
    #len(index_lst)

    # %%
    # labels for class. second time

    global class_name_train
    index_lst2=training_index
    #print(len(index_lst2))
    #class_name_train=[]
    #cnt1=cnt2=cnt3=cnt4=cnt5=0
    class_name_train=[]
    for i in range(len(index_lst2)):
        if index_lst2[i]<32:
            class_name_train.append('DNA')
            
            #cnt1+=1

    
        elif index_lst2[i]<64:
            class_name_train.append('MT')
            
            #cnt2+=1

        
        elif index_lst2[i]<96:
            class_name_train.append('HSP')
            
        #cnt3+=1

        elif index_lst2[i]<128:
            #cnt4+=1
            
            class_name_train.append('PROT')
            
        
        elif index_lst2[i]<160:
            #cnt5+=1
            class_name_train.append('HDAC')
        elif index_lst2[i]<168:
            #cnt5+=1
            class_name_train.append('Gem17AAG')
        elif index_lst2[i]<176:
            #cnt5+=1
            class_name_train.append('GemAUY922')
        elif index_lst2[i]<184:
            #cnt5+=1
            class_name_train.append('GemPac')
        elif index_lst2[i]<192:
            #cnt5+=1
            class_name_train.append('GemApi')
            
    #print(len(class_name_train))
    for i in range(24):
        class_name_train.append("DMSO")
    #print(len(class_name_train))
    #print(len(class_name))
    #predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
    #print(predict_counter)
    #class_name_train=class_name

    # %%
    #len(training_index)
    #len(testing_index)

    # %%
    #prediction LDA
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import accuracy_score
    knn5 = KNeighborsClassifier(n_neighbors=60)
    knn5.fit(X_train, class_name_train)
    y_pred_5 = knn5.predict(X_test)

    #print(yhat2)
    #print(len(yhat2))





    

    # %%
    #accuracy
    
    result.append(yhat2)
    accuracy_score=accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","Gem17AAG","GemAUY922","GemPac","GemApi","DMSO"])
    accuracy_lst.append(accuracy_score)

    # %%
    
    

In [272]:
accuracy_lst=[]
for i in range(30):
    pipeline()
#print(accuracy_lst)
print(sum(accuracy_lst)/len(accuracy_lst))


1.0


In [ ]:
#prediction
#just found an error in my accuracy function