In [1]:
#a code block that deals with concentration and drug names
#we do not use this block for now.

import pandas as pd
f1 = pd.read_csv('B.csv')
f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('A_ks3.csv')
file = [f1,f2,f3,f5]
train = pd.concat(file,axis=1)
train.to_csv("train.csv", index=0, sep=',')


In [2]:
#do some further processing with "A" because there are some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('A_ks3.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('modified_A.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                


-0.294442


In [3]:
#test file A
import pandas as pd
df_A=pd.read_csv("A_ks3.csv")
df_A.shape
#df_A2=pd.read_csv("A_modified.csv")
#df_A2.shape


(767, 239)

In [4]:
#a block that is used to concate the drug names(drug combinations and related concentration)

import csv
res_list=[]
with open('train.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        data=[]
        data.append(row[0]+'+'+row[1]+"+"+row[2])
        res_list.append(data)

        
        
with open('concatenated.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerows(res_list)

In [5]:
#a block that is used to concate concentration and ks numbers.
import pandas as pd
f1 = pd.read_csv('concatenated.csv')
#f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D.csv')
f4=pd.read_csv('E.csv')
f5=pd.read_csv('modified_A.csv')
file = [f1,f5]
train = pd.concat(file,axis=1)
train.to_csv("train3.csv", index=0, sep=',')

In [6]:
#a block that sets the fields for the drug data
import csv
fields=['drug_name','default']
for i in range(1,239):
    fields.append('ks'+str(i))
rows=[]
with open('train3.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        rows.append(row)

        
        
with open('drug_withfields2.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerow(fields)
    writer.writerows(rows)

In [7]:
#do some further processing with "drug_withfields" because there are still some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('drug_withfields2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('drug_with_fields.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                

-0.294442


In [8]:
df=pd.read_csv('drug_with_fields.csv')
#one type first type. dna
df11=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+2') ]
df13=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+3') ]
df14=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+4') ]
df15=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+5') ]
df16=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+6') ]
df21=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+1') ]
df22=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+2') ]
df23=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+3') ]
df24=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+4') ]
df25=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+5') ]
df26=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+6') ]
df31=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df32=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]
df33=df.loc[(df['drug_name'] =='Etoposide+Etoposide+3') ]
df34=df.loc[(df['drug_name'] =='Etoposide+Etoposide+4') ]
df35=df.loc[(df['drug_name'] =='Etoposide+Etoposide+5') ]
df36=df.loc[(df['drug_name'] =='Etoposide+Etoposide+6') ]
df41=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+1') ]
df42=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+2') ]
df43=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+3') ]
df44=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+4') ]
df45=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+5') ]
df46=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+6') ]
frames = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
dna = pd.concat(frames)
dna


drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.639170 -0.144250  0.148430   
14    Etoposide+Gemcitabine+2        0 -0.565830 -0.148970 -0.173080   
16    Etoposide+Gemcitabine+3        0 -0.535830  0.097875 -0.143150   
18    Etoposide+Gemcitabine+4        0 -0.459460  0.090733 -0.140140   
20    Etoposide+Gemcitabine+5        0 -0.098333 -0.079680 -0.120000   
22    Etoposide+Gemcitabine+6        0 -0.056667 -0.030110  0.025658   
72    Gemcitabine+Etoposide+1        0 -0.690830 -0.072245  0.192740   
74    Gemcitabine+Etoposide+2        0 -0.644170 -0.170130  0.119350   
76    Gemcitabine+Etoposide+3        0 -0.515000 -0.122820  0.123830   
78    Gemcitabine+Etoposide+4        0  0.019287 -0.145030 -0.192740   
80    Gemcitabine+Etoposide+5        0  0.087826 -0.167370 -0.172580   
82    Gemcitabine+Etoposide+6        0  0.046287 -0.124100 -0.127340   
0       Etoposide+Etoposide+1        0 -0.658330 -0.151980 -0.133790   
2       Etoposide+Etoposide+2        0 -0.596670 -0.183410 -0.224890   
4       Etoposide+Etoposide+3        0 -0.507540  0.080714 -0.125940   
6       Etoposide+Etoposide+4        0 -0.053269 -0.097863 -0.140810   
8       Etoposide+Etoposide+5        0  0.038568 -0.070623 -0.084830   
10      Etoposide+Etoposide+6        0 -0.021682 -0.073558 -0.087733   
84  Gemcitabine+Gemcitabine+1        0 -0.577500 -0.105360  0.197020   
86  Gemcitabine+Gemcitabine+2        0 -0.550000 -0.147800  0.190130   
88  Gemcitabine+Gemcitabine+3        0 -0.567500 -0.097928  0.175350   
90  Gemcitabine+Gemcitabine+4        0 -0.418330  0.067900 -0.145000   
92  Gemcitabine+Gemcitabine+5        0 -0.086594 -0.154860 -0.197830   
94  Gemcitabine+Gemcitabine+6        0  0.062926 -0.086938 -0.063973   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.206640 -0.365490 -0.116250  0.160770  0.205180  ...  0.247910  0.142580   
14 -0.251080 -0.377400 -0.185960 -0.166540 -0.149940  ...  0.235990  0.189400   
16 -0.098313 -0.125500 -0.143980 -0.158160 -0.148350  ...  0.278330  0.256040   
18 -0.069508 -0.167160 -0.150810 -0.136360 -0.125550  ...  0.233550  0.226280   
20 -0.084225 -0.170440 -0.116250 -0.111180 -0.106920  ...  0.057003  0.043050   
22 -0.061638 -0.047487  0.029334  0.035004  0.038447  ... -0.021942  0.024703   
72 -0.173770 -0.333780  0.063140  0.226760  0.267730  ...  0.181340  0.121490   
74 -0.200000 -0.381920 -0.115790  0.153420  0.204870  ...  0.208230  0.145430   
76 -0.201090 -0.403390 -0.116680  0.145850  0.198010  ...  0.166140  0.111680   
78 -0.111530 -0.278820 -0.193440 -0.168010 -0.159800  ... -0.075304 -0.036240   
80 -0.098315 -0.294110 -0.173290 -0.144740 -0.138530  ... -0.109910  0.026654   
82 -0.088924 -0.230600 -0.126990 -0.107180 -0.095707  ... -0.087753 -0.039599   
0  -0.228720 -0.421970 -0.130760  0.161730  0.208450  ...  0.232730  0.096027   
2  -0.310260 -0.445170 -0.227970 -0.190090 -0.174000  ...  0.220820  0.146930   
4   0.104190 -0.129000 -0.133430 -0.130930 -0.134840  ...  0.299920  0.118720   
6  -0.122950 -0.187030 -0.133820 -0.118800 -0.111940  ... -0.037030  0.022158   
8  -0.055402 -0.134990 -0.088421 -0.069816 -0.063219  ... -0.065165  0.025711   
10 -0.079325 -0.128700 -0.096127 -0.071604 -0.062475  ... -0.037668 -0.027406   
84 -0.168100 -0.319050  0.068571  0.231790  0.267980  ...  0.115600  0.153210   
86 -0.239410 -0.402250 -0.110940  0.227700  0.269670  ...  0.163910  0.109200   
88 -0.199960 -0.304410 -0.101320  0.185030  0.226570  ...  0.138680  0.137460   
90 -0.118180 -0.190180 -0.141560 -0.137320 -0.126020  ...  0.196990  0.196180   
92 -0.135800 -0.295870 -0.196300 -0.166920 -0.165830  ... -0.073804  0.028551   
94 -0.070039 -0.167980 -0.071415 -0.042771 -0.042655  ... -0.089477 -0.042016   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.400640  0.383250  0.333460  0.142580 -0.582600 -0.645280 -0.255230   
14 -0.425990  0.397740  0.312770  0.18940

In [9]:

#one type first type. mt
df11=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+1') ]
df12=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+2') ]
df13=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+3') ]
df14=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+4') ]
df15=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+5') ]
df16=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+6') ]
df21=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+2') ]
df23=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+3') ]
df24=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+4') ]
df25=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+5') ]
df26=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+6') ]
df31=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df32=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]
df33=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+3') ]
df34=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+4') ]
df35=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+5') ]
df36=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+6') ]
df41=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+1') ]
df42=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+2') ]
df43=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+3') ]
df44=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+4') ]
df45=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+5') ]
df46=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+6') ]
frames2 = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]
mt= pd.concat(frames)
mt



drug_name  default       ks1       ks2       ks3  \
12    Etoposide+Gemcitabine+1        0 -0.639170 -0.144250  0.148430   
14    Etoposide+Gemcitabine+2        0 -0.565830 -0.148970 -0.173080   
16    Etoposide+Gemcitabine+3        0 -0.535830  0.097875 -0.143150   
18    Etoposide+Gemcitabine+4        0 -0.459460  0.090733 -0.140140   
20    Etoposide+Gemcitabine+5        0 -0.098333 -0.079680 -0.120000   
22    Etoposide+Gemcitabine+6        0 -0.056667 -0.030110  0.025658   
72    Gemcitabine+Etoposide+1        0 -0.690830 -0.072245  0.192740   
74    Gemcitabine+Etoposide+2        0 -0.644170 -0.170130  0.119350   
76    Gemcitabine+Etoposide+3        0 -0.515000 -0.122820  0.123830   
78    Gemcitabine+Etoposide+4        0  0.019287 -0.145030 -0.192740   
80    Gemcitabine+Etoposide+5        0  0.087826 -0.167370 -0.172580   
82    Gemcitabine+Etoposide+6        0  0.046287 -0.124100 -0.127340   
0       Etoposide+Etoposide+1        0 -0.658330 -0.151980 -0.133790   
2       Etoposide+Etoposide+2        0 -0.596670 -0.183410 -0.224890   
4       Etoposide+Etoposide+3        0 -0.507540  0.080714 -0.125940   
6       Etoposide+Etoposide+4        0 -0.053269 -0.097863 -0.140810   
8       Etoposide+Etoposide+5        0  0.038568 -0.070623 -0.084830   
10      Etoposide+Etoposide+6        0 -0.021682 -0.073558 -0.087733   
84  Gemcitabine+Gemcitabine+1        0 -0.577500 -0.105360  0.197020   
86  Gemcitabine+Gemcitabine+2        0 -0.550000 -0.147800  0.190130   
88  Gemcitabine+Gemcitabine+3        0 -0.567500 -0.097928  0.175350   
90  Gemcitabine+Gemcitabine+4        0 -0.418330  0.067900 -0.145000   
92  Gemcitabine+Gemcitabine+5        0 -0.086594 -0.154860 -0.197830   
94  Gemcitabine+Gemcitabine+6        0  0.062926 -0.086938 -0.063973   

         ks4       ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12 -0.206640 -0.365490 -0.116250  0.160770  0.205180  ...  0.247910  0.142580   
14 -0.251080 -0.377400 -0.185960 -0.166540 -0.149940  ...  0.235990  0.189400   
16 -0.098313 -0.125500 -0.143980 -0.158160 -0.148350  ...  0.278330  0.256040   
18 -0.069508 -0.167160 -0.150810 -0.136360 -0.125550  ...  0.233550  0.226280   
20 -0.084225 -0.170440 -0.116250 -0.111180 -0.106920  ...  0.057003  0.043050   
22 -0.061638 -0.047487  0.029334  0.035004  0.038447  ... -0.021942  0.024703   
72 -0.173770 -0.333780  0.063140  0.226760  0.267730  ...  0.181340  0.121490   
74 -0.200000 -0.381920 -0.115790  0.153420  0.204870  ...  0.208230  0.145430   
76 -0.201090 -0.403390 -0.116680  0.145850  0.198010  ...  0.166140  0.111680   
78 -0.111530 -0.278820 -0.193440 -0.168010 -0.159800  ... -0.075304 -0.036240   
80 -0.098315 -0.294110 -0.173290 -0.144740 -0.138530  ... -0.109910  0.026654   
82 -0.088924 -0.230600 -0.126990 -0.107180 -0.095707  ... -0.087753 -0.039599   
0  -0.228720 -0.421970 -0.130760  0.161730  0.208450  ...  0.232730  0.096027   
2  -0.310260 -0.445170 -0.227970 -0.190090 -0.174000  ...  0.220820  0.146930   
4   0.104190 -0.129000 -0.133430 -0.130930 -0.134840  ...  0.299920  0.118720   
6  -0.122950 -0.187030 -0.133820 -0.118800 -0.111940  ... -0.037030  0.022158   
8  -0.055402 -0.134990 -0.088421 -0.069816 -0.063219  ... -0.065165  0.025711   
10 -0.079325 -0.128700 -0.096127 -0.071604 -0.062475  ... -0.037668 -0.027406   
84 -0.168100 -0.319050  0.068571  0.231790  0.267980  ...  0.115600  0.153210   
86 -0.239410 -0.402250 -0.110940  0.227700  0.269670  ...  0.163910  0.109200   
88 -0.199960 -0.304410 -0.101320  0.185030  0.226570  ...  0.138680  0.137460   
90 -0.118180 -0.190180 -0.141560 -0.137320 -0.126020  ...  0.196990  0.196180   
92 -0.135800 -0.295870 -0.196300 -0.166920 -0.165830  ... -0.073804  0.028551   
94 -0.070039 -0.167980 -0.071415 -0.042771 -0.042655  ... -0.089477 -0.042016   

       ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12 -0.400640  0.383250  0.333460  0.142580 -0.582600 -0.645280 -0.255230   
14 -0.425990  0.397740  0.312770  0.18940

In [10]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames3=[]
for i in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+AUY922+'+str(i)) ])
for j in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+17AAG+'+str(j)) ])
for k in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+AUY922+'+str(k)) ])
for m in range(1,7):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+17AAG+'+str(m)) ])
HSP= pd.concat(frames3)
HSP


drug_name  default       ks1       ks2       ks3       ks4  \
397   17AAG+AUY922+1        0 -0.674170 -0.165250  0.200230 -0.264110   
399   17AAG+AUY922+2        0 -0.700830 -0.147950  0.164460 -0.306230   
401   17AAG+AUY922+3        0 -0.711670 -0.172910  0.209390 -0.305160   
403   17AAG+AUY922+4        0 -0.385830 -0.076059 -0.110900 -0.101530   
405   17AAG+AUY922+5        0 -0.035735 -0.068093 -0.095508 -0.068125   
407   17AAG+AUY922+6        0  0.034927  0.029695  0.040069 -0.022628   
457   AUY922+17AAG+1        0 -0.546670 -0.103750  0.143520 -0.217090   
459   AUY922+17AAG+2        0 -0.534170 -0.105630 -0.166570 -0.214090   
461   AUY922+17AAG+3        0 -0.500000  0.089967 -0.169070 -0.131880   
463   AUY922+17AAG+4        0 -0.488510  0.117650 -0.116610  0.067337   
465   AUY922+17AAG+5        0  0.103470 -0.141110 -0.147490 -0.090191   
467   AUY922+17AAG+6        0  0.078576 -0.121490 -0.154390  0.057324   
469  AUY922+AUY922+1        0 -0.627500 -0.100820  0.278970 -0.201220   
471  AUY922+AUY922+2        0 -0.625830 -0.128380  0.193910 -0.258700   
473  AUY922+AUY922+3        0 -0.570830 -0.173100 -0.154870 -0.309510   
475  AUY922+AUY922+4        0 -0.480000  0.096645 -0.134630 -0.131010   
477  AUY922+AUY922+5        0 -0.111090 -0.119700 -0.193500 -0.131400   
479  AUY922+AUY922+6        0  0.077260 -0.065729 -0.067111 -0.107860   
385    17AAG+17AAG+1        0 -0.630000 -0.178550  0.150480 -0.300570   
387    17AAG+17AAG+2        0 -0.601670 -0.144300 -0.164650 -0.283210   
389    17AAG+17AAG+3        0 -0.444170  0.069580 -0.140730 -0.064966   
391    17AAG+17AAG+4        0  0.061841 -0.167950 -0.190900 -0.183980   
393    17AAG+17AAG+5        0  0.019024 -0.070078 -0.085918 -0.101700   
395    17AAG+17AAG+6        0 -0.043149 -0.074153 -0.102210 -0.055896   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
397 -0.360210  0.080297  0.233460  0.273340  ...  0.194160  0.150090   
399 -0.410260 -0.143580  0.182530  0.231010  ...  0.260780  0.144160   
401 -0.407760 -0.132470  0.234060  0.264910  ...  0.224340  0.120910   
403 -0.140170 -0.112720 -0.121420 -0.106850  ...  0.195070  0.121020   
405 -0.092885 -0.099710 -0.097177 -0.088020  ...  0.049356 -0.061358   
407  0.039578  0.036269  0.030207  0.031801  ...  0.029750 -0.064527   
457 -0.367850 -0.124090  0.175090  0.210830  ...  0.213960  0.168560   
459 -0.300690 -0.187910 -0.175280 -0.146890  ...  0.281640  0.153210   
461 -0.174120 -0.164440 -0.159540 -0.144480  ...  0.309000  0.183740   
463 -0.167390 -0.128630 -0.111070 -0.102890  ...  0.260980  0.249830   
465 -0.207450 -0.154570 -0.133400 -0.119800  ... -0.111550 -0.034668   
467 -0.230240 -0.165680 -0.141750 -0.125250  ... -0.097280 -0.056917   
469 -0.332010  0.134990  0.296720  0.348100  ...  0.152970  0.154600   
471 -0.322990 -0.089658  0.216000  0.263310  ...  0.247240  0.117780   
473 -0.499800 -0.180530  0.160800  0.221650  ...  0.183690  0.125750   
475 -0.144580 -0.139840 -0.146700 -0.136710  ...  0.233660  0.289440   
477 -0.215590 -0.186440 -0.182420 -0.174890  ...  0.048307 -0.036060   
479 -0.056747 -0.062081 -0.074421 -0.063658  ... -0.062735 -0.046472   
385 -0.389470 -0.146400  0.178880  0.228610  ...  0.222770  0.162170   
387 -0.358190 -0.210870 -0.164890  0.157050  ...  0.277410  0.164270   
389 -0.127770 -0.158230 -0.149290 -0.132510  ...  0.272500  0.127560   
391 -0.219550 -0.191940 -0.185870 -0.167400  ... -0.077980 -0.031057   
393 -0.077878 -0.087723 -0.086992 -0.073214  ... -0.027454 -0.046287   
395 -0.127040 -0.109260 -0.099949 -0.087387  ...  0.057151 -0.034294   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
397 -0.245180  0.309580  0.269810  0.150090 -0.643760 -0.616310 -0.296550   
399 -0.337270  0.367270  0.306300  0.144160 -0.568830 -0.611730 -0.276100   
401 -0.339780  0.301420  0.248450  0.120910 -0.576480 -0.609080 -0.243950   
403 -0.129360  0.308130  0.278850  0.121020 -0.327970 -0.362930 -0.205540   

In [11]:
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin

frames4=[]
for i in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+PS341+'+str(i)) ])
for j in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+MG132+'+str(j)) ])
for k in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='MG132+MG132+'+str(k)) ])
for m in range(1,7):
    frames4.append(df.loc[(df['drug_name'] =='PS341+PS341+'+str(m)) ])
PROT= pd.concat(frames4)
PROT

drug_name  default       ks1       ks2       ks3       ks4       ks5  \
541  MG132+PS341+1        0 -0.891670  0.110950  0.301900 -0.279440  0.098135   
543  MG132+PS341+2        0 -0.517500  0.168780  0.193490 -0.111110  0.213560   
545  MG132+PS341+3        0 -0.303330  0.295650  0.338850  0.085449  0.390210   
547  MG132+PS341+4        0 -0.144900  0.113020  0.157820 -0.113800  0.057448   
549  MG132+PS341+5        0 -0.069596  0.039161  0.052463 -0.076390 -0.036266   
551  MG132+PS341+6        0  0.079233 -0.025412  0.053315 -0.070311  0.042623   
601  PS341+MG132+1        0 -0.975000  0.217530  0.492660 -0.372630 -0.289840   
603  PS341+MG132+2        0 -0.548360  0.118980  0.328470 -0.078737  0.172830   
605  PS341+MG132+3        0 -0.450000  0.314700  0.499940  0.082381  0.132200   
607  PS341+MG132+4        0 -0.290000  0.250700  0.321830  0.081790  0.160620   
609  PS341+MG132+5        0 -0.053163  0.029507  0.036718  0.050714  0.051684   
611  PS341+MG132+6        0  0.069282 -0.086974 -0.100470 -0.051279 -0.099086   
529  MG132+MG132+1        0 -0.920000  0.173770  0.315830 -0.161920  0.108220   
531  MG132+MG132+2        0 -0.420000  0.109610  0.148740 -0.056667  0.111750   
533  MG132+MG132+3        0 -0.208330  0.171060  0.166240 -0.099039 -0.034092   
535  MG132+MG132+4        0 -0.124780 -0.084102  0.132470 -0.108960  0.035755   
537  MG132+MG132+5        0 -0.072951 -0.038507  0.041875 -0.118020 -0.034618   
539  MG132+MG132+6        0  0.039511 -0.093682 -0.084746 -0.141690 -0.093560   
613  PS341+PS341+1        0 -0.970830  0.092143  0.280710 -0.187860 -0.192620   
615  PS341+PS341+2        0 -0.762500  0.120140  0.220000 -0.128190  0.060000   
617  PS341+PS341+3        0 -0.398130  0.287300  0.394770 -0.078121  0.382920   
619  PS341+PS341+4        0 -0.383200  0.285140  0.401850  0.069713  0.152230   
621  PS341+PS341+5        0 -0.103330 -0.027607 -0.028744 -0.062957  0.028274   
623  PS341+PS341+6        0  0.047283 -0.026824 -0.028787  0.060666 -0.043555   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
541  0.281070  0.294400  0.309760  ...  0.200480  0.147740 -0.115630   
543  0.220710  0.171860  0.177260  ...  0.094218  0.328100 -0.165050   
545  0.347480  0.297410  0.288930  ...  0.369560 -0.092352  0.068915   
547  0.154810  0.156140  0.165310  ...  0.130930 -0.045745  0.034401   
549  0.062042  0.047907  0.051863  ...  0.063351 -0.058697 -0.040620   
551  0.050622  0.048866  0.055388  ... -0.078986 -0.037343  0.020911   
601  0.432070  0.544090  0.619680  ...  0.184250 -0.152470  0.160190   
603  0.317740  0.321990  0.316160  ...  0.147120 -0.111680  0.146140   
605  0.413510  0.511010  0.542800  ...  0.144050 -0.110710  0.149230   
607  0.268470  0.313930  0.327710  ...  0.184780  0.049164 -0.031841   
609  0.039201  0.029201  0.027653  ...  0.081854 -0.090510  0.031633   
611 -0.100080 -0.093394 -0.089554  ... -0.072346 -0.047852  0.026047   
529  0.312320  0.299280  0.326850  ...  0.219750 -0.113700  0.171230   
531  0.168070  0.129890  0.118770  ...  0.074930  0.327750 -0.105960   
533  0.116150  0.193160  0.236690  ...  0.144110  0.041886  0.027709   
535  0.127120  0.138170  0.146800  ...  0.082371  0.042858 -0.057388   
537  0.039549  0.041076  0.056701  ...  0.069132 -0.045903 -0.040590   
539 -0.083728 -0.074773 -0.066714  ... -0.049065 -0.048474 -0.046049   
613  0.210120  0.332980  0.359880  ...  0.156900 -0.262620  0.226190   
615  0.238330  0.217220  0.221670  ...  0.188470 -0.110970  0.121110   
617  0.418140  0.360310  0.349280  ...  0.311430 -0.136360  0.026532   
619  0.341450  0.387470  0.403920  ...  0.181350  0.073040 -0.024058   
621 -0.033035 -0.033879 -0.028164  ...  0.081840 -0.053869 -0.031493   
623 -0.033135 -0.033467 -0.027157  ... -0.032332 -0.040681 -0.022185   

        ks232     ks233     ks234     ks235     ks236     ks237     ks238  
541  0.236270  0.220440  0.147740 -0.447860 -0.377020 -0.226150  0.167220  
543  0.420530  0.345920  0.328

In [12]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames5=[]
for i in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+Apicidin+'+str(i)) ])
for j in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+SAHA+'+str(j)) ])
for k in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+Apicidin+'+str(k)) ])
for m in range(1,7):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+SAHA+'+str(m)) ])
HDAC= pd.concat(frames5)
HDAC

drug_name  default       ks1       ks2       ks3       ks4  \
672      SAHA+Apicidin+1        0 -0.483470  0.378410  0.507380  0.054191   
674      SAHA+Apicidin+2        0 -0.415000  0.434060  0.498840  0.145890   
676      SAHA+Apicidin+3        0 -0.021667  0.356350  0.410930  0.124640   
678      SAHA+Apicidin+4        0 -0.067095  0.121050  0.109130  0.179530   
680      SAHA+Apicidin+5        0 -0.105770 -0.024704 -0.072792  0.083621   
682      SAHA+Apicidin+6        0  0.033385 -0.046291 -0.067642  0.076785   
289      Apicidin+SAHA+1        0 -0.590000  0.403760  0.528880  0.070518   
291      Apicidin+SAHA+2        0 -0.430830  0.515260  0.594430  0.113280   
293      Apicidin+SAHA+3        0  0.072443  0.324550  0.402210  0.102980   
295      Apicidin+SAHA+4        0  0.058409  0.086580  0.145730  0.069141   
297      Apicidin+SAHA+5        0 -0.030833 -0.020203  0.063110 -0.039417   
299      Apicidin+SAHA+6        0  0.049460 -0.053651 -0.042118 -0.044433   
673  Apicidin+Apicidin+1        0 -0.607500  0.422640  0.530900  0.097063   
675  Apicidin+Apicidin+2        0 -0.374170  0.467510  0.554460  0.104690   
677  Apicidin+Apicidin+3        0 -0.078879  0.340940  0.409950  0.144220   
679  Apicidin+Apicidin+4        0  0.020777  0.132380  0.121070  0.160830   
681  Apicidin+Apicidin+5        0 -0.066264  0.052155  0.036121  0.117100   
683  Apicidin+Apicidin+6        0  0.026089 -0.082388 -0.147870  0.099931   
288          SAHA+SAHA+1        0 -0.566670  0.438030  0.550750 -0.059810   
290          SAHA+SAHA+2        0 -0.400830  0.453910  0.541630  0.080766   
292          SAHA+SAHA+3        0 -0.027500  0.344000  0.405700  0.094734   
294          SAHA+SAHA+4        0  0.058409  0.122910  0.206910  0.051181   
296          SAHA+SAHA+5        0 -0.032444  0.030642  0.020422  0.042036   
298          SAHA+SAHA+6        0 -0.037423 -0.058404 -0.044503 -0.062743   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
672  0.309380  0.496270  0.493420  0.488420  ...  0.204440  0.236390   
674  0.382940  0.471850  0.483930  0.474400  ...  0.324860  0.189350   
676  0.440360  0.413760  0.377510  0.367060  ...  0.098529 -0.054964   
678  0.125080  0.097586  0.097511  0.101550  ...  0.097934 -0.068645   
680 -0.077803 -0.078574 -0.072374 -0.065043  ...  0.088531 -0.040063   
682 -0.104490 -0.066556 -0.060004 -0.050636  ... -0.036501 -0.044210   
289  0.282550  0.503800  0.547050  0.535440  ...  0.157880  0.251990   
291  0.476670  0.582180  0.587270  0.582360  ...  0.322930  0.186260   
293  0.395130  0.387780  0.382380  0.378520  ...  0.057739 -0.066992   
295  0.141870  0.147640  0.130650  0.130870  ... -0.039272 -0.053431   
297  0.049413  0.066406  0.062899  0.065365  ... -0.051345  0.026422   
299 -0.084437 -0.050467 -0.034464 -0.033721  ... -0.082965 -0.038377   
673  0.321690  0.508580  0.523850  0.514040  ...  0.197350  0.226690   
675  0.434370  0.545750  0.530580  0.518560  ...  0.343130  0.142720   
677  0.438490  0.403460  0.381310  0.373190  ...  0.147160 -0.081721   
679  0.144290  0.119190  0.120040  0.126400  ...  0.065990 -0.075789   
681  0.045029  0.038908  0.046322  0.046092  ...  0.061983 -0.040805   
683 -0.168590 -0.163880 -0.136340 -0.119950  ... -0.034673 -0.065980   
288  0.309010  0.538490  0.554360  0.557370  ...  0.145700  0.245320   
290  0.392600  0.521220  0.523850  0.521880  ...  0.276140  0.146990   
292  0.412200  0.393270  0.389870  0.381490  ...  0.099992 -0.054705   
294  0.177520  0.198690  0.195540  0.188580  ... -0.029757 -0.055261   
296 -0.020363  0.021656  0.027619  0.027713  ... -0.032298 -0.038075   
298 -0.058652 -0.037050 -0.032443 -0.033832  ... -0.017008 -0.029015   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
672 -0.289110  0.380580  0.328690  0.236390 -0.327600 -0.362680 -0.197870   
674 -0.174450  0.475740  0.455210  0.189350 -0.369090 -0.377870 -0.103480   
676  0.058282  0.091017  0.108830 -0.054964  0.175570  0.

In [13]:
#Dna ： etoposide，Gemcitabine
#hsp：17aag，auy922
#mt：paclitaxel，Vinblastine
#prot："MG132"，ps341
#hdac：saha，apicidin

frames6=[]
for i in range(1,7):
    frames6.append(df.loc[(df['drug_name'] =='DMSO+DMSO+'+str(i)) ])

DMSO= pd.concat(frames6)
DMSO
#len(DMSO)


drug_name  default       ks1       ks2       ks3       ks4       ks5  \
360  DMSO+DMSO+1        0 -0.045833  0.045630  0.069729  0.032458  0.046111   
361  DMSO+DMSO+1        0 -0.030833 -0.023131 -0.031360  0.062452 -0.053954   
372  DMSO+DMSO+1        0  0.073695  0.029093  0.060841 -0.051401  0.045579   
373  DMSO+DMSO+1        0  0.054498 -0.058508 -0.051640  0.054882 -0.083751   
744  DMSO+DMSO+1        0  0.029236  0.068853  0.090612 -0.056395  0.128060   
745  DMSO+DMSO+1        0  0.094064  0.033183  0.045444  0.036417  0.050826   
756  DMSO+DMSO+1        0 -0.055592 -0.037596 -0.074126  0.073131 -0.062658   
757  DMSO+DMSO+1        0  0.039511 -0.027140  0.037520 -0.073599  0.023893   
362  DMSO+DMSO+2        0 -0.023333  0.045120  0.054200  0.039305  0.060897   
363  DMSO+DMSO+2        0  0.069926  0.024255  0.063075  0.054632  0.043439   
374  DMSO+DMSO+2        0  0.018606  0.028958  0.041390  0.026484 -0.042806   
375  DMSO+DMSO+2        0 -0.076667  0.033630  0.035200 -0.065921  0.035431   
746  DMSO+DMSO+2        0 -0.056405 -0.024389 -0.042762  0.047312 -0.032773   
747  DMSO+DMSO+2        0  0.071958  0.057600  0.050552  0.131620  0.051325   
758  DMSO+DMSO+2        0 -0.032087 -0.027087 -0.038807  0.105020 -0.035720   
759  DMSO+DMSO+2        0  0.036972 -0.032795 -0.037089  0.080217 -0.029010   
364  DMSO+DMSO+3        0 -0.028333  0.027500  0.045833 -0.019167  0.055833   
365  DMSO+DMSO+3        0 -0.153120 -0.056478 -0.289820  0.260850 -0.379400   
376  DMSO+DMSO+3        0 -0.056667  0.033979  0.080593 -0.061445  0.048790   
377  DMSO+DMSO+3        0 -0.030000 -0.038507 -0.024825 -0.084936 -0.036916   
748  DMSO+DMSO+3        0 -0.064607  0.032506 -0.049825  0.057344 -0.049680   
749  DMSO+DMSO+3        0  0.050093 -0.029630 -0.036358  0.018241  0.028395   
760  DMSO+DMSO+3        0 -0.040912 -0.037584 -0.086443  0.070179 -0.089379   
761  DMSO+DMSO+3        0 -0.049171  0.051818  0.039541 -0.026366  0.079148   
366  DMSO+DMSO+4        0  0.029373  0.034538  0.054697 -0.055866  0.043778   
367  DMSO+DMSO+4        0 -0.023333  0.031522  0.055250  0.031131  0.062378   
378  DMSO+DMSO+4        0 -0.084788 -0.039664 -0.042280 -0.064268 -0.041899   
379  DMSO+DMSO+4        0 -0.084788  0.061762  0.042738 -0.051412  0.025873   
750  DMSO+DMSO+4        0 -0.086608  0.037805 -0.057019  0.076620 -0.045129   
751  DMSO+DMSO+4        0  0.069282 -0.037465 -0.046289  0.042331 -0.043263   
762  DMSO+DMSO+4        0 -0.035735  0.031032  0.053588 -0.037182  0.046151   
763  DMSO+DMSO+4        0 -0.050746  0.034945  0.043244  0.056416  0.058554   
368  DMSO+DMSO+5        0  0.099136 -0.056353  0.023986 -0.023674 -0.047861   
369  DMSO+DMSO+5        0  0.020646  0.043503  0.060578  0.036344  0.061037   
380  DMSO+DMSO+5        0 -0.034098  0.030928  0.057626 -0.057777  0.039000   
381  DMSO+DMSO+5        0 -0.076667  0.047676  0.061718 -0.062250  0.073749   
752  DMSO+DMSO+5        0 -0.080586 -0.021371 -0.048900  0.044969  0.029567   
753  DMSO+DMSO+5        0 -0.018382 -0.036100  0.021561 -0.080307  0.033277   
764  DMSO+DMSO+5        0 -0.046150 -0.042004 -0.035158  0.032152  0.024188   
765  DMSO+DMSO+5        0 -0.062955  0.043926  0.044278 -0.032397  0.061400   
370  DMSO+DMSO+6        0  0.118480 -0.052185 -0.023870  0.015962 -0.051530   
371  DMSO+DMSO+6        0  0.040511  0.025139  0.041982  0.043357  0.058772   
382  DMSO+DMSO+6        0 -0.156060  0.064540  0.057057 -0.039832  0.043153   
383  DMSO+DMSO+6        0 -0.129050  0.078132  0.097199 -0.068729  0.096897   
754  DMSO+DMSO+6        0 -0.034270 -0.046098 -0.097904  0.034439 -0.085415   
755  DMSO+DMSO+6        0  0.019024  0.023192  0.029223 -0.034336  0.032044   
766  DMSO+DMSO+6        0 -0.030833  0.077126  0.073685 -0.074497  0.120190   
767  DMSO+DMSO+6        0 -0.043897  0.060833  0.078476 -0.077643  0.127950   

          ks6       ks7       ks8  ...     ks229     ks230     ks231  \
360  0.066633  0.065636  0.065471  ...  0.046291 -0.051054  0.0

In [14]:
combi=frames+frames2+frames3+frames4+frames5+frames6
training= pd.concat(combi)
print(training)
print(len(training))



                   drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.639170 -0.144250  0.148430 -0.206640   
14   Etoposide+Gemcitabine+2        0 -0.565830 -0.148970 -0.173080 -0.251080   
16   Etoposide+Gemcitabine+3        0 -0.535830  0.097875 -0.143150 -0.098313   
18   Etoposide+Gemcitabine+4        0 -0.459460  0.090733 -0.140140 -0.069508   
20   Etoposide+Gemcitabine+5        0 -0.098333 -0.079680 -0.120000 -0.084225   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.129050  0.078132  0.097199 -0.068729   
754              DMSO+DMSO+6        0 -0.034270 -0.046098 -0.097904  0.034439   
755              DMSO+DMSO+6        0  0.019024  0.023192  0.029223 -0.034336   
766              DMSO+DMSO+6        0 -0.030833  0.077126  0.073685 -0.074497   
767              DMSO+DMSO+6        0 -0.043897  0.060833  0.078476 -0.077643   

          ks5       ks6    

In [15]:
#lda model
#just sample
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin
from sklearn.datasets import make_classification
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X_drug=training.iloc[:, 3:240].values

y=[]
for i in range(24):
    y.append('DNA')
for j in range(24):
    y.append('MT')
for k in range(24):
    y.append('HSP')
for m in range(24):
    y.append('PROT')
for n in range(24):
    y.append('HDAC')
for k in range(48):
    y.append('DMSO')
print(len(X_drug[0]))
model = LinearDiscriminantAnalysis(n_components=4)
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
#reduce dimension for the data
X_drug2=model.fit(X_drug,y).transform(X_drug)
X_drug2
print(len(X_drug2[0]))



237
4


In [16]:
print(len(X_drug2))
print(X_drug2[-1])

168
[-7.76042984  0.36734649  2.24034194  0.14574942]


In [17]:
#wipe out those whose concentration is not valid
def get_centroid(point_lst):
    x_sum=0
    y_sum=0
    z1_sum=0
    z2_sum=0
    z3_sum=0
    z4_sum=0


    for i in range(len(point_lst)):
        x_sum+=point_lst[i][0]
        y_sum+=point_lst[i][1]
        z1_sum+=point_lst[i][2]
        z2_sum+=point_lst[i][3]
        #z3_sum+=point_lst[i][4]
        #z4_sum+=point_lst[i][5]


    x_mean=x_sum/len(point_lst)
    y_mean=y_sum/len(point_lst)
    z1_mean=z1_sum/len(point_lst)
    z2_mean=z2_sum/len(point_lst)
    #z3_mean=z3_sum/len(point_lst)
    #z4_mean=z4_sum/len(point_lst)
    centroid=[]
    centroid.append(x_mean)
    centroid.append(y_mean)
    centroid.append(z1_mean)
    centroid.append(z2_mean)
    #centroid.append(z3_mean)
    #centroid.append(z4_mean)
    #centroid.append(point_lst[0][-1])
    return centroid



In [18]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                 8.135686              -0.599061               4.272090   
1                 7.101879              -0.244859               3.572983   
2                 7.525829               0.710095               3.693703   
3                 8.585531               0.720823               3.113446   
4                 7.585193               0.148029               1.611679   
..                     ...                    ...                    ...   
163             -10.047273               0.738590               1.147129   
164              -9.281311              -0.066942               1.446367   
165              -7.078092              -0.233108              -0.703078   
166              -8.580074               0.103565               2.372221   
167              -7.760430               0.367346               2.240342   

     principal component 4  
0                 3.963843  
1                 5.052534  
2                 4.943005  
3                 4.579971  
4                 3.094811  
..                     ...  
163               0.291324  
164               0.117489  
165               0.737991  
166               1.109327  
167               0.145749  

[168 rows x 4 columns]

In [19]:
#predict
#still sample but useful this block 
#model2 = LinearDiscriminantAnalysis(n_components=1)
#model2.fit(X_drug2,y)
#row=X_drug2
#yhat = model2.predict(row)
# summarize prediction
#print('Predicted Class: %s' % yhat)



In [20]:
all_list=[]

for i in range(len(X_drug2)):
    all_list.append(X_drug2[i])
print(len(all_list))
all_list[120:127]

168


[array([-8.44475753,  0.69777021,  0.14718422,  1.20461533]),
 array([-8.16955335,  0.03455641, -0.02232433,  2.84538975]),
 array([-10.60616222,   1.35158342,  -0.32391184,   1.25223833]),
 array([-10.71859732,   1.02370548,   0.23004521,   2.09975572]),
 array([-8.71750625, -0.03450073, -0.59825725,  0.12076088]),
 array([-7.94307062,  0.19955846, -0.29191142,  2.12436769]),
 array([-10.19784033,   0.60362364,   0.78651069,   2.16329733])]

In [21]:
X_training=[]
X_testing=[]
#X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]+all_list[120]
X_training=all_list[6:24]+all_list[30:48]+all_list[54:72]+all_list[78:96]+all_list[102:120]
for i in range(120,168,8):
    X_training+=all_list[i:i+7]

X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
for j in range(120,168,8):
    X_testing.append(all_list[j])
    print(all_list[j])

#X_testing=all_list[:6]+all_list[24:30]+all_list[48:54]+all_list[72:78]+all_list[96:102]
#X_testing.append()
print(len(X_training))
print(len(X_testing))
y=[]
for i in range(18):
    y.append('DNA')
for j in range(18):
    y.append("MT")
for k in range(18):
    y.append("HSP")
for m in range(18):
    y.append("PROT")
for n in range(18):
    y.append("HDAC")
for k in range(42):
    y.append("DMSO")


[-8.44475753  0.69777021  0.14718422  1.20461533]
[-9.40861161 -1.14318543  1.75997853  0.48901212]
[-8.37643631 -1.16760447  1.75116539  2.59154374]
[-7.98631609 -0.45757837  1.4019414   2.21909852]
[-9.83535496  2.05079095  2.18185101  0.03352737]
[-8.64970946 -0.76261078  2.34530919  1.73220609]
132
36


In [22]:

dmso_lst2=[]
for i in range(48):
    dmso_lst2.append(all_list[i+120])
print(len(dmso_lst2))
cen_dmso=get_centroid(dmso_lst2)
print(cen_dmso)


48
[-8.910713388740216, -0.19411075928510704, 1.3867797857932018, 0.7811564080471373]


In [23]:
#calculating the distance
from math import sqrt
def euclidean_distance(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(len(row1)-1):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [24]:
dist_lst=[]
for i in range(len(dmso_lst2)):
    dist_lst.append(euclidean_distance(dmso_lst2[i],cen_dmso))
dist_lst.sort()
print(len(dist_lst))
max_ave=sum(dist_lst[-5:-1])/len(dist_lst[-5:-1])
max_ave
max_ave*=2
max_ave


48


6.236302372344532

In [25]:
#selecting data
effect=[]
dist_lst2=[]
for i in range(120):
    selection_dist=euclidean_distance(all_list[i],cen_dmso)
    dist_lst2.append(selection_dist)
dist_lst2.sort()
print(dist_lst2[0])

10.285422365725097


In [26]:
model2 = LinearDiscriminantAnalysis(n_components=4)
model2.fit(X_training,y)
yhat2=model2.predict(X_testing)

print(yhat2)
print(len(yhat2))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [27]:
def accuracy(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(int(length/6.0)):
        list3.append(list2[0])
    for j in range(int(length/6.0)):
        list3.append(list2[1])
    for m in range(int(length/6.0)):
        list3.append(list2[2])
    for n in range(int(length/6.0)):
        list3.append(list2[3])
    for k in range(int(length/6.0)):
        list3.append(list2[4])
    for k in range(int(length/6.0)):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [28]:
#test accuracy
'%.2f%%' % ((accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))*100)


'100.00%'

In [29]:
training["drug_name"]
train_drug_name_without_concentration=[]
for each in training['drug_name']:
    train_drug_name_without_concentration.append(each[:-2])
    #print(training["drug_name"][i][0:-1])
    

train_drug_name_without_concentration
train_drug_name_without_concentration2=[]
#dna,mt,hsp,prot,hdac
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('DNA')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('MT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HSP')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('PROT')
for i in range(int((len(train_drug_name_without_concentration)-48)/5.0)):
    train_drug_name_without_concentration2.append('HDAC')
for i in range(48):
    train_drug_name_without_concentration2.append("DMSO")

train_drug_name_without_concentration2   


['DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'DNA',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'MT',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'HSP',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'PROT',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'HDAC',
 'DMSO',
 'DMSO'

In [30]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append('DMSO')
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=train_drug_name_without_concentration2)
#training['drug_name']
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [31]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(24):
    y2.append('DNA')
for j in range(24):
    y2.append('MT')
for k in range(24):
    y2.append('HSP')
for m in range(24):
    y2.append('PROT')
for n in range(24):
    y2.append('HDAC')
for k in range(48):
    y2.append("DMSO")
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug3=training.iloc[:,2:240].values
X_drug3=model.fit(X_drug3,y2).transform(X_drug3)
fig = px.scatter(X_drug3, x=0, y=1, color=training['drug_name'])
fig.show()
#these 5 groups are very clearly separated, as we can see in the image

In [32]:
# Create a function
def select_n_components(var_ratio, goal_var: float) -> int:
    # Set initial variance explained so far
    total_variance = 0.0
    
    # Set initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for explained_variance in var_ratio:
        
        # Add the explained variance to the total
        total_variance += explained_variance
        
        # Add one to the number of components
        n_components += 1
        
        # If we reach our goal level of explained variance
        if total_variance >= goal_var:
            # End the loop
            break
            
    # Return the number of components
    return n_components

In [33]:
lda = LinearDiscriminantAnalysis(n_components=None)
y5=[]
for i in range(18):
    y5.append('DNA')
for j in range(18):
    y5.append("MT")
for k in range(18):
    y5.append("HSP")
for m in range(18):
    y5.append("PROT")
for n in range(18):
    y5.append("HDAC")
for k in range(42):
    y5.append("DMSO")

X_lda=lda.fit(X_training,y5)


In [34]:
# Create array of explained variance ratios
lda_var_ratios = lda.explained_variance_ratio_
lda_var_ratios

array([0.47138848, 0.26083963, 0.16057942, 0.10719246])

In [35]:
# Run function
print(select_n_components(lda_var_ratios, 0.95))
print(select_n_components(lda_var_ratios, 0.85))
print(select_n_components(lda_var_ratios, 0.75))
print(select_n_components(lda_var_ratios, 0.65))
print(select_n_components(lda_var_ratios, 0.35))


4
3
3
2
1


In [36]:
#pca_drug = PCA(n_components=6)
#components = pca_drug.fit_transform(X_drug)
principalDf = pd.DataFrame(data = X_drug2
             , columns =['principal component 1', 'principal component 2','principal component 3','principal component 4'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                 8.135686              -0.599061               4.272090   
1                 7.101879              -0.244859               3.572983   
2                 7.525829               0.710095               3.693703   
3                 8.585531               0.720823               3.113446   
4                 7.585193               0.148029               1.611679   
..                     ...                    ...                    ...   
163             -10.047273               0.738590               1.147129   
164              -9.281311              -0.066942               1.446367   
165              -7.078092              -0.233108              -0.703078   
166              -8.580074               0.103565               2.372221   
167              -7.760430               0.367346               2.240342   

     principal component 4  
0                 3.963843  
1                 5.052534  
2                 4.943005  
3                 4.579971  
4                 3.094811  
..                     ...  
163               0.291324  
164               0.117489  
165               0.737991  
166               1.109327  
167               0.145749  

[168 rows x 4 columns]

In [37]:
training

drug_name  default       ks1       ks2       ks3       ks4  \
12   Etoposide+Gemcitabine+1        0 -0.639170 -0.144250  0.148430 -0.206640   
14   Etoposide+Gemcitabine+2        0 -0.565830 -0.148970 -0.173080 -0.251080   
16   Etoposide+Gemcitabine+3        0 -0.535830  0.097875 -0.143150 -0.098313   
18   Etoposide+Gemcitabine+4        0 -0.459460  0.090733 -0.140140 -0.069508   
20   Etoposide+Gemcitabine+5        0 -0.098333 -0.079680 -0.120000 -0.084225   
..                       ...      ...       ...       ...       ...       ...   
383              DMSO+DMSO+6        0 -0.129050  0.078132  0.097199 -0.068729   
754              DMSO+DMSO+6        0 -0.034270 -0.046098 -0.097904  0.034439   
755              DMSO+DMSO+6        0  0.019024  0.023192  0.029223 -0.034336   
766              DMSO+DMSO+6        0 -0.030833  0.077126  0.073685 -0.074497   
767              DMSO+DMSO+6        0 -0.043897  0.060833  0.078476 -0.077643   

          ks5       ks6       ks7       ks8  ...     ks229     ks230  \
12  -0.365490 -0.116250  0.160770  0.205180  ...  0.247910  0.142580   
14  -0.377400 -0.185960 -0.166540 -0.149940  ...  0.235990  0.189400   
16  -0.125500 -0.143980 -0.158160 -0.148350  ...  0.278330  0.256040   
18  -0.167160 -0.150810 -0.136360 -0.125550  ...  0.233550  0.226280   
20  -0.170440 -0.116250 -0.111180 -0.106920  ...  0.057003  0.043050   
..        ...       ...       ...       ...  ...       ...       ...   
383  0.096897  0.102080  0.093429  0.100230  ...  0.097303 -0.026349   
754 -0.085415 -0.097073 -0.092850 -0.082848  ...  0.032324 -0.039492   
755  0.032044  0.033690  0.022005  0.020924  ... -0.026061 -0.045560   
766  0.120190  0.088412  0.060566  0.061987  ...  0.047312  0.025392   
767  0.127950  0.091221  0.064554  0.068872  ...  0.066944 -0.058880   

        ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
12  -0.400640  0.383250  0.333460  0.142580 -0.582600 -0.645280 -0.255230   
14  -0.425990  0.397740  0.312770  0.189400 -0.506840 -0.601820 -0.194810   
16  -0.286360  0.501470  0.430570  0.256040 -0.341480 -0.440620 -0.227430   
18  -0.173630  0.437650  0.405720  0.226280 -0.291770 -0.360490 -0.117630   
20  -0.099577  0.082478  0.064693  0.043050 -0.115180 -0.164870 -0.083051   
..        ...       ...       ...       ...       ...       ...       ...   
383  0.047503  0.100560  0.102540 -0.026349 -0.098545 -0.087436 -0.028672   
754 -0.054502  0.027212  0.034754 -0.039492  0.023565 -0.032719 -0.018783   
755  0.022520 -0.030191 -0.029522 -0.045560 -0.022733  0.033174  0.031173   
766  0.050416  0.048214  0.050098  0.025392 -0.034964  0.035534  0.019352   
767  0.035480  0.047912  0.052508 -0.058880 -0.060345 -0.047938  0.052710   

        ks238  
12   0.406690  
14   0.441380  
16   0.318870  
18   0.212030  
20   0.098872  
..        ...  
383 -0.040644  
754  0.055371  
755 -0.021555  
766 -0.049585  
767 -0.036019  

[168 rows x 240 columns]

In [38]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn5 = KNeighborsClassifier(n_neighbors=20)
knn5.fit(X_training, y)
y_pred_5 = knn5.predict(X_testing)
print(y_pred_5)
print(accuracy(y_pred_5,['DNA',"MT","HSP","PROT","HDAC","DMSO"]))
#print("Accuracy with k=5", accuracy_score(y_test, y_pred_5)*100)

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
1.0


In [39]:
import numpy as np
all_list2=[]
for i in range(len(all_list)):
    all_list2.append(np.ndarray.tolist(all_list[i]))

print(len(all_list2))

168


In [40]:
#starts with bootstrap sampling
#24,24,24,24,24,48
#6,6,6,6,6,12


import random
def bootstrap(all_list):
    part1=all_list[:24]
    
    part2=all_list[24:48]
    part3=all_list[48:72]
    part4=all_list[72:96]
    part5=all_list[96:120]
    part6=all_list[120:168]

    testing_data=[]
    toremovelst=[]
    testing_data2=[]
    toremovelst2=[]
    testing_data3=[]
    toremovelst3=[]
    testing_data4=[]
    toremovelst4=[]
    testing_data5=[]
    toremovelst5=[]
    testing_data6=[]
    toremovelst6=[]
    #1
    
    
    toremoveindexlst=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst)):
        toremoveindex=toremoveindexlst[i]

        target=part1[toremoveindex]
        toremovelst.append(target)
        testing_data.append(target)
    
        
    for i in range(len(toremovelst)):
        part1.remove(toremovelst[i])
    #2
    toremoveindexlst2=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst2)):
        toremoveindex2=toremoveindexlst2[i]

        target2=part2[toremoveindex2]
        toremovelst2.append(target2)
        testing_data.append(target2)
    
        
    for i in range(len(toremovelst2)):
        part2.remove(toremovelst2[i])
    #3
    toremoveindexlst3=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst3)):
        toremoveindex3=toremoveindexlst3[i]

        target3=part3[toremoveindex3]
        toremovelst3.append(target3)
        testing_data.append(target3)

    for i in range(len(toremovelst3)):
        part3.remove(toremovelst3[i])
    #4
    toremoveindexlst4=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst4)):
        toremoveindex4=toremoveindexlst4[i]

        target4=part4[toremoveindex4]
        toremovelst4.append(target4)
        testing_data.append(target4)
        
    for i in range(len(toremovelst4)):
        part4.remove(toremovelst4[i])
    #5
    toremoveindexlst5=random.sample(range(24), 6)
    for i in range(len(toremoveindexlst5)):
        toremoveindex5=toremoveindexlst5[i]

        target5=part5[toremoveindex5]
        toremovelst5.append(target5)
        testing_data.append(target5)

    for i in range(len(toremovelst5)):
        part5.remove(toremovelst5[i])

    #6
    toremoveindexlst6=random.sample(range(48), 12)
    for i in range(len(toremoveindexlst6)):
        toremoveindex6=toremoveindexlst6[i]

        target6=part6[toremoveindex6]
        toremovelst6.append(target6)
        testing_data.append(target6)
    
        
    for i in range(len(toremovelst6)):
        part6.remove(toremovelst6[i])
    
    
        





        
    
    





    return part1,part2,part3,part4,part5,part6,testing_data



In [41]:
part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)



In [42]:
training_data=part1+part2+part3+part4+part5+part6
print(len(training_data),len(part6))
y6=[]
for i in range(18):
    y6.append('DNA')
for j in range(18):
    y6.append("MT")
for k in range(18):
    y6.append("HSP")
for m in range(18):
    y6.append("PROT")
for n in range(18):
    y6.append("HDAC")
for k in range(36):
    y6.append("DMSO")

126 36


In [43]:
model6 = LinearDiscriminantAnalysis(n_components=4)
model6.fit(training_data,y6)
yhat6=model6.predict(X_testing)

print(yhat6)
print(len(yhat6))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [44]:
def accuracy2(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(6):
        list3.append(list2[0])
    for j in range(6):
        list3.append(list2[1])
    for m in range(6):
        list3.append(list2[2])
    for n in range(6):
        list3.append(list2[3])
    for k in range(6):
        list3.append(list2[4])
    for k in range(12):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [45]:
a1=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


In [46]:
#bootstrap 

In [47]:
#just to predict, then we will know the effects of bootstrap sampling
accuracylst=[]
def bootstrap_predict_accuracy():
    part1,part2,part3,part4,part5,part6,testing_data=bootstrap(all_list2)
    training_data=part1+part2+part3+part4+part5+part6


    model6 = LinearDiscriminantAnalysis(n_components=4)
    model6.fit(training_data,y6)
    yhat6=model6.predict(X_testing)
    a=accuracy2(yhat6,["DNA","MT","HSP","PROT","HDAC","DMSO"])


    accuracylst.append(a)

for i in range(10):
    bootstrap_predict_accuracy()
ave_accuracy=sum(accuracylst)/len(accuracylst)

    

In [48]:
ave_accuracy

1.0