In [1]:
#a code block that deals with concentration and drug names
#we do not use this block for now.

import pandas as pd
f1 = pd.read_csv('B_ks2.csv')
f2 = pd.read_csv('C_ks2.csv')
f3=pd.read_csv('D_ks2.csv')
f4=pd.read_csv('E_ks2.csv')
f5=pd.read_csv('A_ks2.csv')
file = [f1,f2,f3,f5]
train = pd.concat(file,axis=1)
train.to_csv("train.csv", index=0, sep=',')


In [2]:
#do some further processing with "A" because there are some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('A_ks2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('modified_A.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                


-0.294442


In [3]:
#test file A
import pandas as pd
df_A=pd.read_csv("A_ks2.csv")
df_A.shape
#df_A2=pd.read_csv("A_modified.csv")
#df_A2.shape


(1535, 239)

In [4]:
#a block that is used to concate the drug names(drug combinations and related concentration)

import csv
res_list=[]
with open('train.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        data=[]
        data.append(row[0]+'+'+row[1]+"+"+row[2])
        res_list.append(data)

        
        
with open('concatenated.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerows(res_list)

In [5]:
#a block that is used to concate concentration and ks numbers.
import pandas as pd
f1 = pd.read_csv('concatenated.csv')
#f2 = pd.read_csv('C.csv')
f3=pd.read_csv('D_ks2.csv')
f4=pd.read_csv('E_ks2.csv')
f5=pd.read_csv('modified_A.csv')
file = [f1,f5]
train = pd.concat(file,axis=1)
train.to_csv("train3.csv", index=0, sep=',')

In [6]:
#a block that sets the fields for the drug data
import csv
fields=['drug_name','default']
for i in range(1,239):
    fields.append('ks'+str(i))
rows=[]
with open('train3.csv', 'r') as file:
    reader = csv.reader(file)
    
    for row in reader:
        rows.append(row)

        
        
with open('drug_withfields2.csv', 'w') as file2:
    writer = csv.writer(file2)
    writer.writerow(fields)
    writer.writerows(rows)

In [7]:
#do some further processing with "drug_withfields" because there are still some data error in it
def remove_extradots(string):
    counter=0
    lst=[]
    for i in range(len(string)):
        if string[i]=='.' and counter<1 :
            lst.append(string[i])
            counter+=1
        elif string[i]!='.':
            lst.append(string[i])
    res="".join(lst)
    return res



import csv
res_list=[]
print(remove_extradots("-0.29444.2"))
with open('drug_withfields2.csv') as file2:
    reader=csv.reader(file2)

    for row in reader:
        data=[]
        for i in range(len(row)):
            
            data.append(remove_extradots(row[i]))
        res_list.append(data)
    


with open('drug_with_fields.csv', 'w') as file3:
    writer = csv.writer(file3)
    writer.writerows(res_list)
file3.close()
                

-0.294442


In [8]:
#we take etoposide and palitaxel out. 
df=pd.read_csv('drug_with_fields.csv')
df11=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]
df13=df.loc[(df['drug_name'] =='Etoposide+Etoposide+3') ]
df14=df.loc[(df['drug_name'] =='Etoposide+Etoposide+4') ]
df15=df.loc[(df['drug_name'] =='Etoposide+Etoposide+5') ]
df16=df.loc[(df['drug_name'] =='Etoposide+Etoposide+6') ]
df21=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]
df23=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+3') ]
df24=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+4') ]
df25=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+5') ]
df26=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+6') ]
df31=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+1')]
df32=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+2')]
df33=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+3')]
df34=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+4')]
df35=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+5')]
df36=df.loc[(df['drug_name'] =='Etoposide+Paclitaxel+6')]
df41=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+1') ]
df42=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+2') ]
df43=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+3') ]
df44=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+4') ]
df45=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+5') ]
df46=df.loc[(df['drug_name'] =='Paclitaxel+Etoposide+6') ]
#df51=df.loc[(df['drug_name'] =='DMSO+DMSO+1') ]
#df52=df.loc[(df['drug_name'] =='DMSO+DMSO+2') ]
##df53=df.loc[(df['drug_name'] =='DMSO+DMSO+3') ]
#df54=df.loc[(df['drug_name'] =='DMSO+DMSO+4') ]
#df55=df.loc[(df['drug_name'] =='DMSO+DMSO+5') ]
#df56=df.loc[(df['drug_name'] =='DMSO+DMSO+6') ]


frames = [df11, df12,df13,df14,df15,df16,df21,df22,df23,df24,df25,df26,df31,df32,df33,df34,df35,df36,df41,df42,df43,df44,df45,df46]

e_and_p = pd.concat(frames)
#etoposide and paclitaxel combination. 
e_and_p


drug_name  default      ks1       ks2       ks3       ks4  \
1260   Etoposide+Etoposide+1        0 -0.87250  0.430230  0.261280  0.266420   
1261   Etoposide+Etoposide+1        0 -0.64125  0.469260  0.331120  0.251450   
1284   Etoposide+Etoposide+1        0 -0.92292  0.321250  0.202080  0.192920   
1285   Etoposide+Etoposide+1        0 -0.79250  0.478660  0.342870  0.243060   
1262   Etoposide+Etoposide+2        0  0.13685  0.093075  0.069296 -0.054434   
...                      ...      ...      ...       ...       ...       ...   
717   Paclitaxel+Etoposide+5        0 -0.16167 -0.211590 -0.253620  0.101530   
694   Paclitaxel+Etoposide+6        0 -0.25610 -0.151600 -0.233990  0.105140   
695   Paclitaxel+Etoposide+6        0 -0.47542 -0.276040 -0.342130 -0.175520   
718   Paclitaxel+Etoposide+6        0 -0.53500 -0.205530 -0.295830 -0.170610   
719   Paclitaxel+Etoposide+6        0 -0.49500 -0.176240 -0.261810 -0.110280   

          ks5      ks6       ks7       ks8  ...    ks229     ks230     ks231  \
1260  0.26622  0.23978  0.233630  0.220140  ...  0.63798  0.104290 -0.218610   
1261  0.54936  0.36380  0.289990  0.292180  ...  0.65625 -0.037638  0.073717   
1284  0.43083  0.19458  0.176250  0.173750  ...  0.57042  0.165830 -0.291670   
1285  0.49101  0.36177  0.306620  0.321320  ...  0.61635  0.060051 -0.144120   
1262  0.16414  0.08174  0.044532 -0.048380  ...  0.08473 -0.028454  0.078405   
...       ...      ...       ...       ...  ...      ...       ...       ...   
717  -0.47382 -0.42908 -0.209540 -0.117560  ... -0.26579 -0.104840  0.235100   
694  -0.42556 -0.38522 -0.188280 -0.097921  ... -0.25366 -0.121660  0.254390   
695  -0.64399 -0.49033 -0.301420 -0.192030  ... -0.23048 -0.165930  0.319310   
718  -0.56848 -0.45439 -0.250270 -0.128520  ... -0.19159 -0.184620  0.269510   
719  -0.43979 -0.38595 -0.225270 -0.119570  ... -0.18306 -0.164260  0.217710   

        ks232     ks233     ks234    ks235     ks236     ks237     ks238  
1260  0.66386  0.662250  0.104290 -0.49506 -0.479380 -0.079277  0.201210  
1261  0.66479  0.706310 -0.037638 -0.41696 -0.328540  0.123200 -0.073301  
1284  0.66042  0.661670  0.165830 -0.52292 -0.476250 -0.128330  0.250000  
1285  0.62121  0.665220  0.060051 -0.47982 -0.412700 -0.069073  0.094167  
1262  0.10014  0.094098 -0.028454 -0.09596  0.094325  0.088627 -0.079684  
...       ...       ...       ...      ...       ...       ...       ...  
717  -0.31872 -0.298720 -0.104840  0.23601  0.254490 -0.105660 -0.264170  
694  -0.34893 -0.305960 -0.121660  0.29049  0.280750 -0.091204 -0.286070  
695  -0.30494 -0.272140 -0.165930  0.14860  0.219190 -0.081361 -0.291650  
718  -0.29114 -0.249050 -0.184620  0.19883  0.260570  0.105870 -0.303480  
719  -0.27935 -0.233680 -0.164260  0.22808  0.264670  0.088762 -0.279980  

[72 rows x 240 columns]

In [9]:
# to see the proper number of principle components
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
X_drug = e_and_p.iloc[:, 3:240].values

X_drug = StandardScaler().fit_transform(X_drug)
pca = PCA(n_components = 0.9)
pca.fit(X_drug)
reduced = pca.transform(X_drug)
print(len(X_drug[0]))
print(len(reduced[0]))
print(pca.explained_variance_ratio_)

237
8
[0.31072252 0.2015756  0.16923631 0.0842636  0.06410339 0.03772477
 0.01759506 0.01569609]


In [10]:
#see that again
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.95)
pca.fit(X_drug)
reduced = pca.transform(X_drug)
print(len(X_drug[0]))
print(len(reduced[0]))
print(pca.explained_variance_ratio_)

237
15
[0.31072252 0.2015756  0.16923631 0.0842636  0.06410339 0.03772477
 0.01759506 0.01569609 0.01261607 0.00995072 0.00850016 0.00639258
 0.00554854 0.00479382 0.0036747 ]


In [11]:
df=pd.read_csv('drug_with_fields.csv')
#one type first type. dna
df11=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+1') ]
df12=df.loc[(df['drug_name'] =='Etoposide+Gemcitabine+2') ]

df21=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+1') ]
df22=df.loc[(df['drug_name'] =='Gemcitabine+Etoposide+2') ]

df31=df.loc[(df['drug_name'] =='Etoposide+Etoposide+1') ]
df32=df.loc[(df['drug_name'] =='Etoposide+Etoposide+2') ]

df41=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+1') ]
df42=df.loc[(df['drug_name'] =='Gemcitabine+Gemcitabine+2') ]

df51=df.loc[(df['drug_name'] =='Gemcitabine+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='Gemcitabine+DMSO+2') ]



df61=df.loc[(df['drug_name'] =='Etoposide+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Etoposide+DMSO+2') ]



frames = [df11, df12,df21,df22,df31,df32,df41,df42,df51,df52,df61,df62]
dna = pd.concat(frames)
dna


drug_name  default      ks1       ks2       ks3       ks4  \
288   Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.272120   
289   Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.361410   
312   Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.374890   
313   Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.181460   
290   Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.259660   
291   Gemcitabine+Etoposide+2        0 -0.43083  0.296090  0.133160  0.268950   
314   Gemcitabine+Etoposide+2        0 -0.24625  0.185470 -0.092140  0.235070   
315   Gemcitabine+Etoposide+2        0 -0.28042  0.289890  0.133600  0.204580   
1260    Etoposide+Etoposide+1        0 -0.87250  0.430230  0.261280  0.266420   
1261    Etoposide+Etoposide+1        0 -0.64125  0.469260  0.331120  0.251450   
1284    Etoposide+Etoposide+1        0 -0.92292  0.321250  0.202080  0.192920   
1285    Etoposide+Etoposide+1        0 -0.79250  0.478660  0.342870  0.243060   
1262    Etoposide+Etoposide+2        0  0.13685  0.093075  0.069296 -0.054434   
1263    Etoposide+Etoposide+2        0 -0.55375 -0.157010 -0.165160  0.073749   
1286    Etoposide+Etoposide+2        0  0.19224 -0.136410 -0.160640 -0.098558   
1287    Etoposide+Etoposide+2        0 -0.30625  0.283270  0.301550 -0.081369   
60         Gemcitabine+DMSO+1        0 -0.43506  0.238280  0.086834  0.189750   
61         Gemcitabine+DMSO+1        0 -0.28375 -0.075667 -0.250820  0.200940   
84         Gemcitabine+DMSO+1        0 -0.19125  0.073316 -0.200130  0.156070   
85         Gemcitabine+DMSO+1        0 -0.32292 -0.339030 -0.549870  0.162410   
62         Gemcitabine+DMSO+2        0 -0.39208 -0.058333 -0.224310  0.166300   
63         Gemcitabine+DMSO+2        0 -0.15833 -0.191540 -0.391550  0.151590   
86         Gemcitabine+DMSO+2        0 -0.32967 -0.383580 -0.566420 -0.096000   
87         Gemcitabine+DMSO+2        0 -0.38042 -0.284750 -0.471880  0.068732   
1296         Etoposide+DMSO+1        0 -0.86542  0.368750  0.297920  0.134580   
1297         Etoposide+DMSO+1        0 -0.88583 -0.216250 -0.141250  0.271670   
1320         Etoposide+DMSO+1        0 -0.92000  0.152130 -0.222040  0.260790   
1321         Etoposide+DMSO+1        0 -0.92458 -0.308580 -0.408860 -0.124850   
1298         Etoposide+DMSO+2        0  0.16973  0.197440  0.212300  0.076551   
1299         Etoposide+DMSO+2        0  0.13454 -0.057376 -0.085138  0.037170   
1322         Etoposide+DMSO+2        0  0.18417 -0.078435 -0.092622 -0.056961   
1323         Etoposide+DMSO+2        0  0.11348  0.087708  0.108820 -0.024613   

           ks5       ks6       ks7       ks8  ...     ks229     ks230  \
288  -0.405750 -0.503060 -0.456620 -0.454380  ...  0.309020  0.098262   
289  -0.148340 -0.246130 -0.205880 -0.194610  ...  0.314070  0.058262   
312  -0.284660 -0.363750 -0.341210 -0.338950  ...  0.299810  0.085338   
313  -0.408660 -0.504910 -0.482440 -0.487010  ...  0.282460  0.126550   
290  -0.177040 -0.263640 -0.233270 -0.225690  ...  0.253050  0.160250   
291   0.241030 -0.068173  0.137450  0.165820  ...  0.319190  0.132600   
314   0.144350 -0.110970 -0.089130 -0.081101  ...  0.265940  0.086148   
315   0.206040  0.105150  0.125610  0.147320  ...  0.276900  0.066092   
1260  0.266220  0.239780  0.233630  0.220140  ...  0.637980  0.104290   
1261  0.549360  0.363800  0.289990  0.292180  ...  0.656250 -0.037638   
1284  0.430830  0.194580  0.176250  0.173750  ...  0.570420  0.165830   
1285  0.491010  0.361770  0.306620  0.321320  ...  0.616350  0.060051   
1262  0.164140  0.081740  0.044532 -0.048380  ...  0.084730 -0.028454   
1263 -0.144340 -0.155850 -0.169430 -0.158590  ...  0.260930  0.114340   
1286  0.115670 -0.129650 -0.176250 -0.185990  ...  0.073462 -0.063077   
1287  0.322800  0.319580  0.275480  0.276900  ...  0.209350  0.027083   
60    0.263890 -0.093564 -0.085325  0.081236  ...  0.274400  0.151520   
61   -0.132450 -0.258640 -0.2550

In [12]:

#one type first type. mt
df11=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+1') ]
df12=df.loc[(df['drug_name'] =='Paclitaxel+Vinblastine+2') ]

df21=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+1') ]
df22=df.loc[(df['drug_name'] =='Vinblastine+Paclitaxel+2') ]

df31=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+1') ]
df32=df.loc[(df['drug_name'] =='Paclitaxel+Paclitaxel+2') ]

df41=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+1') ]
df42=df.loc[(df['drug_name'] =='Vinblastine+Vinblastine+2') ]

df51=df.loc[(df['drug_name'] =='Paclitaxel+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='Paclitaxel+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='Vinblastine+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Vinblastine+DMSO+2') ]



frames2 = [df11, df12,df21,df22,df31,df32,df41,df42,df51,df52,df61,df62]
mt= pd.concat(frames2)
mt
#print(len(dna),len(mt))



drug_name  default      ks1       ks2       ks3      ks4  \
588   Paclitaxel+Vinblastine+1        0 -0.27500 -0.258880 -0.086688 -0.13499   
589   Paclitaxel+Vinblastine+1        0 -0.20375 -0.267970 -0.136310 -0.13175   
612   Paclitaxel+Vinblastine+1        0 -0.49583 -0.346390 -0.183470 -0.19861   
613   Paclitaxel+Vinblastine+1        0 -0.53167 -0.304310 -0.166310 -0.16731   
590   Paclitaxel+Vinblastine+2        0 -0.27583 -0.142300 -0.156530  0.14773   
591   Paclitaxel+Vinblastine+2        0 -0.32125 -0.265340 -0.346260 -0.12321   
614   Paclitaxel+Vinblastine+2        0 -0.24792 -0.239510 -0.275520 -0.11819   
615   Paclitaxel+Vinblastine+2        0 -0.23958 -0.230550 -0.257150 -0.13883   
1164   Paclitaxel+Paclitaxel+1        0 -0.75917 -0.581090 -0.394530 -0.39493   
1165   Paclitaxel+Paclitaxel+1        0 -0.76292 -0.463100 -0.236850 -0.27625   
1188   Paclitaxel+Paclitaxel+1        0 -0.89875 -0.495110 -0.249690 -0.29585   
1189   Paclitaxel+Paclitaxel+1        0 -0.65500 -0.345930 -0.212800 -0.15639   
1166   Paclitaxel+Paclitaxel+2        0 -0.76292 -0.298510 -0.153210 -0.25071   
1167   Paclitaxel+Paclitaxel+2        0 -0.67458 -0.252440 -0.093939 -0.18939   
1190   Paclitaxel+Paclitaxel+2        0 -0.47708 -0.221080 -0.291030  0.15201   
1191   Paclitaxel+Paclitaxel+2        0 -0.81625 -0.149960  0.050048 -0.17892   
816          Paclitaxel+DMSO+1        0 -0.48667 -0.319640 -0.132950 -0.30168   
817          Paclitaxel+DMSO+1        0 -0.68292 -0.354630 -0.111990 -0.34956   
840          Paclitaxel+DMSO+1        0 -0.72458 -0.424650 -0.201600 -0.31538   
841          Paclitaxel+DMSO+1        0 -0.62792 -0.350440 -0.162220 -0.33031   
818          Paclitaxel+DMSO+2        0 -0.65125 -0.220030 -0.153250 -0.20715   
819          Paclitaxel+DMSO+2        0 -0.65042 -0.115350 -0.136910 -0.14007   
842          Paclitaxel+DMSO+2        0 -0.76542 -0.165950 -0.178110 -0.13727   
843          Paclitaxel+DMSO+2        0 -0.67625 -0.196890 -0.092061 -0.18154   
972         Vinblastine+DMSO+1        0 -0.53500 -0.178750 -0.195340  0.10686   
973         Vinblastine+DMSO+1        0 -0.57167 -0.135670 -0.106230 -0.12021   
996         Vinblastine+DMSO+1        0 -0.49500 -0.259960 -0.192130 -0.18467   
997         Vinblastine+DMSO+1        0 -0.46792 -0.194520 -0.163120 -0.09825   
974         Vinblastine+DMSO+2        0 -0.15458 -0.239900 -0.369590  0.28835   
975         Vinblastine+DMSO+2        0 -0.15042 -0.307400 -0.466850  0.33771   
998         Vinblastine+DMSO+2        0 -0.39000 -0.050435 -0.080462  0.22177   
999         Vinblastine+DMSO+2        0  0.10907 -0.045425 -0.104990  0.13264   

           ks5      ks6       ks7       ks8  ...     ks229     ks230  \
588  -0.609590 -0.31824 -0.040134  0.170860  ... -0.491700 -0.354070   
589  -0.602510 -0.36357 -0.084163  0.123060  ... -0.458200 -0.295470   
612  -0.716530 -0.41583 -0.111670  0.095139  ... -0.412780 -0.322500   
613  -0.674520 -0.40416 -0.091777  0.114900  ... -0.526330 -0.393490   
590  -0.404610 -0.37457 -0.115130  0.106660  ... -0.293980 -0.201980   
591  -0.615680 -0.52210 -0.293780 -0.173460  ... -0.246290 -0.166910   
614  -0.567600 -0.47661 -0.219540 -0.087308  ... -0.348340 -0.152310   
615  -0.567190 -0.48083 -0.221390 -0.066476  ... -0.318830 -0.228960   
1164 -0.802460 -0.53512 -0.317220 -0.180090  ... -0.230990 -0.235670   
1165 -0.668040 -0.41399 -0.172620 -0.127620  ...  0.268810  0.125770   
1188 -0.708040 -0.41210 -0.198210 -0.131110  ...  0.398730  0.153210   
1189 -0.626970 -0.44532 -0.148150  0.059829  ...  0.098538 -0.123220   
1166 -0.677140 -0.38381 -0.104760  0.212800  ... -0.334700 -0.197260   
1167 -0.624690 -0.35943 -0.035102  0.220040  ... -0.229970 -0.198070   
1190 -0.518330 -0.46538 -0.223550 -0.129410  ... -0.126900 -0.126990   
1191 -0.565120 -0.30623  0.096483  0.253520  ... -0.087025 -0.203490   
816  -0.791950 -0.47082 -0.101560  0.238770  ... -0.550130 -0.325980   
817  -0.767830 -0.45376 -0.075402  0.225410  ... -0

In [13]:

frames3=[]
for i in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+AUY922+'+str(i)) ])
for j in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+17AAG+'+str(j)) ])
for k in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='AUY922+AUY922+'+str(k)) ])
for m in range(1,3):
    frames3.append(df.loc[(df['drug_name'] =='17AAG+17AAG+'+str(m)) ])

df51=df.loc[(df['drug_name'] =='17AAG+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='17AAG+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='AUY922+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='AUY922+DMSO+2') ]
another_lst=[df51,df52,df61,df62]
frames3=frames3+another_lst
HSP= pd.concat(frames3)
HSP


drug_name  default      ks1      ks2      ks3       ks4      ks5  \
432    17AAG+AUY922+1        0  0.12512 -0.46275 -0.35777 -0.228330 -0.72383   
433    17AAG+AUY922+1        0 -0.14583 -0.36235 -0.28347 -0.148500 -0.56642   
456    17AAG+AUY922+1        0 -0.13625 -0.35090 -0.28563 -0.133080 -0.57341   
457    17AAG+AUY922+1        0 -0.20167 -0.42543 -0.35686 -0.223910 -0.70629   
434    17AAG+AUY922+2        0 -0.30042 -0.29033 -0.26982 -0.130900 -0.49008   
435    17AAG+AUY922+2        0 -0.17417 -0.30279 -0.28715 -0.119090 -0.49773   
458    17AAG+AUY922+2        0 -0.24708 -0.45449 -0.35224 -0.217140 -0.72476   
459    17AAG+AUY922+2        0 -0.14708 -0.41732 -0.35095 -0.188140 -0.62754   
1356  AUY922+AUY922+1        0 -0.84708 -0.33663 -0.34076 -0.133110 -0.55045   
1357  AUY922+AUY922+1        0 -0.69042 -0.42670 -0.47650 -0.188580 -0.74933   
1380  AUY922+AUY922+1        0 -0.84000 -0.22256 -0.24263 -0.081178 -0.44293   
1381  AUY922+AUY922+1        0 -0.95208 -0.24786  0.14181 -0.174970 -0.21879   
1358  AUY922+AUY922+2        0 -0.69500 -0.27855 -0.28250 -0.163270 -0.53495   
1359  AUY922+AUY922+2        0 -0.59708 -0.42794 -0.43216 -0.181830 -0.69676   
1382  AUY922+AUY922+2        0 -0.82542 -0.42339 -0.41547 -0.250000 -0.71629   
1383  AUY922+AUY922+2        0 -0.91167 -0.15316 -0.16318 -0.079468 -0.45368   
480      17AAG+DMSO+1        0 -0.14625 -0.30794 -0.22791 -0.182310 -0.59108   
481      17AAG+DMSO+1        0 -0.25375 -0.44188 -0.37461 -0.187470 -0.63871   
504      17AAG+DMSO+1        0 -0.19000 -0.48273 -0.41934 -0.203270 -0.72075   
505      17AAG+DMSO+1        0  0.13105 -0.37524 -0.27833 -0.153200 -0.63105   
482      17AAG+DMSO+2        0 -0.16083 -0.24619 -0.21730 -0.088039 -0.47427   
483      17AAG+DMSO+2        0 -0.22125 -0.38109 -0.32378 -0.231010 -0.66516   
506      17AAG+DMSO+2        0 -0.26667 -0.24889 -0.21335 -0.142850 -0.49517   
507      17AAG+DMSO+2        0 -0.13292 -0.44319 -0.31731 -0.220220 -0.73763   
1440    AUY922+DMSO+1        0 -0.51542 -0.44488 -0.46637 -0.239470 -0.76751   
1441    AUY922+DMSO+1        0 -0.33667 -0.44346 -0.48285 -0.266440 -0.79378   
1464    AUY922+DMSO+1        0 -0.85458 -0.47946 -0.45686 -0.234560 -0.77358   
1465    AUY922+DMSO+1        0 -0.85875 -0.21683 -0.29485  0.135770 -0.47052   
1442    AUY922+DMSO+2        0 -0.45083 -0.33226 -0.36054 -0.159620 -0.63379   
1443    AUY922+DMSO+2        0 -0.36042 -0.31285 -0.35152 -0.142930 -0.59856   
1466    AUY922+DMSO+2        0 -0.69042 -0.31179 -0.32003 -0.167240 -0.56429   
1467    AUY922+DMSO+2        0 -0.71708 -0.33458 -0.38875 -0.160830 -0.67000   

          ks6      ks7      ks8  ...     ks229     ks230     ks231    ks232  \
432  -0.53077 -0.29647 -0.25058  ... -0.196410 -0.107040  0.166990 -0.24339   
433  -0.47063 -0.24710 -0.18895  ... -0.207880 -0.148320  0.149010 -0.28328   
456  -0.44494 -0.25381 -0.21069  ... -0.178750 -0.107690  0.137840 -0.23651   
457  -0.48697 -0.31005 -0.28401  ... -0.099377 -0.133100  0.141100 -0.19154   
434  -0.38280 -0.24551 -0.19899  ... -0.112720 -0.077571  0.054277 -0.16137   
435  -0.42034 -0.24592 -0.18161  ... -0.128840 -0.088680  0.094486 -0.20953   
458  -0.50393 -0.30702 -0.25454  ... -0.167390 -0.135430  0.174850 -0.23421   
459  -0.49221 -0.30424 -0.25095  ... -0.094999 -0.069764  0.095069 -0.14731   
1356 -0.41231 -0.31322 -0.29606  ...  0.103860  0.125720 -0.129170  0.18193   
1357 -0.54492 -0.45168 -0.41736  ...  0.202750  0.121040 -0.159010  0.27716   
1380 -0.31846 -0.23879 -0.20859  ...  0.424310  0.160000 -0.453330  0.50359   
1381 -0.14618  0.12181  0.20578  ...  0.250160  0.356820 -0.373120  0.37339   
1358 -0.41002 -0.25253 -0.21798  ...  0.187040  0.099155 -0.240810  0.22788   
1359 -0.53566 -0.38952 -0.35700  ...  0.196980 -0.085123 -0.129590  0.24408   
1382 -0.47630 -0.40116 -0.38000  ...  0.194260  0.135510 -0.170280  0.29304   
1383 -0.33309 -0.15144  0.25874  ...  0.415170  0.314760 -0.553200  0.56149   
480  -0.41540 -0.20273 -0.16

In [14]:
#Dna ： etoposide，Gemcitabine
#mt：paclitaxel，Vinblastine
#hsp：17aag，auy922

#prot："MG132"，ps341
#hdac：saha，apicidin

frames4=[]
for i in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='MG132+PS341+'+str(i)) ])
for j in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='PS341+MG132+'+str(j)) ])
for k in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='MG132+MG132+'+str(k)) ])
for m in range(1,3):
    frames4.append(df.loc[(df['drug_name'] =='PS341+PS341+'+str(m)) ])
df51=df.loc[(df['drug_name'] =='MG132+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='MG132+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='PS341+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='PS341+DMSO+2') ]
another_lst=[df51,df52,df61,df62]
frames4=frames4+another_lst
PROT= pd.concat(frames4)
PROT

drug_name  default      ks1      ks2      ks3      ks4      ks5  \
396   PS341+MG132+1        0 -0.57083 -0.65243 -0.68537 -0.58167 -0.93353   
397   PS341+MG132+1        0 -0.37625 -0.56318 -0.67811 -0.41361 -0.90242   
420   PS341+MG132+1        0 -0.52917 -0.65365 -0.69407 -0.60150 -0.94298   
421   PS341+MG132+1        0 -0.41667 -0.61814 -0.65463 -0.47647 -0.92267   
398   PS341+MG132+2        0 -0.58542 -0.51228 -0.50626 -0.37930 -0.83408   
399   PS341+MG132+2        0 -0.67458 -0.61303 -0.49983 -0.48690 -0.91470   
422   PS341+MG132+2        0 -0.53917 -0.50482 -0.53827 -0.47248 -0.90456   
423   PS341+MG132+2        0 -0.42417 -0.57130 -0.52389 -0.45215 -0.91534   
1308  MG132+MG132+1        0 -0.84458 -0.60884 -0.68654 -0.42920 -0.88794   
1309  MG132+MG132+1        0 -0.47292 -0.62086 -0.69725 -0.45806 -0.91361   
1332  MG132+MG132+1        0 -0.90542 -0.70768 -0.73528 -0.62794 -0.94200   
1333  MG132+MG132+1        0 -0.78500 -0.61185 -0.69503 -0.47560 -0.91222   
1310  MG132+MG132+2        0 -0.75000 -0.47825 -0.51677 -0.33117 -0.79784   
1311  MG132+MG132+2        0 -0.88792 -0.62346 -0.58088 -0.47403 -0.90611   
1334  MG132+MG132+2        0 -0.74250 -0.63011 -0.63920 -0.43407 -0.89362   
1335  MG132+MG132+2        0 -0.86792 -0.55105 -0.64143 -0.49059 -0.88123   
1392   MG132+DMSO+1        0 -0.72625 -0.67204 -0.73244 -0.54572 -0.92628   
1393   MG132+DMSO+1        0 -0.75917 -0.57608 -0.61486 -0.44152 -0.87070   
1416   MG132+DMSO+1        0 -0.89167 -0.57853 -0.67535 -0.39119 -0.82000   
1417   MG132+DMSO+1        0 -0.92458 -0.64048 -0.75300 -0.76253 -0.98208   
1394   MG132+DMSO+2        0 -0.55792 -0.42314 -0.42486 -0.18923 -0.72776   
1395   MG132+DMSO+2        0 -0.35875 -0.36896 -0.37138 -0.15965 -0.63534   
1418   MG132+DMSO+2        0 -0.78917 -0.41867 -0.44089 -0.22199 -0.71321   
1419   MG132+DMSO+2        0 -0.85042 -0.45605 -0.46367 -0.14458 -0.67356   
492    PS341+DMSO+1        0 -0.34250 -0.58296 -0.57761 -0.45306 -0.91576   
493    PS341+DMSO+1        0 -0.28292 -0.61297 -0.53655 -0.46007 -0.90849   
516    PS341+DMSO+1        0 -0.38042 -0.54972 -0.55672 -0.45425 -0.89565   
517    PS341+DMSO+1        0 -0.23172 -0.48411 -0.50299 -0.39327 -0.83802   
494    PS341+DMSO+2        0 -0.29500 -0.59352 -0.57258 -0.46462 -0.90974   
495    PS341+DMSO+2        0 -0.37208 -0.52970 -0.41591 -0.38692 -0.88047   
518    PS341+DMSO+2        0 -0.21792 -0.47768 -0.41633 -0.34686 -0.83277   
519    PS341+DMSO+2        0 -0.25250 -0.58686 -0.55543 -0.45509 -0.91309   

          ks6      ks7      ks8  ...    ks229     ks230     ks231    ks232  \
396  -0.73263 -0.63684 -0.60739  ... -0.25803  0.055219 -0.452680 -0.22772   
397  -0.71855 -0.63371 -0.60988  ... -0.52192 -0.080365 -0.252330 -0.48349   
420  -0.72470 -0.64522 -0.60870  ... -0.61905 -0.129820  0.092136 -0.61050   
421  -0.71600 -0.59480 -0.55225  ... -0.59904 -0.089020 -0.080417 -0.57804   
398  -0.60931 -0.46338 -0.41122  ... -0.30921  0.145150 -0.441540 -0.22485   
399  -0.66218 -0.45717 -0.44547  ... -0.59956 -0.109160  0.156280 -0.56316   
422  -0.65721 -0.48219 -0.45505  ... -0.67721 -0.245250  0.496100 -0.71539   
423  -0.64535 -0.47736 -0.43619  ... -0.65825 -0.132850  0.230810 -0.65668   
1308 -0.75922 -0.65186 -0.58035  ...  0.30923  0.238210  0.073787  0.42528   
1309 -0.73821 -0.65962 -0.61879  ...  0.30090  0.137700 -0.490720  0.38185   
1332 -0.75988 -0.67819 -0.63054  ...  0.20958  0.307880 -0.154520  0.35181   
1333 -0.72843 -0.64201 -0.60089  ...  0.27042  0.272320 -0.049026  0.43183   
1310 -0.60294 -0.46838 -0.42775  ...  0.26308  0.209820 -0.109690  0.38948   
1311 -0.69999 -0.53331 -0.50601  ...  0.37247  0.325540 -0.259490  0.60346   
1334 -0.68069 -0.56980 -0.52486  ...  0.31206  0.249770 -0.434050  0.44478   
1335 -0.66750 -0.58715 -0.55996  ...  0.31862  0.267430 -0.120500  0.40792   
1392 -0.76380 -0.69278 -0.65930  ...  0.29319  0.276600 -0.265640  0.42888   
1393 -0.70600 -0.57020 -0.51363  ...  0.29257  0.164690 -0.54242

In [15]:
frames5=[]
for i in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+Apicidin+'+str(i)) ])
for j in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+SAHA+'+str(j)) ])
for k in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='Apicidin+Apicidin+'+str(k)) ])
for m in range(1,3):
    frames5.append(df.loc[(df['drug_name'] =='SAHA+SAHA+'+str(m)) ])

df51=df.loc[(df['drug_name'] =='SAHA+DMSO+1') ]
df52=df.loc[(df['drug_name'] =='SAHA+DMSO+2') ]

df61=df.loc[(df['drug_name'] =='Apicidin+DMSO+1') ]
df62=df.loc[(df['drug_name'] =='Apicidin+DMSO+2') ]

another_lst=[df51,df52,df61,df62]
frames5=frames5+another_lst
HDAC= pd.concat(frames5)
HDAC

drug_name  default      ks1       ks2       ks3       ks4  \
912       Apicidin+SAHA+1        0 -0.69042 -0.296930 -0.340530 -0.174020   
913       Apicidin+SAHA+1        0 -0.35208 -0.181170 -0.191110 -0.094006   
936       Apicidin+SAHA+1        0 -0.52667 -0.206170 -0.250750 -0.101510   
937       Apicidin+SAHA+1        0 -0.39542 -0.174210 -0.215880 -0.088104   
914       Apicidin+SAHA+2        0 -0.56542 -0.066917  0.114750 -0.041456   
915       Apicidin+SAHA+2        0 -0.46417 -0.165090 -0.113100 -0.090829   
938       Apicidin+SAHA+2        0 -0.66417 -0.152530 -0.185580 -0.097895   
939       Apicidin+SAHA+2        0 -0.45500 -0.070569  0.151470 -0.074440   
1212  Apicidin+Apicidin+1        0 -0.55792 -0.194790 -0.234200 -0.093386   
1213  Apicidin+Apicidin+1        0 -0.80833 -0.120190 -0.160510 -0.157220   
1236  Apicidin+Apicidin+1        0 -0.58250 -0.143510 -0.156190 -0.074442   
1237  Apicidin+Apicidin+1        0 -0.89583 -0.224400 -0.272890 -0.113330   
1214  Apicidin+Apicidin+2        0 -0.55792 -0.056940  0.111860 -0.122950   
1215  Apicidin+Apicidin+2        0 -0.35333 -0.047568  0.063691 -0.118290   
1238  Apicidin+Apicidin+2        0 -0.66833  0.076006  0.147360 -0.088779   
1239  Apicidin+Apicidin+2        0 -0.69333 -0.081991 -0.085370 -0.111020   
1152          SAHA+DMSO+1        0 -0.56458 -0.224350 -0.219800 -0.124640   
1153          SAHA+DMSO+1        0 -0.48458 -0.182050 -0.165830 -0.118490   
1176          SAHA+DMSO+1        0 -0.87250 -0.285130 -0.310550  0.211160   
1177          SAHA+DMSO+1        0 -0.69667 -0.133160 -0.222900  0.304060   
1154          SAHA+DMSO+2        0 -0.38250 -0.135980 -0.154600  0.124340   
1155          SAHA+DMSO+2        0 -0.48208 -0.140340 -0.123450 -0.090430   
1178          SAHA+DMSO+2        0 -0.57500  0.085833 -0.145000  0.285830   
1179          SAHA+DMSO+2        0 -0.63000  0.226250  0.083826  0.361780   
1104      Apicidin+DMSO+1        0 -0.23958 -0.124910 -0.163290  0.151590   
1105      Apicidin+DMSO+1        0 -0.52375 -0.097286 -0.111520  0.085041   
1128      Apicidin+DMSO+1        0 -0.49208 -0.111460 -0.147710  0.085778   
1129      Apicidin+DMSO+1        0 -0.56125 -0.127980 -0.202720  0.132560   
1106      Apicidin+DMSO+2        0  0.28421 -0.150070 -0.250800  0.295560   
1107      Apicidin+DMSO+2        0 -0.28125 -0.027019 -0.112140  0.206540   
1130      Apicidin+DMSO+2        0 -0.49208  0.080930 -0.047459  0.174400   
1131      Apicidin+DMSO+2        0 -0.48708  0.046407  0.076933 -0.125010   

           ks5       ks6       ks7       ks8  ...     ks229     ks230  \
912  -0.665450 -0.450950 -0.317120 -0.273750  ... -0.567390 -0.135720   
913  -0.547370 -0.272550 -0.160080  0.198330  ... -0.426550 -0.163430   
936  -0.567610 -0.309630 -0.218430 -0.191720  ... -0.430630 -0.157520   
937  -0.527070 -0.323800 -0.203650 -0.182740  ... -0.427930 -0.136910   
914  -0.390910 -0.128700  0.145360  0.228880  ... -0.236700 -0.126050   
915  -0.471170 -0.211960 -0.099283  0.132420  ... -0.335470 -0.103260   
938  -0.535070 -0.217190 -0.165560  0.174230  ... -0.310840 -0.108500   
939  -0.392960 -0.094577  0.179360  0.249200  ... -0.218330 -0.080448   
1212 -0.562520 -0.399930 -0.193930 -0.152750  ... -0.434320 -0.096292   
1213 -0.547080 -0.235050  0.163890  0.270370  ... -0.356440 -0.109720   
1236 -0.533810 -0.243370 -0.134280  0.227060  ... -0.367730 -0.113450   
1237 -0.602480 -0.422150 -0.244200 -0.234280  ... -0.396210 -0.106100   
1214 -0.363080 -0.098344  0.158050  0.217040  ... -0.147820  0.106290   
1215 -0.303940 -0.085672  0.083717  0.138260  ... -0.159380  0.105200   
1238 -0.249170 -0.067184  0.170500  0.196450  ... -0.103690  0.138820   
1239 -0.444260 -0.193750 -0.071667  0.098796  ... -0.098287  0.113330   
1152 -0.595320 -0.336990 -0.198980 -0.193580  ... -0.429520 -0.150500   
1153 -0.559840 -0.290530 -0.145170  0.189360  ... -0.312250 -0.123530   
1176 -0.528040 -0.403810 -0.272220 -0.253050  ... -0.340750 -0.243840   
1177 -0.397460

In [16]:
frames6=[]
for i in range(1,3):
    frames6.append(df.loc[(df['drug_name'] =='DMSO+DMSO+'+str(i)) ])

DMSO= pd.concat(frames6)
DMSO
#len(DMSO)


drug_name  default      ks1       ks2       ks3       ks4       ks5  \
1404  DMSO+DMSO+1        0  0.26423 -0.191470 -0.279800  0.146180 -0.195440   
1405  DMSO+DMSO+1        0 -0.28583  0.170760  0.252280 -0.124140  0.169460   
1428  DMSO+DMSO+1        0 -0.19833  0.160910  0.183850 -0.112090  0.192170   
1429  DMSO+DMSO+1        0 -0.82292  0.648170  0.663170 -0.118250  0.496000   
1452  DMSO+DMSO+1        0 -0.33340 -0.086441 -0.138140  0.111720 -0.121250   
1453  DMSO+DMSO+1        0  0.13743  0.030150  0.046624 -0.066784  0.130540   
1476  DMSO+DMSO+1        0 -0.38417 -0.113400 -0.118880 -0.173330  0.091425   
1477  DMSO+DMSO+1        0 -0.54083 -0.132630 -0.110940 -0.141690 -0.142570   
1488  DMSO+DMSO+1        0  0.25978 -0.419300 -0.519300  0.103630 -0.450930   
1489  DMSO+DMSO+1        0  0.12452 -0.038936 -0.201300  0.252770 -0.117710   
1500  DMSO+DMSO+1        0 -0.30417 -0.256940 -0.259370 -0.094463 -0.216520   
1501  DMSO+DMSO+1        0  0.18471  0.142200  0.145240 -0.039861  0.201490   
1512  DMSO+DMSO+1        0  0.24417  0.102680  0.095019  0.087185  0.114840   
1513  DMSO+DMSO+1        0 -0.11750 -0.100570 -0.195160  0.259640 -0.167770   
1524  DMSO+DMSO+1        0  0.31438 -0.038593 -0.085611 -0.024620  0.100680   
1525  DMSO+DMSO+1        0 -0.49583 -0.182500 -0.248060 -0.099583 -0.121390   
1406  DMSO+DMSO+2        0  0.20772 -0.062188 -0.110120  0.059334  0.046472   
1407  DMSO+DMSO+2        0 -0.10208 -0.142430 -0.131840 -0.036788 -0.059414   
1430  DMSO+DMSO+2        0  0.13163  0.020900  0.077371 -0.088747  0.092360   
1431  DMSO+DMSO+2        0 -0.29708 -0.168800 -0.093349 -0.043894 -0.123350   
1454  DMSO+DMSO+2        0  0.17875  0.032522  0.050735 -0.071262  0.061112   
1455  DMSO+DMSO+2        0  0.34978 -0.125790 -0.130910 -0.075205  0.049501   
1478  DMSO+DMSO+2        0  0.20621 -0.459950 -0.456920 -0.167270 -0.331130   
1479  DMSO+DMSO+2        0 -0.11292 -0.048638 -0.059902 -0.067991  0.036220   
1490  DMSO+DMSO+2        0  0.35535 -0.159130 -0.338850  0.376710 -0.256850   
1491  DMSO+DMSO+2        0  0.36697  0.051450 -0.149660  0.431630 -0.054828   
1502  DMSO+DMSO+2        0 -0.16208  0.098648  0.090666  0.061739  0.079592   
1503  DMSO+DMSO+2        0 -0.10833 -0.218940 -0.218850 -0.153680 -0.075702   
1514  DMSO+DMSO+2        0  0.15515  0.058406 -0.092225  0.322010  0.061095   
1515  DMSO+DMSO+2        0 -0.11708  0.144440  0.143580  0.136450  0.118600   
1526  DMSO+DMSO+2        0 -0.26842  0.166930  0.207920 -0.140920  0.120280   
1527  DMSO+DMSO+2        0 -0.43083  0.314670  0.426560 -0.168680  0.121230   

           ks6       ks7       ks8  ...     ks229     ks230     ks231  \
1404 -0.281620 -0.266000 -0.262080  ... -0.132900 -0.046385  0.194800   
1405  0.256800  0.230590  0.239440  ...  0.156740  0.077679 -0.244190   
1428  0.191130  0.166070  0.169120  ...  0.118590 -0.042965 -0.091366   
1429  0.640670  0.651830  0.651750  ...  0.423830  0.105080  0.148170   
1452 -0.135060 -0.134610 -0.134170  ...  0.065650 -0.032644 -0.043951   
1453  0.059049 -0.057778 -0.064968  ... -0.041036 -0.049338  0.070652   
1476  0.093706 -0.130370 -0.140640  ...  0.145880  0.046776 -0.138550   
1477 -0.073021 -0.115630 -0.119270  ...  0.214040  0.095849 -0.262320   
1488 -0.521280 -0.504490 -0.501650  ... -0.193020 -0.062632  0.179430   
1489 -0.241730 -0.169140 -0.152510  ... -0.094881 -0.052948  0.147010   
1500 -0.235940 -0.264490 -0.265000  ...  0.084362  0.044840 -0.051968   
1501  0.167780  0.120350  0.114670  ... -0.107960 -0.044059  0.150640   
1512  0.071767  0.091039  0.092708  ... -0.069310 -0.029260  0.086638   
1513 -0.235880 -0.175570 -0.163950  ...  0.115940 -0.052720  0.084819   
1524 -0.052829 -0.104650 -0.098313  ... -0.060541 -0.079512  0.166030   
1525 -0.235690 -0.233330 -0.230140  ...  0.131390  0.030694 -0.060833   
1406 -0.089871 -0.116540 -0.116350  ... -0.086647 -0.077675  0.130840   
1407 -0.113490 -0.129910 -0.132300  ... -0.043730 -0.051072  0.074235   
1430  0.07704

In [17]:
combi=frames+frames2+frames3+frames4+frames5+frames6
training= pd.concat(combi)

print(len(training))

192


In [18]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X_drug = training.iloc[:, 2:240].values

X_drug = StandardScaler().fit_transform(X_drug)

pca_drug = PCA(n_components=8)
components = pca_drug.fit_transform(X_drug)
components
principalDf = pd.DataFrame(data = components
             , columns = ['principal component 1', 'principal component 2','principal component 3', 'principal component 4','principal component 5', 'principal component 6','principal component 7', 'principal component 8'])
principalDf

principal component 1  principal component 2  principal component 3  \
0                -9.210831               1.971956               1.985239   
1               -11.427386              -2.236591              -0.076146   
2                -9.548587               0.544286               1.288563   
3                -8.746532               1.904091               2.416643   
4                -9.243794               0.813960               1.897365   
..                     ...                    ...                    ...   
187               3.048212              -6.732952               8.264945   
188              -1.565806              -8.659482               6.276333   
189              -5.525015             -10.188852               7.808363   
190              -1.058137             -10.233128               9.793628   
191              -3.882653              -6.040206               8.982553   

     principal component 4  principal component 5  principal component 6  \
0                -6.253599              -5.174828              -5.088056   
1                -5.218438              -0.882598              -1.417285   
2                -4.716602              -1.364516              -3.410210   
3                -4.621695              -3.738491              -5.862680   
4                -6.670023               0.647295              -1.955733   
..                     ...                    ...                    ...   
187              -2.824676              -1.284406              -4.309154   
188              -2.768603               2.277807              -0.472120   
189               7.415952               4.357231               1.038655   
190               1.497302              -3.775224               2.322171   
191               6.199455               6.244085               6.440435   

     principal component 7  principal component 8  
0                -3.171787              -3.510841  
1                -1.579464              -3.883445  
2                -1.769053              -3.669465  
3                -2.557660              -4.028172  
4                -1.503388              -1.739354  
..                     ...                    ...  
187              -0.777973               2.189911  
188               0.138555               1.784222  
189               1.851929              -1.771310  
190               3.530289               0.352086  
191               2.088186               1.248101  

[192 rows x 8 columns]

In [19]:
type(training.iloc[:, 0].values)
import numpy as np
all_names=np.ndarray.tolist(training.iloc[:,0].values)

In [20]:
components2=np.ndarray.tolist(components)

for i in range(len(all_names)):
    components2[i].append(all_names[i])
#components2

In [21]:
#class preparation
train_drug_name_without_concentration2=[]
#dna,mt,hsp,prot,hdac
for i in range(32):
    train_drug_name_without_concentration2.append('DNA')
for i in range(32):
    train_drug_name_without_concentration2.append('MT')
for i in range(32):
    train_drug_name_without_concentration2.append('HSP')
for i in range(32):
    train_drug_name_without_concentration2.append('PROT')
for i in range(32):
    train_drug_name_without_concentration2.append('HDAC')
for i in range(32):
    train_drug_name_without_concentration2.append("DMSO")

#train_drug_name_without_concentration2 

In [22]:
import plotly.express as px
fig = px.scatter(components, x=0, y=1, color=train_drug_name_without_concentration2)
fig.show()

In [23]:
def get_centroid(point_lst):
    x_sum=0
    y_sum=0
    z1_sum=0
    z2_sum=0
    z3_sum=0
    z4_sum=0
    z5_sum=0
    z6_sum=0


    for i in range(len(point_lst)):
        x_sum+=point_lst[i][0]
        y_sum+=point_lst[i][1]
        z1_sum+=point_lst[i][2]
        z2_sum+=point_lst[i][3]
        z3_sum+=point_lst[i][4]
        z4_sum+=point_lst[i][5]
        z5_sum+=point_lst[i][6]
        z6_sum+=point_lst[i][7]


    x_mean=x_sum/len(point_lst)
    y_mean=y_sum/len(point_lst)
    z1_mean=z1_sum/len(point_lst)
    z2_mean=z2_sum/len(point_lst)
    z3_mean=z3_sum/len(point_lst)
    z4_mean=z4_sum/len(point_lst)
    z5_mean=z5_sum/len(point_lst)
    z6_mean=z6_sum/len(point_lst)
    centroid=[]
    centroid.append(x_mean)
    centroid.append(y_mean)
    centroid.append(z1_mean)
    centroid.append(z2_mean)
    centroid.append(z3_mean)
    centroid.append(z4_mean)
    centroid.append(z5_mean)
    centroid.append(z6_mean)
    
    return centroid


In [24]:
training

drug_name  default      ks1       ks2       ks3      ks4  \
288   Gemcitabine+Etoposide+1        0 -0.37625 -0.239770 -0.472950  0.27212   
289   Gemcitabine+Etoposide+1        0 -0.30750  0.084427 -0.217620  0.36141   
312   Gemcitabine+Etoposide+1        0 -0.40083 -0.130780 -0.355410  0.37489   
313   Gemcitabine+Etoposide+1        0 -0.36125 -0.268510 -0.500130  0.18146   
290   Gemcitabine+Etoposide+2        0 -0.39000 -0.074998 -0.244910  0.25966   
...                       ...      ...      ...       ...       ...      ...   
1503              DMSO+DMSO+2        0 -0.10833 -0.218940 -0.218850 -0.15368   
1514              DMSO+DMSO+2        0  0.15515  0.058406 -0.092225  0.32201   
1515              DMSO+DMSO+2        0 -0.11708  0.144440  0.143580  0.13645   
1526              DMSO+DMSO+2        0 -0.26842  0.166930  0.207920 -0.14092   
1527              DMSO+DMSO+2        0 -0.43083  0.314670  0.426560 -0.16868   

           ks5      ks6       ks7       ks8  ...     ks229     ks230  \
288  -0.405750 -0.50306 -0.456620 -0.454380  ...  0.309020  0.098262   
289  -0.148340 -0.24613 -0.205880 -0.194610  ...  0.314070  0.058262   
312  -0.284660 -0.36375 -0.341210 -0.338950  ...  0.299810  0.085338   
313  -0.408660 -0.50491 -0.482440 -0.487010  ...  0.282460  0.126550   
290  -0.177040 -0.26364 -0.233270 -0.225690  ...  0.253050  0.160250   
...        ...      ...       ...       ...  ...       ...       ...   
1503 -0.075702 -0.18815 -0.230440 -0.234840  ... -0.183620 -0.058209   
1514  0.061095 -0.14118 -0.070689 -0.054594  ... -0.030696 -0.070114   
1515  0.118600  0.10983  0.153210  0.159460  ...  0.129850 -0.044044   
1526  0.120280  0.21838  0.196360  0.203860  ...  0.053572 -0.093384   
1527  0.121230  0.44859  0.404460  0.407570  ...  0.126320  0.048968   

         ks231     ks232     ks233     ks234     ks235     ks236     ks237  \
288   0.087180  0.399560  0.409440  0.098262 -0.308850 -0.227210  0.098363   
289  -0.141980  0.355410  0.380740  0.058262 -0.132720 -0.186760  0.078267   
312  -0.077312  0.363630  0.383620  0.085338 -0.211410 -0.194220  0.077165   
313   0.074616  0.374620  0.377060  0.126550 -0.305530 -0.230910  0.058352   
290  -0.146910  0.385550  0.390930  0.160250 -0.221980 -0.241610  0.059718   
...        ...       ...       ...       ...       ...       ...       ...   
1503  0.187390 -0.226000 -0.214100 -0.058209  0.148670  0.221960  0.083449   
1514  0.116940 -0.074759 -0.045337 -0.070114  0.169490  0.144980  0.054948   
1515  0.051471  0.114040  0.124020 -0.044044 -0.039142 -0.064804 -0.022770   
1526  0.093702 -0.070864 -0.058081 -0.093384  0.107860  0.121960  0.082383   
1527 -0.264860  0.161010  0.131090  0.048968 -0.155020 -0.267220 -0.113010   

         ks238  
288  -0.091499  
289   0.094994  
312   0.084654  
313  -0.081113  
290   0.144270  
...        ...  
1503 -0.185260  
1514 -0.117670  
1515 -0.046471  
1526 -0.077445  
1527  0.270060  

[192 rows x 240 columns]

In [25]:
len(principalDf[-32:])

32

In [26]:
#DMSO filtering part
dmso_centroid=get_centroid(components[-32:])


In [27]:
dmso_lst=components[-32:]

In [28]:
#calculating the distance
from math import sqrt
def euclidean_distance(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(len(row1)-1):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [29]:
dist_lst=[]
for i in range(len(dmso_lst)):
    dist_lst.append(euclidean_distance(dmso_lst[i],dmso_centroid))
dist_lst.sort()
print(len(dist_lst))
max_ave=sum(dist_lst[-5:-1])/len(dist_lst[-5:-1])
max_ave
max_ave*=2
max_ave

32


25.97335479752179

In [30]:
#outlier computation
# method 1.
Q1 = np.percentile(dist_lst , 25)
Q3 = np.percentile(dist_lst , 75)
# method 2.
Q1,Q3 = np.percentile(dist_lst , [25,75])


In [31]:
IQR = Q3 - Q1
ul = Q3+1.5*IQR
ll = Q1-1.5*IQR
print(ul,ll)

15.539512645695865 1.7419044602866576


In [32]:
Q1

6.9160075298151105

In [33]:
Q3

10.365409576167412

In [34]:
def euclidean_distance2(row1, row2):
    distance =0
	#print(len(row1)-1) this is to ensure that we calculate 6 points
    for i in range(8):

	

        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

In [35]:
dist_lst2=[]
filtered_lst=[]
index_lst=[]
for i in range(len(components2[:160])):
    dist_lst2.append(euclidean_distance2(components2[i],dmso_centroid))
    if euclidean_distance2(components2[i],dmso_centroid)>ul:
        filtered_lst.append(components2[i])
        index_lst.append(i)
#filtered_lst
#dist_lst2
print(len(filtered_lst))
print(len(dist_lst2))
print(len(index_lst))
#filtered_lst


118
160
118


In [36]:
#index_lst

In [37]:
# labels for class. second time
class_name=[]
cnt1=cnt2=cnt3=cnt4=cnt5=0

for i in range(len(index_lst)):
    if index_lst[i]<32:
        class_name.append('DNA')
        cnt1+=1

    
    elif index_lst[i]<64:
        class_name.append('MT')
        cnt2+=1

    
    elif index_lst[i]<96:
        class_name.append('HSP')
        cnt3+=1
    
    elif index_lst[i]<128:
        cnt4+=1
        
        class_name.append('PROT')
    
    elif index_lst[i]<160:
        cnt5+=1
        class_name.append('HDAC')

for i in range(32):
    class_name.append("DMSO")
len(class_name)
predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
print(predict_counter)


[20, 21, 32, 31, 14]


In [38]:
#second scatterplot
components5=[]
for i in range(len(index_lst)):
    components5.append(components[i])
for i in range(160,192):
    components5.append(components[i])
components5

[array([-9.21083078,  1.97195582,  1.98523923, -6.25359853, -5.17482787,
        -5.08805572, -3.17178735, -3.51084064]),
 array([-11.42738569,  -2.2365907 ,  -0.07614642,  -5.21843842,
         -0.88259846,  -1.41728537,  -1.5794639 ,  -3.88344548]),
 array([-9.54858715,  0.54428609,  1.28856259, -4.71660152, -1.36451628,
        -3.41021009, -1.76905266, -3.66946488]),
 array([-8.74653182,  1.90409143,  2.41664311, -4.62169475, -3.73849134,
        -5.86268017, -2.55765999, -4.0281719 ]),
 array([-9.2437941 ,  0.81396035,  1.89736498, -6.67002342,  0.64729456,
        -1.95573348, -1.50338767, -1.73935384]),
 array([-10.71897198,  -1.17281023,   0.26653841,  -7.67976213,
          5.68068231,   5.41558173,   1.38525583,   0.05440409]),
 array([-11.52283484,  -4.71601228,  -0.57591755,  -1.74499869,
          6.42670479,  -2.42371474,  -0.63197595,  -1.98854666]),
 array([-11.18891594,  -3.95939608,   0.09094905,  -8.16177457,
          2.98737005,   3.83804209,   0.57220942,  -0.9777

In [39]:
filtered_lst

[[-9.21083077636569,
  1.9719558186319333,
  1.9852392300983022,
  -6.253598532984788,
  -5.174827868939233,
  -5.088055717253541,
  -3.17178734878487,
  -3.5108406350171744,
  'Gemcitabine+Etoposide+1'],
 [-8.746531816158011,
  1.9040914257426993,
  2.416643114173005,
  -4.621694753211207,
  -3.73849133516125,
  -5.862680171736095,
  -2.5576599866571446,
  -4.028171901707396,
  'Gemcitabine+Etoposide+1'],
 [-10.718971978125513,
  -1.1728102286317053,
  0.2665384105983268,
  -7.679762128429364,
  5.680682307155359,
  5.415581730168927,
  1.385255828966315,
  0.054404094602309064,
  'Gemcitabine+Etoposide+2'],
 [-11.188915942496394,
  -3.9593960842738336,
  0.09094904957306103,
  -8.161774571961228,
  2.9873700495841358,
  3.838042094060566,
  0.5722094162641219,
  -0.9777381360477485,
  'Gemcitabine+Etoposide+2'],
 [-17.48923380984229,
  -0.2497568147383569,
  -1.905657820515722,
  -4.715103894342318,
  2.211329055655051,
  5.337750094057313,
  3.6451576620970667,
  -2.4461980461453896

In [40]:
fig = px.scatter(components5, x=0, y=1, color=class_name)
#training['drug_name']
fig.show()

In [41]:
#after using pca to do the filter, we gonna use LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis(n_components=4)
y2=[]
for i in range(32):
    y2.append('DNA')
for j in range(32):
    y2.append('MT')
for k in range(32):
    y2.append('HSP')
for m in range(32):
    y2.append('PROT')
for n in range(32):
    y2.append('HDAC')
for k in range(32):
    y2.append("DMSO")
#model.fit(X_drug, y)
#X_drug2 = model.transform(X_drug)
X_drug5=training.iloc[:,2:240].values
X_drug5=model.fit(X_drug5,y2).transform(X_drug5)

In [42]:
len(X_drug5)

192

In [43]:
# Create a function
def select_n_components(var_ratio, goal_var: float) -> int:
    # Set initial variance explained so far
    total_variance = 0.0
    
    # Set initial number of features
    n_components = 0
    
    # For the explained variance of each feature:
    for explained_variance in var_ratio:
        
        # Add the explained variance to the total
        total_variance += explained_variance
        
        # Add one to the number of components
        n_components += 1
        
        # If we reach our goal level of explained variance
        if total_variance >= goal_var:
            # End the loop
            break
            
    # Return the number of components
    return n_components

In [44]:
lda = LinearDiscriminantAnalysis(n_components=None)
X_lda=lda.fit(X_drug5,y2)
lda_var_ratios = lda.explained_variance_ratio_
print(lda_var_ratios)
print(select_n_components(lda_var_ratios, 0.95))
print(select_n_components(lda_var_ratios, 0.85))
print(select_n_components(lda_var_ratios, 0.75))
print(select_n_components(lda_var_ratios, 0.65))
print(select_n_components(lda_var_ratios, 0.35))
#print(X_drug5)

[0.36039048 0.2993837  0.23534198 0.10488384]
4
3
3
2
1


In [45]:
filtered_lda=np.ndarray.tolist(X_drug5)

In [46]:
#filtered_lda
filtered_drug=[]
for i in range(len(index_lst)):
    filtered_drug.append(filtered_lda[i])
for i in range(160,192):
    filtered_drug.append(filtered_lda[i])
print(len(filtered_drug),len(class_name))


150 150


In [47]:
fig = px.scatter(filtered_drug, x=0, y=1, color=class_name)
#training['drug_name']
fig.show()

In [48]:
#original figure
class_name
fig = px.scatter(X_drug5, x=0, y=1, color=train_drug_name_without_concentration2)
#training['drug_name']
fig.show()

In [49]:
#bootstrapping
for i in range(len(filtered_lst)):
    print(filtered_lst[i][-1])

Gemcitabine+Etoposide+1
Gemcitabine+Etoposide+1
Gemcitabine+Etoposide+2
Gemcitabine+Etoposide+2
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Etoposide+Etoposide+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+1
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Gemcitabine+DMSO+2
Etoposide+DMSO+1
Etoposide+DMSO+1
Etoposide+DMSO+1
Etoposide+DMSO+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+1
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Vinblastine+2
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+1
Paclitaxel+Paclitaxel+2
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+1
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
Paclitaxel+DMSO+2
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+1
17AAG+AUY922+2
17AAG+AUY922+2
17AAG+AUY922+2
17AAG+AUY922+2
AUY922+AUY92

In [50]:
len(filtered_lst)

118

In [51]:
def accuracy(list1,list2):
    length=len(list1)
    list3=[]
    for i in range(cnt1//4):
        list3.append(list2[0])
    for j in range(cnt2//4):
        list3.append(list2[1])
    for m in range(cnt3//4):
        list3.append(list2[2])
    for n in range(cnt4//4):
        list3.append(list2[3])
    for k in range(cnt5//4):
        list3.append(list2[4])
    for k in range(8):
        list3.append(list2[5])

    counter=0
    for k in range(len(list1)):

        if list1[k]==list3[k]:
            counter+=1
    return counter/length



In [52]:
len(index_lst)

118

In [53]:
lst=[1,2,3,4,5,6]
print(lst[:4])

[1, 2, 3, 4]


In [54]:
print(predict_counter)
#predict:1,5,7,4,1  18
#training:84-18=56
#56+24=90

[20, 21, 32, 31, 14]


In [55]:
#training and testing data preparation
#

import random
global random_chosen
global chosen_index_lst
global left_lst

random_chosen=[]
chosen_index_lst=[]

chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
chosen_index_lst

#print([cnt1,cnt2,cnt3,cnt4,cnt5])
#print(chosen_index_lst)
left_lst=list(set(index_lst)^set(chosen_index_lst))
#print(left_lst)
#print(len(chosen_index_lst))
#print(len(left_lst))
#print(len(chosen_index_lst)+len(left_lst))

In [56]:
len(chosen_index_lst)
len(index_lst)
len(left_lst)

90

In [57]:
#training and testing dataset
import random

global training_index
global testing_index
global dmso_left
global left_lst

dmso_index=[]
for i in range(160,192):
    dmso_index.append(i)
dmso_chosen=random.sample(dmso_index,32//4)
#chosen_index_lst+=dmso_chosen
dmso_left=list(set(dmso_index)^set(dmso_chosen))
print(len(dmso_left))
training_index=left_lst+dmso_left
testing_index=chosen_index_lst+dmso_chosen
#print(len(training_index))
#print(len(testing_index))


24


In [58]:
len(dmso_left)
len(left_lst)

90

In [59]:
#training data and testing data

global X_train
global X_test
X_train=[]
X_test=[]
for i in range(len(training_index)):
    X_train.append(X_drug5[training_index[i]])
for i in range(len(testing_index)):
    X_test.append(X_drug5[testing_index[i]])


In [60]:
len(index_lst)

118

In [61]:
# labels for class. second time

global class_name_train
index_lst2=training_index
print(len(index_lst2))
#class_name_train=[]
#cnt1=cnt2=cnt3=cnt4=cnt5=0
class_name_train=[]
for i in range(len(index_lst2)):
    if index_lst2[i]<32:
        class_name_train.append('DNA')
        
        #cnt1+=1

    
    elif index_lst2[i]<64:
        class_name_train.append('MT')
        
        #cnt2+=1

    
    elif index_lst2[i]<96:
        class_name_train.append('HSP')
        
    #cnt3+=1

    elif index_lst2[i]<128:
        #cnt4+=1
        
        class_name_train.append('PROT')
        
    
    elif index_lst2[i]<160:
        #cnt5+=1
        class_name_train.append('HDAC')
        
print(len(class_name_train))
for i in range(24):
    class_name_train.append("DMSO")
print(len(class_name_train))
#print(len(class_name))
#predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
#print(predict_counter)
#class_name_train=class_name

114
90
114


In [62]:
len(training_index)
len(testing_index)

36

In [69]:
X_train

[array([-0.92965396,  9.23175327, -7.74497262,  7.89566123]),
 array([-4.44111345, 13.25961829, -8.73829101,  6.47604083]),
 array([-4.55895265,  9.75879932, -7.66856245,  8.87909384]),
 array([-3.51534256, 11.22905796, -8.74753436,  8.22667749]),
 array([-2.78070683, 10.69705749, -8.64186971,  7.48342037]),
 array([-3.06662117,  9.61446191, -8.52684992,  6.68673423]),
 array([-3.49131286, 11.60293763, -7.42520876,  6.95418337]),
 array([-0.42005266, 11.80600164, -6.856561  ,  7.50842826]),
 array([-2.98079767, 10.36600616, -9.30105793,  5.74757047]),
 array([-1.94082737,  9.31873763, -7.49360872,  6.75435353]),
 array([-2.61403098,  9.31021007, -7.53782493,  7.82491924]),
 array([-3.53272644, 11.95412825, -9.76437451,  7.56005689]),
 array([-2.64657684, 11.31446423, -7.44865634,  7.63483643]),
 array([-1.71909362, 10.88201814, -8.2987994 ,  7.15501639]),
 array([-3.24128034, 10.00698141, -8.56603653,  7.41202463]),
 array([  4.13026733, -16.22278349,  12.10228568,   8.06650319]),
 arr

In [63]:
#prediction LDA
model2 = LinearDiscriminantAnalysis(n_components=4)
model2.fit(X_train,class_name_train)
yhat2=model2.predict(X_test)

print(yhat2)
print(len(yhat2))

['DNA' 'DNA' 'DNA' 'DNA' 'DNA' 'MT' 'MT' 'MT' 'MT' 'MT' 'HSP' 'HSP' 'HSP'
 'HSP' 'HSP' 'HSP' 'HSP' 'HSP' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT' 'PROT'
 'PROT' 'HDAC' 'HDAC' 'HDAC' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO' 'DMSO'
 'DMSO' 'DMSO']
36


In [64]:
#accuracy
accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","DMSO"])

1.0

In [65]:
accuracy_lst=[]
def pipeline():
    
    import random
    global random_chosen
    global chosen_index_lst
    global left_lst

    random_chosen=[]
    chosen_index_lst=[]

    chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
    chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
    chosen_index_lst

    #print([cnt1,cnt2,cnt3,cnt4,cnt5])
    #print(chosen_index_lst)
    left_lst=list(set(index_lst)^set(chosen_index_lst))
    #print(left_lst)
    #print(len(chosen_index_lst))
    #print(len(left_lst))
    #print(len(chosen_index_lst)+len(left_lst))



    # %%
    #training and testing dataset
    import random

    global training_index
    global testing_index
    global dmso_left
    

    dmso_index=[]
    for i in range(160,192):
        dmso_index.append(i)
    dmso_chosen=random.sample(dmso_index,32//4)
    #chosen_index_lst+=dmso_chosen
    dmso_left=list(set(dmso_index)^set(dmso_chosen))
    #print(len(dmso_left))
    training_index=left_lst+dmso_left
    testing_index=chosen_index_lst+dmso_chosen
    #print(len(training_index))
    #print(len(testing_index))


    # %%
    #training data and testing data

    global X_train
    global X_test
    X_train=[]
    X_test=[]
    for i in range(len(training_index)):
        X_train.append(X_drug5[training_index[i]])
    for i in range(len(testing_index)):
        X_test.append(X_drug5[testing_index[i]])


    # %%
    #len(index_lst)

    # %%
    # labels for class. second time

    global class_name_train
    index_lst2=training_index
    #print(len(index_lst2))
    #class_name_train=[]
    #cnt1=cnt2=cnt3=cnt4=cnt5=0
    class_name_train=[]
    for i in range(len(index_lst2)):
        if index_lst2[i]<32:
            class_name_train.append('DNA')
            
            #cnt1+=1

        
        elif index_lst2[i]<64:
            class_name_train.append('MT')
            
            #cnt2+=1

        
        elif index_lst2[i]<96:
            class_name_train.append('HSP')
            
        #cnt3+=1

        elif index_lst2[i]<128:
            #cnt4+=1
            
            class_name_train.append('PROT')
            
        
        elif index_lst2[i]<160:
            #cnt5+=1
            class_name_train.append('HDAC')
            
    #print(len(class_name_train))
    for i in range(24):
        class_name_train.append("DMSO")
    #print(len(class_name_train))
    #print(len(class_name))
    #predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
    #print(predict_counter)
    #class_name_train=class_name




    # %%
    #prediction LDA
    model2 = LinearDiscriminantAnalysis(n_components=4)
    model2.fit(X_train,class_name_train)
    yhat2=model2.predict(X_test)

    #print(yhat2)
    #print(len(yhat2))

    # %%
    #accuracy
    accuracy_score=accuracy( yhat2,['DNA',"MT","HSP","PROT","HDAC","DMSO"])
    accuracy_lst.append(accuracy_score)

    # %%
    
    

In [66]:
#ten times test (LDA)
accuracy_lst=[]
for i in range(30):
    pipeline()
print(accuracy_lst)
print("average accuracy: "+str(sum(accuracy_lst)/len(accuracy_lst)))


[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
average accuracy: 1.0


In [67]:
#prediction
accuracy_lst=[]
def pipeline():
    
    import random
    global random_chosen
    global chosen_index_lst
    global left_lst

    random_chosen=[]
    chosen_index_lst=[]

    chosen_index_lst+=random.sample(index_lst[:cnt1],cnt1//4)
    chosen_index_lst+=random.sample(index_lst[cnt1:cnt1+cnt2],cnt2//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2:cnt1+cnt2+cnt3],cnt3//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3:cnt1+cnt2+cnt3+cnt4],cnt4//4)
    chosen_index_lst+=random.sample(index_lst[cnt1+cnt2+cnt3+cnt4:cnt1+cnt2+cnt3+cnt4+cnt5],cnt5//4)
    chosen_index_lst

    #print([cnt1,cnt2,cnt3,cnt4,cnt5])
    #print(chosen_index_lst)
    left_lst=list(set(index_lst)^set(chosen_index_lst))
    #print(left_lst)
    #print(len(chosen_index_lst))
    #print(len(left_lst))
    #print(len(chosen_index_lst)+len(left_lst))



    # %%
    #training and testing dataset
    import random

    global training_index
    global testing_index
    global dmso_left
    

    dmso_index=[]
    for i in range(160,192):
        dmso_index.append(i)
    dmso_chosen=random.sample(dmso_index,32//4)
    #chosen_index_lst+=dmso_chosen
    dmso_left=list(set(dmso_index)^set(dmso_chosen))
    #print(len(dmso_left))
    training_index=left_lst+dmso_left
    testing_index=chosen_index_lst+dmso_chosen
    #print(len(training_index))
    #print(len(testing_index))


    # %%
    #training data and testing data

    global X_train
    global X_test
    X_train=[]
    X_test=[]
    for i in range(len(training_index)):
        X_train.append(X_drug5[training_index[i]])
    for i in range(len(testing_index)):
        X_test.append(X_drug5[testing_index[i]])


    # %%
    #len(index_lst)

    # %%
    # labels for class. second time

    global class_name_train
    index_lst2=training_index
    #print(len(index_lst2))
    #class_name_train=[]
    #cnt1=cnt2=cnt3=cnt4=cnt5=0
    class_name_train=[]
    for i in range(len(index_lst2)):
        if index_lst2[i]<32:
            class_name_train.append('DNA')
            
            #cnt1+=1

        
        elif index_lst2[i]<64:
            class_name_train.append('MT')
            
            #cnt2+=1

        
        elif index_lst2[i]<96:
            class_name_train.append('HSP')
            
        #cnt3+=1

        elif index_lst2[i]<128:
            #cnt4+=1
            
            class_name_train.append('PROT')
            
        
        elif index_lst2[i]<160:
            #cnt5+=1
            class_name_train.append('HDAC')
            
    #print(len(class_name_train))
    for i in range(24):
        class_name_train.append("DMSO")
    #print(len(class_name_train))
    #print(len(class_name))
    #predict_counter=[cnt1,cnt2,cnt3,cnt4,cnt5]
    #print(predict_counter)
    #class_name_train=class_name




    # %%
    #prediction LDA
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import accuracy_score
    knn5 = KNeighborsClassifier(n_neighbors=22)
    knn5.fit(X_train, class_name_train)
    y_pred_5 = knn5.predict(X_test)
    #model2 = LinearDiscriminantAnalysis(n_components=4)
    #model2.fit(X_train,class_name_train)
    #yhat2=model2.predict(X_test)

    #print(yhat2)
    #print(len(yhat2))

    # %%
    #accuracy
    accuracy_score=accuracy( y_pred_5,['DNA',"MT","HSP","PROT","HDAC","DMSO"])
    accuracy_lst.append(accuracy_score)

    # %%
    
    
#knn

#print("Accuracy with k=5", accuracy_score(y_test, y_pred_5)*100)

In [68]:
accuracy_lst=[]
for i in range(30):
    pipeline()
#print(accuracy_lst)
print(sum(accuracy_lst)/len(accuracy_lst))


0.9166666666666671
